const actinium = [
    {nucleodeCount: '203', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '204', decayType: ['a']},
    {nucleodeCount: '205', decayType: ['a']},
    {nucleodeCount: '206', decayType: ['a']},
    {nucleodeCount: '206m1', decayType: ['a']},
    {nucleodeCount: '206m2', decayType: ['a']},
    {nucleodeCount: '207', decayType: ['a']},
    {nucleodeCount: '208', decayType: ['a (99%)']},
    {nucleodeCount: '208', decayType: ['b<sup>+</sup> (1%)']},
    {nucleodeCount: '208m', decayType: ['a (89%)']},
    {nucleodeCount: '208m', decayType: ['[[Isomeric transition', 'IT]] (10%)']},
    {nucleodeCount: '208m', decayType: ['b<sup>+</sup> (1%)']},
    {nucleodeCount: '209', decayType: ['a (99%)']},
    {nucleodeCount: '209', decayType: ['b<sup>+</sup> (1%)']},
    {nucleodeCount: '210', decayType: ['a (96%)']},
    {nucleodeCount: '210', decayType: ['b<sup>+</sup> (4%)']},
    {nucleodeCount: '211', decayType: ['a (99.8%)']},
    {nucleodeCount: '211', decayType: ['b<sup>+</sup> (.2%)']},
    {nucleodeCount: '212', decayType: ['a (97%)']},
    {nucleodeCount: '212', decayType: ['b<sup>+</sup> (3%)']},
    {nucleodeCount: '213', decayType: ['a']},
    {nucleodeCount: '213', decayType: ['b<sup>+</sup> (rare)']},
    {nucleodeCount: '214', decayType: ['a (89%)']},
    {nucleodeCount: '214', decayType: ['b<sup>+</sup> (11%)']},
    {nucleodeCount: '215', decayType: ['a (99.91%)']},
    {nucleodeCount: '215', decayType: ['b<sup>+</sup> (.09%)']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m1', decayType: ['a']},
    {nucleodeCount: '216m2', decayType: ['IT']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m', decayType: ['IT']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['a (99(1)%)']},
    {nucleodeCount: '222', decayType: ['b<sup>+</sup> (1(1)%){{r', 'g=n', 'r=This decay mode has been observed, but only an upper limit of branching ratio is experimentally known{{NUBASE2020', 'ref}}}}']},
    {nucleodeCount: '222m', decayType: ['a (98.6%)']},
    {nucleodeCount: '222m', decayType: ['b<sup>+</sup> (1.4%)']},
    {nucleodeCount: '222m', decayType: ['IT?']},
    {nucleodeCount: '223', decayType: ['a (99%)']},
    {nucleodeCount: '223', decayType: ['[[Electron capture', 'EC]] (1%)']},
    {nucleodeCount: '223', decayType: ['[[Cluster decay', 'CD]] (3.2x10<sup>-9</sup>%)']},
    {nucleodeCount: '224', decayType: ['b<sup>+</sup> (90.9%)']},
    {nucleodeCount: '224', decayType: ['a (9.1%)']},
    {nucleodeCount: '224', decayType: ['b<sup>-</sup> (1.6%)']},
    {nucleodeCount: '225', decayType: ['a']},
    {nucleodeCount: '225', decayType: ['rowspan=2', '(3/2-)']},
    {nucleodeCount: '225', decayType: ['CD (6x10<sup>-10</sup>%)']},
    {nucleodeCount: '226', decayType: ['b<sup>-</sup> (83%)']},
    {nucleodeCount: '226', decayType: ['EC (17%)']},
    {nucleodeCount: '226', decayType: ['a (.006%)']},
    {nucleodeCount: '227', decayType: ['b<sup>-</sup> (98.62%)']},
    {nucleodeCount: '227', decayType: ['rowspan=2', '3/2-']},
    {nucleodeCount: '227', decayType: ['a (1.38%)']},
    {nucleodeCount: '228', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '228', decayType: ['3+']},
    {nucleodeCount: '229', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '230', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '231', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '232', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '233', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '234', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '235', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '236', decayType: ['b<sup>-</sup>']},
]
