const actinium = [
    {nucleodeCount: '203', decayType: ['a']},
    {nucleodeCount: '204', decayType: ['a']},
    {nucleodeCount: '205', decayType: ['a']},
    {nucleodeCount: '206', decayType: ['a']},
    {nucleodeCount: '206m1', decayType: ['a']},
    {nucleodeCount: '206m2', decayType: ['a']},
    {nucleodeCount: '207', decayType: ['a']},
    {nucleodeCount: '208', decayType: ['a', 'b+']},
    {nucleodeCount: '208m', decayType: ['a', 'IT', 'b+']},
    {nucleodeCount: '209', decayType: ['a', 'b+']},
    {nucleodeCount: '210', decayType: ['a', 'b+']},
    {nucleodeCount: '211', decayType: ['a', 'b+']},
    {nucleodeCount: '212', decayType: ['a', 'b+']},
    {nucleodeCount: '213', decayType: ['a', 'b+']},
    {nucleodeCount: '214', decayType: ['a', 'b+']},
    {nucleodeCount: '215', decayType: ['a', 'b+']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m1', decayType: ['a']},
    {nucleodeCount: '216m2', decayType: ['IT']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m', decayType: ['IT']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['a', 'b+']},
    {nucleodeCount: '222m', decayType: ['a', 'b+']},
    {nucleodeCount: '223', decayType: ['a', 'e']},
    {nucleodeCount: '224', decayType: ['b+', 'a', 'b-']},
    {nucleodeCount: '225', decayType: ['a']},
    {nucleodeCount: '226', decayType: ['b-', 'e', 'a']},
    {nucleodeCount: '227', decayType: ['b-', 'a']},
    {nucleodeCount: '228', decayType: ['b-']},
    {nucleodeCount: '229', decayType: ['b-']},
    {nucleodeCount: '230', decayType: ['b-']},
    {nucleodeCount: '231', decayType: ['b-']},
    {nucleodeCount: '232', decayType: ['b-']},
    {nucleodeCount: '233', decayType: ['b-']},
    {nucleodeCount: '234', decayType: ['b-']},
    {nucleodeCount: '235', decayType: ['b-']},
    {nucleodeCount: '236', decayType: ['b-']}
]
