const aluminium = [
    {nucleodeCount: '21', decayType: ['p']},
    {nucleodeCount: '22', decayType: ['b+, p', 'b+', 'b+, 2p', 'b+, a']},
    {nucleodeCount: '23', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '24', decayType: ['b+', 'b+, a', 'b+, p']},
    {nucleodeCount: '24m', decayType: ['IT', 'b+', 'b+, a']},
    {nucleodeCount: '25', decayType: ['b+']},
    {nucleodeCount: '26', decayType: ['b+']},
    {nucleodeCount: '26m', decayType: ['b+']},
    {nucleodeCount: '27', decayType: ['Stable']},
    {nucleodeCount: '28', decayType: ['b-']},
    {nucleodeCount: '29', decayType: ['b-']},
    {nucleodeCount: '30', decayType: ['b-']},
    {nucleodeCount: '31', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '32', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '32m', decayType: ['IT']},
    {nucleodeCount: '33', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '34', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '34m', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '35', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '36', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '37', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '38', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '39', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '40', decayType: ['b-, n', 'b-, 2n', 'b-']},
    {nucleodeCount: '41', decayType: ['b-, n', 'b-, 2n', 'b-']},
    {nucleodeCount: '43', decayType: ['b-']}
]
