const aluminium = [
    {nucleodeCount: '21', decayType: ['p']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup>, p (55%)']},
    {nucleodeCount: '22', decayType: ['[[beta decay', 'b<sup>+</sup>]] (44%)']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup>, 2p (1.10%)']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup>, [[alpha decay', 'a]] (0.038%)']},
    {nucleodeCount: '23', decayType: ['b<sup>+</sup> (98.78%)']},
    {nucleodeCount: '23', decayType: ['b<sup>+</sup>, p (1.22%)']},
    {nucleodeCount: '24', decayType: ['b<sup>+</sup> (99.96%)']},
    {nucleodeCount: '24', decayType: ['b<sup>+</sup>, a (0.035%)']},
    {nucleodeCount: '24', decayType: ['b<sup>+</sup>, p (0.0016%)']},
    {nucleodeCount: '24m', decayType: ['[[Isomeric transition', 'IT]] (82.5%)']},
    {nucleodeCount: '24m', decayType: ['b<sup>+</sup> (17.5%)']},
    {nucleodeCount: '24m', decayType: ['b<sup>+</sup>, a (0.028%)']},
    {nucleodeCount: '25', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '26', decayType: ['b<sup>+</sup> (85%)']},
    {nucleodeCount: '26m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '28', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '29', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '30', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup> (>98.4%)']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (<1.6%)']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup> (99.3%)']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup>, n (0.7%)']},
    {nucleodeCount: '32m', decayType: ['IT']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup> (91.5%)']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup>, n (8.5%)']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup> (74%)']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup>, n (26%)']},
    {nucleodeCount: '34m', decayType: ['b<sup>-</sup> (89%)']},
    {nucleodeCount: '34m', decayType: ['b<sup>-</sup>, n (11%)']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup> (64.2%)']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>, n (35.8%)']},
    {nucleodeCount: '36', decayType: ['b<sup>-</sup> (>69%)']},
    {nucleodeCount: '36', decayType: ['b<sup>-</sup>, n (<31%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>, n (52%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup> (<47%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>, 2n (>1%)']},
    {nucleodeCount: '38', decayType: ['b<sup>-</sup>, n (84%)']},
    {nucleodeCount: '38', decayType: ['b<sup>-</sup> (16%)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>, n (97%)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup> (3%)']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup>, n (64%)']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup>, 2n (20%)']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup> (16%)']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>, n (86%)']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>, 2n (11%)']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup> (3%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup>?']},
]
