const americium = [
    {nucleodeCount: 'None', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '229', decayType: ['a']},
    {nucleodeCount: '230', decayType: ['[[beta decay', 'b<sup>+</sup>]] (<70%)']},
    {nucleodeCount: '232', decayType: ['b<sup>+</sup> (97%)']},
    {nucleodeCount: '232', decayType: ['a (3%)']},
    {nucleodeCount: '233', decayType: ['b<sup>+</sup> (95.5%)']},
    {nucleodeCount: '233', decayType: ['a (4.5%)']},
    {nucleodeCount: '234', decayType: ['b<sup>+</sup> (99.95%)']},
    {nucleodeCount: '234', decayType: ['a (0.039%)']},
    {nucleodeCount: '235', decayType: ['b<sup>+</sup> (99.60%)']},
    {nucleodeCount: '235', decayType: ['a (0.40%)']},
    {nucleodeCount: '236', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '236', decayType: ['a (4x10<sup>-3</sup>%)']},
    {nucleodeCount: '236m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '236m', decayType: ['a ?']},
    {nucleodeCount: '237', decayType: ['b<sup>+</sup> (99.975%)']},
    {nucleodeCount: '237', decayType: ['a (.025%)']},
    {nucleodeCount: '238', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '238', decayType: ['a (1.0x10<sup>-4</sup>%)']},
    {nucleodeCount: '238m', decayType: ['IT ?']},
    {nucleodeCount: '239', decayType: ['[[Electron capture', 'EC]] (99.99%)']},
    {nucleodeCount: '239', decayType: ['a (0.01%)']},
    {nucleodeCount: '239m', decayType: ['IT ?']},
    {nucleodeCount: '240', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '240', decayType: ['a (1.9x10<sup>-4</sup>%)']},
    {nucleodeCount: '240m', decayType: ['IT ?']},
    {nucleodeCount: '241', decayType: ['a']},
    {nucleodeCount: '242', decayType: ['b<sup>-</sup> (82.7%)']},
    {nucleodeCount: '242', decayType: ['EC (17.3%)']},
    {nucleodeCount: '242m1', decayType: ['[[Isomeric transition', 'IT]] (99.54%)']},
    {nucleodeCount: '242m1', decayType: ['a (.46%)']},
    {nucleodeCount: '242m2', decayType: ['IT ?']},
    {nucleodeCount: '243', decayType: ['a']},
    {nucleodeCount: '243m', decayType: ['IT ?']},
    {nucleodeCount: '244', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '244m1', decayType: ['b<sup>-</sup> (99.96%)']},
    {nucleodeCount: '244m1', decayType: ['EC (0.0364%)']},
    {nucleodeCount: '244m2', decayType: ['IT ?']},
    {nucleodeCount: '244m3', decayType: ['IT ?']},
    {nucleodeCount: '245', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '245m', decayType: ['IT ?']},
    {nucleodeCount: '246', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '246m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '246m1', decayType: ['IT ?']},
    {nucleodeCount: '246m2', decayType: ['IT ?']},
    {nucleodeCount: '247', decayType: ['b<sup>-</sup>']},
]
