const americium = [
    {nucleodeCount: '223', decayType: ['a']},
    {nucleodeCount: '229', decayType: ['a']},
    {nucleodeCount: '230', decayType: ['b+']},
    {nucleodeCount: '232', decayType: ['b+', 'a']},
    {nucleodeCount: '233', decayType: ['b+', 'a']},
    {nucleodeCount: '234', decayType: ['b+', 'a']},
    {nucleodeCount: '235', decayType: ['b+', 'a']},
    {nucleodeCount: '236', decayType: ['b+', 'a']},
    {nucleodeCount: '236m', decayType: ['b+', 'a']},
    {nucleodeCount: '237', decayType: ['b+', 'a']},
    {nucleodeCount: '238', decayType: ['b+', 'a']},
    {nucleodeCount: '238m', decayType: ['IT']},
    {nucleodeCount: '239', decayType: ['e', 'a']},
    {nucleodeCount: '239m', decayType: ['IT', 'b+']},
    {nucleodeCount: '240', decayType: ['a']},
    {nucleodeCount: '240m', decayType: ['IT']},
    {nucleodeCount: '241', decayType: ['a']},
    {nucleodeCount: '242', decayType: ['b-']},
    {nucleodeCount: '242', decayType: ['e']},
    {nucleodeCount: '242m1', decayType: ['IT']},
    {nucleodeCount: '242m1', decayType: ['a']},
    {nucleodeCount: '242m2', decayType: ['IT']},
    {nucleodeCount: '243', decayType: ['a']},
    {nucleodeCount: '243m', decayType: ['IT']},
    {nucleodeCount: '244', decayType: ['b-']},
    {nucleodeCount: '244m1', decayType: ['b-']},
    {nucleodeCount: '244m1', decayType: ['EC']},
    {nucleodeCount: '244m2', decayType: ['IT']},
    {nucleodeCount: '244m3', decayType: ['IT']},
    {nucleodeCount: '245', decayType: ['b-']},
    {nucleodeCount: '245m', decayType: ['IT']},
    {nucleodeCount: '246', decayType: ['b-']},
    {nucleodeCount: '246m1', decayType: ['b-']},
    {nucleodeCount: '246m1', decayType: ['IT']},
    {nucleodeCount: '246m2', decayType: ['IT']},
    {nucleodeCount: '247', decayType: ['b-']}
]
