const antimony = [
    {nucleodeCount: '104', decayType: ['b+', 'p', 'b+, p', 'a']},
    {nucleodeCount: '105', decayType: ['b+', 'p', 'b+, p']},
    {nucleodeCount: '106', decayType: ['b+']},
    {nucleodeCount: '106m', decayType: ['IT']},
    {nucleodeCount: '107', decayType: ['b+']},
    {nucleodeCount: '108', decayType: ['b+']},
    {nucleodeCount: '109', decayType: ['b+']},
    {nucleodeCount: '110', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['b+']},
    {nucleodeCount: '112', decayType: ['b+']},
    {nucleodeCount: '112m', decayType: ['IT']},
    {nucleodeCount: '113', decayType: ['b+']},
    {nucleodeCount: '114', decayType: ['b+']},
    {nucleodeCount: '114m', decayType: ['IT']},
    {nucleodeCount: '115', decayType: ['b+']},
    {nucleodeCount: '115m', decayType: ['IT']},
    {nucleodeCount: '116', decayType: ['b+']},
    {nucleodeCount: '116m1', decayType: ['IT']},
    {nucleodeCount: '116m2', decayType: ['b+']},
    {nucleodeCount: '117', decayType: ['b+']},
    {nucleodeCount: '117m1', decayType: ['IT']},
    {nucleodeCount: '117m2', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b+']},
    {nucleodeCount: '118m1', decayType: ['IT']},
    {nucleodeCount: '118m2', decayType: ['b+']},
    {nucleodeCount: '119', decayType: ['e']},
    {nucleodeCount: '119m1', decayType: ['IT']},
    {nucleodeCount: '119m2', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b+']},
    {nucleodeCount: '120m1', decayType: ['b+']},
    {nucleodeCount: '120m2', decayType: ['IT']},
    {nucleodeCount: '120m3', decayType: ['IT']},
    {nucleodeCount: '121', decayType: ['Stable']},
    {nucleodeCount: '121m', decayType: ['IT']},
    {nucleodeCount: '122', decayType: ['b-', 'b+']},
    {nucleodeCount: '122m1', decayType: ['IT']},
    {nucleodeCount: '122m2', decayType: ['IT']},
    {nucleodeCount: '122m3', decayType: ['IT']},
    {nucleodeCount: '123', decayType: ['Stable']},
    {nucleodeCount: '123m1', decayType: ['IT']},
    {nucleodeCount: '123m2', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '124m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '124m2', decayType: ['IT']},
    {nucleodeCount: '124m3', decayType: ['IT']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125m1', decayType: ['IT']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '125m3', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '126m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '126m3', decayType: ['IT']},
    {nucleodeCount: '126m4', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127m1', decayType: ['IT']},
    {nucleodeCount: '127m2', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b-']},
    {nucleodeCount: '128m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '128m2', decayType: ['IT']},
    {nucleodeCount: '128m3', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b-']},
    {nucleodeCount: '129m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '129m2', decayType: ['IT']},
    {nucleodeCount: '129m3', decayType: ['IT']},
    {nucleodeCount: '130', decayType: ['b-']},
    {nucleodeCount: '130m1', decayType: ['b-']},
    {nucleodeCount: '130m2', decayType: ['IT']},
    {nucleodeCount: '130m3', decayType: ['IT']},
    {nucleodeCount: '130m4', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b-']},
    {nucleodeCount: '131m1', decayType: ['IT']},
    {nucleodeCount: '131m2', decayType: ['IT']},
    {nucleodeCount: '131m3', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b-']},
    {nucleodeCount: '132m1', decayType: ['b-']},
    {nucleodeCount: '132m2', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b-']},
    {nucleodeCount: '133m', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '134m', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '135', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '136', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '136m', decayType: ['IT']},
    {nucleodeCount: '137', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '138', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '139', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '140', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '140m', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '142', decayType: ['b-', 'b-, n', 'b-, 2n']}
]
