const argon = [
    {nucleodeCount: '29', decayType: ['[[proton emission', '2p]]']},
    {nucleodeCount: '30', decayType: ['2p']},
    {nucleodeCount: '31', decayType: ['[[Beta decay', 'b<sup>+</sup>]], p (68.3%)']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup> (22.63%)']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup>, 2p (9.0%)']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup>, 3p (0.07%)']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup>, p, [[alpha decay', 'a]]? (<0.38%)']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup>, a? (<0.03%)']},
    {nucleodeCount: '31', decayType: ['2p? (<0.03%)']},
    {nucleodeCount: '32', decayType: ['b<sup>+</sup> (64.42%)']},
    {nucleodeCount: '32', decayType: ['b<sup>+</sup>, p (35.58%)']},
    {nucleodeCount: '33', decayType: ['b<sup>+</sup> (61.3%)']},
    {nucleodeCount: '33', decayType: ['b<sup>+</sup>, p (38.7%)']},
    {nucleodeCount: '34', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '35', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '36', decayType: ['35.967545106(28)']},
    {nucleodeCount: '37', decayType: ['[[electron capture', 'EC]]']},
    {nucleodeCount: '39', decayType: ['38.9643130(54)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '40', decayType: ['0+']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '45', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '46', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '47', decayType: ['b<sup>-</sup> (>99.8%)']},
    {nucleodeCount: '47', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]]? (<0.2%)']},
    {nucleodeCount: '48', decayType: ['b<sup>-</sup> (62%)']},
    {nucleodeCount: '48', decayType: ['b<sup>-</sup>, n (38%)']},
    {nucleodeCount: '49', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '49', decayType: ['b<sup>-</sup>, n (29%)']},
    {nucleodeCount: '49', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '50', decayType: ['b<sup>-</sup> (63%)']},
    {nucleodeCount: '50', decayType: ['b<sup>-</sup>, n (37%)']},
    {nucleodeCount: '50', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '51', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '51', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '51', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '52', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '52', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '52', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '53', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '53', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '53', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '54', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '54', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '54', decayType: ['b<sup>-</sup>, 2n?']},
]
