const argon = [
    {nucleodeCount: '29', decayType: ['2p']},
    {nucleodeCount: '30', decayType: ['2p']},
    {nucleodeCount: '31', decayType: ['b+, p', 'b+', 'b+, 2p', 'b+, 3p', 'b+, p, a', 'b+, a', '2p']},
    {nucleodeCount: '32', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '33', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '34', decayType: ['b+']},
    {nucleodeCount: '35', decayType: ['b+']},
    {nucleodeCount: '36', decayType: ['Stable']},
    {nucleodeCount: '37', decayType: ['e']},
    {nucleodeCount: '38', decayType: ['Stable']},
    {nucleodeCount: '39', decayType: ['b-']},
    {nucleodeCount: '40', decayType: ['Stable']},
    {nucleodeCount: '41', decayType: ['b-']},
    {nucleodeCount: '42', decayType: ['b-']},
    {nucleodeCount: '43', decayType: ['b-']},
    {nucleodeCount: '44', decayType: ['b-']},
    {nucleodeCount: '45', decayType: ['b-']},
    {nucleodeCount: '46', decayType: ['b-']},
    {nucleodeCount: '47', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '48', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '49', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '49', decayType: ['b-, 2n']},
    {nucleodeCount: '50', decayType: ['b-' ,'b-, n', 'b-, 2n']},
    {nucleodeCount: '51', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '52', decayType: ['b-' ,'b-, n' ,'b-, 2n']},
    {nucleodeCount: '53', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '54', decayType: ['b-', 'b-, n', 'b-, 2n']}
]
