const arsenic = [
    {nucleodeCount: '64', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '65', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '66', decayType: ['b+']},
    {nucleodeCount: '66m1', decayType: ['IT']},
    {nucleodeCount: '66m2', decayType: ['IT']},
    {nucleodeCount: '67', decayType: ['b+']},
    {nucleodeCount: '68', decayType: ['b+']},
    {nucleodeCount: '68m', decayType: ['IT']},
    {nucleodeCount: '69', decayType: ['b+']},
    {nucleodeCount: '70', decayType: ['b+']},
    {nucleodeCount: '70m', decayType: ['IT']},
    {nucleodeCount: '71', decayType: ['b+']},
    {nucleodeCount: '72', decayType: ['b+']},
    {nucleodeCount: '73', decayType: ['e']},
    {nucleodeCount: '73m', decayType: ['IT']},
    {nucleodeCount: '74', decayType: ['b+', 'b-']},
    {nucleodeCount: '75', decayType: ['Stable']},
    {nucleodeCount: '75m', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['b-']},
    {nucleodeCount: '76m', decayType: ['IT']},
    {nucleodeCount: '77', decayType: ['b-']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '78', decayType: ['b-']},
    {nucleodeCount: '79', decayType: ['b-']},
    {nucleodeCount: '79m', decayType: ['IT']},
    {nucleodeCount: '80', decayType: ['b-']},
    {nucleodeCount: '81', decayType: ['b-']},
    {nucleodeCount: '82', decayType: ['b-']},
    {nucleodeCount: '82m', decayType: ['b-']},
    {nucleodeCount: '83', decayType: ['b-']},
    {nucleodeCount: '84', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '85', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '86', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '87', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '88', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '89', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '90', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '90m', decayType: ['IT']},
    {nucleodeCount: '91', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '92', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '93', decayType: ['Stable']},
    {nucleodeCount: '94', decayType: ['Stable']},
    {nucleodeCount: '95', decayType: ['Stable']}
]
