const astatine = [
    {nucleodeCount: '188', decayType: ['a', 'p']},
    {nucleodeCount: '190', decayType: ['a']},
    {nucleodeCount: '191', decayType: ['a']},
    {nucleodeCount: '191m', decayType: ['a']},
    {nucleodeCount: '192', decayType: ['a', 'b+']},
    {nucleodeCount: '192m', decayType: ['a', 'b+']},
    {nucleodeCount: '193', decayType: ['a']},
    {nucleodeCount: '193m1', decayType: ['a']},
    {nucleodeCount: '193m2', decayType: ['IT', 'a']},
    {nucleodeCount: '194', decayType: ['a', 'b+']},
    {nucleodeCount: '194m', decayType: ['a', 'b+']},
    {nucleodeCount: '195', decayType: ['a', 'b+']},
    {nucleodeCount: '195m', decayType: ['a', 'IT', 'b+']},
    {nucleodeCount: '196', decayType: ['a', 'b+']},
    {nucleodeCount: '196m1', decayType: ['a']},
    {nucleodeCount: '196m2', decayType: ['IT']},
    {nucleodeCount: '197', decayType: ['a', 'b+']},
    {nucleodeCount: '197m1', decayType: ['a', 'IT', 'b+']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['a', 'b+']},
    {nucleodeCount: '199', decayType: ['a', 'b+']},
    {nucleodeCount: '200', decayType: ['a', 'b+']},
    {nucleodeCount: '200m1', decayType: ['a', 'IT' ,'b+']},
    {nucleodeCount: '201', decayType: ['a', 'b+']},
    {nucleodeCount: '202', decayType: ['b+', 'a']},
    {nucleodeCount: '203', decayType: ['b+', 'a']},
    {nucleodeCount: '204', decayType: ['b+' ,'a']},
    {nucleodeCount: '204m', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b+' ,'a']},
    {nucleodeCount: '206', decayType: ['b+', 'a']},
    {nucleodeCount: '207', decayType: ['b+' ,'a']},
    {nucleodeCount: '208', decayType: ['b+' ,'a']},
    {nucleodeCount: '209', decayType: ['b+' ,'a']},
    {nucleodeCount: '210', decayType: ['b+', 'a']},
    {nucleodeCount: '211', decayType: ['e', 'a']},
    {nucleodeCount: '212', decayType: ['a', 'b+', 'b-']},
    {nucleodeCount: '212m1', decayType: ['a']},
    {nucleodeCount: '212m2', decayType: ['IT']},
    {nucleodeCount: '213', decayType: ['a', 'e']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214m1', decayType: ['a', 'IT']},
    {nucleodeCount: '214m2', decayType: ['a', 'IT']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m', decayType: ['a']},
    {nucleodeCount: '217', decayType: ['a', 'b-']},
    {nucleodeCount: '218', decayType: ['a', 'b-']},
    {nucleodeCount: '219', decayType: ['a' ,'b-']},
    {nucleodeCount: '220', decayType: ['b-', 'a']},
    {nucleodeCount: '221', decayType: ['b-']},
    {nucleodeCount: '222', decayType: ['b-']},
    {nucleodeCount: '223', decayType: ['b-']},
    {nucleodeCount: '224', decayType: ['b-']},
    {nucleodeCount: '225', decayType: ['b-']},
    {nucleodeCount: '226', decayType: ['b-']},
    {nucleodeCount: '227', decayType: ['b-']},
    {nucleodeCount: '228', decayType: ['b-']},
    {nucleodeCount: '229', decayType: ['b-']}
]