const astatine = [
    {nucleodeCount: '190', decayType: ['[[alpha decay', 'a]] (~50%)']},
    {nucleodeCount: '190', decayType: ['[[proton emission', 'p]] (~50%)']},
    {nucleodeCount: '190', decayType: ['a']},
    {nucleodeCount: '191', decayType: ['a']},
    {nucleodeCount: '191m', decayType: ['a']},
    {nucleodeCount: '192', decayType: ['a']},
    {nucleodeCount: '192', decayType: ['[[beta decay', 'b<sup>+</sup>]] (rare)']},
    {nucleodeCount: '192m', decayType: ['a']},
    {nucleodeCount: '192m', decayType: ['b<sup>+</sup> (rare)']},
    {nucleodeCount: '193', decayType: ['a']},
    {nucleodeCount: '193m1', decayType: ['a']},
    {nucleodeCount: '193m2', decayType: ['IT (76%)']},
    {nucleodeCount: '193m2', decayType: ['a (24%)']},
    {nucleodeCount: '194', decayType: ['a (91.7%#)']},
    {nucleodeCount: '194', decayType: ['b<sup>+</sup> (8.3%#)']},
    {nucleodeCount: '194m', decayType: ['a (91.7%#)']},
    {nucleodeCount: '194m', decayType: ['b<sup>+</sup> (8.3%#)']},
    {nucleodeCount: '195', decayType: ['a']},
    {nucleodeCount: '195', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '195m', decayType: ['a (88%)']},
    {nucleodeCount: '195m', decayType: ['[[Isomeric transition', 'IT]] (12%)']},
    {nucleodeCount: '195m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '196', decayType: ['a (97.5%)']},
    {nucleodeCount: '196', decayType: ['b<sup>+</sup> (2.5%)']},
    {nucleodeCount: '196m1', decayType: ['a']},
    {nucleodeCount: '196m2', decayType: ['IT']},
    {nucleodeCount: '197', decayType: ['a (96.1%)']},
    {nucleodeCount: '197', decayType: ['b<sup>+</sup> (3.9%)']},
    {nucleodeCount: '197m1', decayType: ['a']},
    {nucleodeCount: '197m1', decayType: ['IT (<0.004%)']},
    {nucleodeCount: '197m1', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['a (94%)']},
    {nucleodeCount: '198', decayType: ['b<sup>+</sup> (6%)']},
    {nucleodeCount: '199', decayType: ['a (89%)']},
    {nucleodeCount: '199', decayType: ['b<sup>+</sup> (11%)']},
    {nucleodeCount: '200', decayType: ['a (57%)']},
    {nucleodeCount: '200', decayType: ['b<sup>+</sup> (43%)']},
    {nucleodeCount: '200m1', decayType: ['a (43%)']},
    {nucleodeCount: '200m1', decayType: ['IT']},
    {nucleodeCount: '200m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '201', decayType: ['a (71%)']},
    {nucleodeCount: '201', decayType: ['b<sup>+</sup> (29%)']},
    {nucleodeCount: '202', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '202', decayType: ['a (12%)']},
    {nucleodeCount: '203', decayType: ['b<sup>+</sup> (69%)']},
    {nucleodeCount: '203', decayType: ['a (31%)']},
    {nucleodeCount: '204', decayType: ['b<sup>+</sup> (96%)']},
    {nucleodeCount: '204', decayType: ['a (3.8%)']},
    {nucleodeCount: '204m', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b<sup>+</sup> (90%)']},
    {nucleodeCount: '205', decayType: ['a (10%)']},
    {nucleodeCount: '206', decayType: ['b<sup>+</sup> (99.11%)']},
    {nucleodeCount: '206', decayType: ['a (0.9%)']},
    {nucleodeCount: '207', decayType: ['b<sup>+</sup> (91%)']},
    {nucleodeCount: '207', decayType: ['a (8.6%)']},
    {nucleodeCount: '208', decayType: ['b<sup>+</sup> (99.5%)']},
    {nucleodeCount: '208', decayType: ['a (0.55%)']},
    {nucleodeCount: '209', decayType: ['b<sup>+</sup> (96%)']},
    {nucleodeCount: '209', decayType: ['a (4.0%)']},
    {nucleodeCount: '210', decayType: ['b<sup>+</sup> (99.8%)']},
    {nucleodeCount: '210', decayType: ['a (0.18%)']},
    {nucleodeCount: '211', decayType: ['[[Electron capture', 'EC]] (58.2%)']},
    {nucleodeCount: '211', decayType: ['a (42%)']},
    {nucleodeCount: '212', decayType: ['314(2)&nbsp;ms']},
    {nucleodeCount: '212', decayType: ['a{{refn', 'group=n', 'Theoretically capable of b<sup>+</sup> decay to <sup>212</sup>Po or b<sup>-</sup> decay to <sup>212</sup>Rn; the branching ratios are expected to be <3x10<sup>-2</sup>% and <2x10<sup>-6</sup>% (partial half-lives >17.4 min and >182 d) respectively.<ref name="NUBASE 2003"/>{{NUBASE2020', 'ref}}<ref>{{cite web', 'url=https://www.nndc.bnl.gov/ensnds/212/At/adopted.pdf', 'title=Adopted Levels for <sup>212</sup>At', 'publisher=NNDC Chart of Nuclides}}</ref>}}']},
    {nucleodeCount: '212m1', decayType: ['a']},
    {nucleodeCount: '212m2', decayType: ['IT']},
    {nucleodeCount: '213', decayType: ['125(6)&nbsp;ns']},
    {nucleodeCount: '213', decayType: ['a{{refn', 'group=n', 'Theoretically capable of electron capture to <sup>213</sup>Po; the branching ratio is expected to be <2.5x10<sup>-12</sup>% (partial half-life >57.9 d).<ref>{{cite web', 'url=https://www.nndc.bnl.gov/ensnds/213/At/adopted.pdf', 'title=Adopted Levels for <sup>213</sup>At', 'publisher=NNDC Chart of Nuclides}}</ref>}}']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214m1', decayType: ['265(30)&nbsp;ns']},
    {nucleodeCount: '214m1', decayType: ['a{{refn', 'group=n', 'Theoretically capable of isomeric transition to <sup>214</sup>At{{NUBASE2020', 'ref}}}}']},
    {nucleodeCount: '214m2', decayType: ['760(15)&nbsp;ns']},
    {nucleodeCount: '214m2', decayType: ['a{{refn', 'group=n', 'Theoretically capable of isomeric transition to <sup>214</sup>At{{NUBASE2020', 'ref}}<ref>{{cite journal', 'last1=Ewan', 'first1=G. T.', 'last2=Hagberg', 'first2=E.', 'last3=Jonson', 'first3=B.', 'last4=Mattsson', 'first4=S.', 'last5=Tidemand-Petersson', 'first5=P.', 'title=New isomeric states in <sup>218</sup>Fr and <sup>214</sup>At', 'collaboration=The ISOLDE Collaboration, CERN, Geneva, Switzerland', 'journal=Nuclear Physics A', 'date=31 May 1982', 'volume=380', 'issue=3', 'pages=423-437', 'doi=10.1016/0375-9474(82)90568-1', 'url=https://www.sciencedirect.com/science/article/pii/0375947482905681 }}<br />"It is worth noting that although the energy deduced for the excited state in <sup>214</sup>At populated by the 7725 keV a-group, 231 keV, agrees well with the excitation energy of the 760 ns isomer, some or all the a-intensity found for this a-group cannot directly populate the isomer. The a-spectrum obtained in coincidence with the 7725 keV transition includes both the 8819 keV a-group from <sup>214</sup>At and the 8782 keV a-group from <sup>214</sup>At but we know that there is no isomeric transition. There must therefore be another state in the vicinity of the 233 keV isomeric state and a g-transition connecting the two close-lying states or the 7725 keV a-group is a narrow doublet feeding both states."</ref>}}']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['9/2-']},
    {nucleodeCount: '216', decayType: ['0.30(3)&nbsp;ms']},
    {nucleodeCount: '216', decayType: ['a{{refn', 'group=n', 'Theoretically capable of electron capture to <sup>216</sup>Po or b<sup>-</sup> decay to <sup>216</sup>Rn; the branching ratios are expected to be <3x10<sup>-7</sup>% and <6x10<sup>-3</sup>% (partial half-lives >1.2 d and >5.0 s) respectively.<ref name="NUBASE 2003"/>{{NUBASE2020', 'ref}}<ref>{{cite web', 'url=https://www.nndc.bnl.gov/ensnds/216/At/adopted.pdf', 'title=Adopted Levels for <sup>216</sup>At', 'publisher=NNDC Chart of Nuclides}}</ref>}}']},
    {nucleodeCount: '216m', decayType: ['a']},
    {nucleodeCount: '217', decayType: ['a (99.98%)']},
    {nucleodeCount: '217', decayType: ['rowspan=2', '9/2-']},
    {nucleodeCount: '217', decayType: ['b<sup>-</sup> (.012%)']},
    {nucleodeCount: '218', decayType: ['a (99.9%)']},
    {nucleodeCount: '218', decayType: ['rowspan=2', '(2-,3-)']},
    {nucleodeCount: '218', decayType: ['b<sup>-</sup> (0.1%)<ref name="NUBASE 2003" />']},
    {nucleodeCount: '219', decayType: ['a (97%)']},
    {nucleodeCount: '219', decayType: ['b<sup>-</sup> (3.0%)']},
    {nucleodeCount: '220', decayType: ['b<sup>-</sup> (92%)']},
    {nucleodeCount: '220', decayType: ['a (8.0%)']},
    {nucleodeCount: '221', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '222', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '223', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '224', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '225', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '226', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '227', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '228', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '229', decayType: ['b<sup>-</sup>']},
]
