const barium = [
    {nucleodeCount: '114', decayType: ['b+', 'a', 'b+, p']},
    {nucleodeCount: '115', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '116', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '117', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '118', decayType: ['b+']},
    {nucleodeCount: '119', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '119m', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b+']},
    {nucleodeCount: '121', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '122', decayType: ['b+']},
    {nucleodeCount: '123', decayType: ['b+']},
    {nucleodeCount: '123m', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b+']},
    {nucleodeCount: '125', decayType: ['b+']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b+']},
    {nucleodeCount: '127', decayType: ['b+']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['e']},
    {nucleodeCount: '129', decayType: ['b+']},
    {nucleodeCount: '129m', decayType: ['b+', 'IT']},
    {nucleodeCount: '130', decayType: ['2e']},
    {nucleodeCount: '130m', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b+']},
    {nucleodeCount: '131m', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['Stable']},
    {nucleodeCount: '133', decayType: ['e']},
    {nucleodeCount: '133m', decayType: ['IT', 'e']},
    {nucleodeCount: '134', decayType: ['Stable']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['Stable']},
    {nucleodeCount: '135m1', decayType: ['IT']},
    {nucleodeCount: '135m2', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['Stable']},
    {nucleodeCount: '136m1', decayType: ['IT']},
    {nucleodeCount: '136m2', decayType: ['IT']},
    {nucleodeCount: '137', decayType: ['Stable']},
    {nucleodeCount: '137m1', decayType: ['IT']},
    {nucleodeCount: '137m2', decayType: ['IT']},
    {nucleodeCount: '138', decayType: ['Stable']},
    {nucleodeCount: '138m', decayType: ['IT']},
    {nucleodeCount: '139', decayType: ['b-']},
    {nucleodeCount: '140', decayType: ['b-']},
    {nucleodeCount: '141', decayType: ['b-']},
    {nucleodeCount: '142', decayType: ['b-']},
    {nucleodeCount: '143', decayType: ['b-']},
    {nucleodeCount: '144', decayType: ['b-']},
    {nucleodeCount: '145', decayType: ['b-']},
    {nucleodeCount: '146', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '148', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '149', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '150', decayType: ['b-' ,'b-, n']},
    {nucleodeCount: '151', decayType: ['b-' ,'b-, n']},
    {nucleodeCount: '152', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '153', decayType: ['b-', 'b-, n' ,'b-, 2n']},
    {nucleodeCount: '154', decayType: ['b-']},
]
