const berkelium = [
    {nucleodeCount: '233', decayType: ['a', 'b+']},
    {nucleodeCount: '234', decayType: ['a', 'b+']},
    {nucleodeCount: '236', decayType: ['b+', 'a']},
    {nucleodeCount: '238', decayType: ['b+', 'a']},
    {nucleodeCount: '239', decayType: ['b+' ,'a']},
    {nucleodeCount: '240', decayType: ['b+' ,'a']},
    {nucleodeCount: '241', decayType: ['b+' ,'a']},
    {nucleodeCount: '242', decayType: ['b+', 'a']},
    {nucleodeCount: '242m', decayType: ['IT']},
    {nucleodeCount: '243', decayType: ['b+', 'a']},
    {nucleodeCount: '244', decayType: ['b+', 'a']},
    {nucleodeCount: '244m', decayType: ['IT']},
    {nucleodeCount: '245', decayType: ['e', 'a']},
    {nucleodeCount: '246', decayType: ['b+', 'a']},
    {nucleodeCount: '247', decayType: ['a']},
    {nucleodeCount: '248', decayType: ['a', 'e']},
    {nucleodeCount: '248m', decayType: ['b-', 'e', 'a']},
    {nucleodeCount: '249', decayType: ['b-', 'a']},
    {nucleodeCount: '249m', decayType: ['IT']},
    {nucleodeCount: '250', decayType: ['b-']},
    {nucleodeCount: '250m1', decayType: ['IT']},
    {nucleodeCount: '250m2', decayType: ['IT']},
    {nucleodeCount: '251', decayType: ['b-']},
    {nucleodeCount: '251m', decayType: ['IT']},
    {nucleodeCount: '252', decayType: ['b-', 'a']},
    {nucleodeCount: '253', decayType: ['b-']}
]
