const beryllium = [
    {nucleodeCount: '5', decayType: ['p']},
    {nucleodeCount: '6', decayType: ['2p']},
    {nucleodeCount: '7', decayType: ['e']},
    {nucleodeCount: '8', decayType: ['a']},
    {nucleodeCount: '8m', decayType: ['a']},
    {nucleodeCount: '9', decayType: ['Stable']},
    {nucleodeCount: '10', decayType: ['b-']},
    {nucleodeCount: '11', decayType: ['b-', 'b-, a', 'b-, p']},
    {nucleodeCount: '11m', decayType: ['IT']},
    {nucleodeCount: '12', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '12m', decayType: ['IT']},
    {nucleodeCount: '13', decayType: ['n']},
    {nucleodeCount: '14', decayType: ['b-, n']},
    {nucleodeCount: '14', decayType: ['b-']},
    {nucleodeCount: '14', decayType: ['b-, 2n']},
    {nucleodeCount: '14', decayType: ['b-, a']},
    {nucleodeCount: '15', decayType: ['n']},
    {nucleodeCount: '16', decayType: ['2n']}
]
