const beryllium = [
    {nucleodeCount: '5', decayType: ['[[proton emission', 'p]] ?<ref group="n" name="decay mode 1">Decay mode shown is energetically allowed, but has not been experimentally observed to occur in this nuclide.</ref>']},
    {nucleodeCount: '6', decayType: ['[[proton emission', '2p]]']},
    {nucleodeCount: 'None', decayType: ['[[Electron capture', 'e]]']},
    {nucleodeCount: 'None', decayType: ['{{val', '81.9', '(3.7)', 'u=as}}<br/>[{{val', '5.58', '(25)', 'u=eV}}]']},
    {nucleodeCount: 'None', decayType: ['a<ref group="n">Also often considered [[spontaneous fission]], as {{SimpleNuclide', 'Beryllium', '8}} splits into two equal {{SimpleNuclide', 'Helium', '4}} nuclei</ref>']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: '10', decayType: ['[[Beta decay', 'b<sup>-</sup>]]']},
    {nucleodeCount: '11', decayType: ['b<sup>-</sup> ({{val', '96.7', '(1)', 'u=%}})']},
    {nucleodeCount: '11', decayType: ['[[Alpha decay', 'b<sup>-</sup>a]] ({{val', '3.3', '(1)', 'u=%}})']},
    {nucleodeCount: '11', decayType: ['b<sup>-</sup>p ({{val', '0.0013', '(3)', 'u=%}})']},
    {nucleodeCount: '11', decayType: ['[[Nuclear isomer#Decay processes', 'IT]] ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '12', decayType: ['b<sup>-</sup> ({{val', '99.50', '(3)', 'u=%}})']},
    {nucleodeCount: '12', decayType: ['b<sup>-</sup>n ({{val', '0.50', '(3)', 'u=%}})']},
    {nucleodeCount: '12', decayType: ['[[Nuclear isomer#Decay processes', 'IT]]']},
    {nucleodeCount: '13', decayType: ['[[neutron emission', 'n]] ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '14', decayType: ['b<sup>-</sup>n ({{val', '86', '(6)', 'u=%}})']},
    {nucleodeCount: '14', decayType: ['b<sup>-</sup> (> {{val', '9.0', '(6.3)', 'u=%}})']},
    {nucleodeCount: '14', decayType: ['b<sup>-</sup>2n ({{val', '5', '(2)', 'u=%}})']},
    {nucleodeCount: '14', decayType: ['b<sup>-</sup>t ({{val', '0.02', '(1)', 'u=%}})']},
    {nucleodeCount: '14', decayType: ['b<sup>-</sup>a (< {{val', '0.004', 'u=%}})']},
    {nucleodeCount: '15', decayType: ['n']},
    {nucleodeCount: '16', decayType: ['2n']},
]
