const bismuth = [
    {nucleodeCount: '184', decayType: ['a']},
    {nucleodeCount: '184m', decayType: ['a']},
    {nucleodeCount: '185', decayType: ['p', 'a']},
    {nucleodeCount: '185m', decayType: ['IT']},
    {nucleodeCount: '186', decayType: ['a', 'b+']},
    {nucleodeCount: '186m', decayType: ['a', 'b+']},
    {nucleodeCount: '187', decayType: ['a']},
    {nucleodeCount: '187m1', decayType: ['a']},
    {nucleodeCount: '187m2', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['a']},
    {nucleodeCount: '188m2', decayType: ['a']},
    {nucleodeCount: '189', decayType: ['a']},
    {nucleodeCount: '189m1', decayType: ['a', 'IT']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['a', 'b+']},
    {nucleodeCount: '190m1', decayType: ['a', 'b+']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['IT']},
    {nucleodeCount: '191', decayType: ['a', 'b+']},
    {nucleodeCount: '191m1', decayType: ['a' ,'IT' ,'b+']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '191m3', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b+', 'a']},
    {nucleodeCount: '192m', decayType: ['b+', 'a']},
    {nucleodeCount: '193', decayType: ['b+', 'a']},
    {nucleodeCount: '193m1', decayType: ['a', 'b+']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '193m3', decayType: ['IT']},
    {nucleodeCount: '193m4', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b+', 'a']},
    {nucleodeCount: '194m1', decayType: ['b+']},
    {nucleodeCount: '194m2', decayType: ['b+', 'a']},
    {nucleodeCount: '195', decayType: ['b+', 'a']},
    {nucleodeCount: '195m1', decayType: ['b+', 'a']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '195m3', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b+', 'a']},
    {nucleodeCount: '196m1', decayType: ['IT']},
    {nucleodeCount: '196m2', decayType: ['b+', 'IT', 'a']},
    {nucleodeCount: '197', decayType: ['b+']},
    {nucleodeCount: '197m1', decayType: ['a', 'b+']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '197m3', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b+']},
    {nucleodeCount: '198m1', decayType: ['b+']},
    {nucleodeCount: '198m2', decayType: ['IT']},
    {nucleodeCount: '199', decayType: ['b+']},
    {nucleodeCount: '199m1', decayType: ['b+', 'IT', 'a']},
    {nucleodeCount: '199m2', decayType: ['IT']},
    {nucleodeCount: '199m3', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['b+']},
    {nucleodeCount: '200m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '200m2', decayType: ['IT']},
    {nucleodeCount: '201', decayType: ['b+']},
    {nucleodeCount: '201m1', decayType: ['b+', 'a']},
    {nucleodeCount: '201m2', decayType: ['IT']},
    {nucleodeCount: '201m3', decayType: ['IT']},
    {nucleodeCount: '201m4', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['b+', 'a']},
    {nucleodeCount: '202m1', decayType: ['IT']},
    {nucleodeCount: '202m2', decayType: ['IT']},
    {nucleodeCount: '203', decayType: ['b+']},
    {nucleodeCount: '203m1', decayType: ['IT']},
    {nucleodeCount: '203m2', decayType: ['IT']},
    {nucleodeCount: '204', decayType: ['b+']},
    {nucleodeCount: '204m1', decayType: ['IT']},
    {nucleodeCount: '204m2', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b+']},
    {nucleodeCount: '205m1', decayType: ['IT']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '205m3', decayType: ['IT']},
    {nucleodeCount: '206', decayType: ['b+']},
    {nucleodeCount: '206m1', decayType: ['IT']},
    {nucleodeCount: '206m2', decayType: ['IT']},
    {nucleodeCount: '206m3', decayType: ['IT']},
    {nucleodeCount: '206m4', decayType: ['IT']},
    {nucleodeCount: '207', decayType: ['b+']},
    {nucleodeCount: '207m', decayType: ['IT']},
    {nucleodeCount: '208', decayType: ['b+']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: '209', decayType: ['a']},
    {nucleodeCount: '210', decayType: ['b-', 'a']},
    {nucleodeCount: '210m', decayType: ['a', 'IT', 'b-']},
    {nucleodeCount: '211', decayType: ['a', 'b-']},
    {nucleodeCount: '211m', decayType: ['IT']},
    {nucleodeCount: '212', decayType: ['b-', 'a', 'b-, a']},
    {nucleodeCount: '212m1', decayType: ['a', 'b-, a', 'b-']},
    {nucleodeCount: '212m2', decayType: ['b-']},
    {nucleodeCount: '213', decayType: ['b-', 'a']},
    {nucleodeCount: '214', decayType: ['b-', 'a', 'b-, a']},
    {nucleodeCount: '215', decayType: ['b-', 'a']},
    {nucleodeCount: '215m', decayType: ['IT', 'b-']},
    {nucleodeCount: '216', decayType: ['b-']},
    {nucleodeCount: '216m', decayType: ['b-']},
    {nucleodeCount: '217', decayType: ['b-']},
    {nucleodeCount: '217m', decayType: ['IT']},
    {nucleodeCount: '218', decayType: ['b-']},
    {nucleodeCount: '219', decayType: ['b-']},
    {nucleodeCount: '220', decayType: ['b-']}
]
