const bismuth = [
    {nucleodeCount: '184', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '184m', decayType: ['a']},
    {nucleodeCount: '185', decayType: ['[[proton emission', 'p]] (92%)']},
    {nucleodeCount: '185', decayType: ['a (8%)']},
    {nucleodeCount: '185m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '186', decayType: ['a (99.99%)']},
    {nucleodeCount: '186', decayType: ['[[beta decay', 'b<sup>+</sup>]] (?%)']},
    {nucleodeCount: '186m', decayType: ['a (99.99%)']},
    {nucleodeCount: '186m', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '187', decayType: ['a']},
    {nucleodeCount: '187m1', decayType: ['a']},
    {nucleodeCount: '187m2', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['a']},
    {nucleodeCount: '188m2', decayType: ['a']},
    {nucleodeCount: '189', decayType: ['a']},
    {nucleodeCount: '189m1', decayType: ['a (83%)']},
    {nucleodeCount: '189m1', decayType: ['IT (17%)']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['a (77%)']},
    {nucleodeCount: '190', decayType: ['b<sup>+</sup> (23%)']},
    {nucleodeCount: '190m1', decayType: ['a (70%)']},
    {nucleodeCount: '190m1', decayType: ['b<sup>+</sup> (30%)']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['IT']},
    {nucleodeCount: '191', decayType: ['a (51%)']},
    {nucleodeCount: '191', decayType: ['b<sup>+</sup> (49%)']},
    {nucleodeCount: '191m1', decayType: ['a (68%)']},
    {nucleodeCount: '191m1', decayType: ['IT (?%)']},
    {nucleodeCount: '191m1', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '191m3', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '192', decayType: ['a (12%)']},
    {nucleodeCount: '192m', decayType: ['b<sup>+</sup> (90%)']},
    {nucleodeCount: '192m', decayType: ['a (10%)']},
    {nucleodeCount: '193', decayType: ['b<sup>+</sup> (96.5%)']},
    {nucleodeCount: '193', decayType: ['a (3.5%)']},
    {nucleodeCount: '193m1', decayType: ['a (84%)']},
    {nucleodeCount: '193m1', decayType: ['b<sup>+</sup> (16%)']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '193m3', decayType: ['IT']},
    {nucleodeCount: '193m4', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b<sup>+</sup> (99.54%)']},
    {nucleodeCount: '194', decayType: ['a (0.46%)']},
    {nucleodeCount: '194m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '194m2', decayType: ['b<sup>+</sup> (99.80%)']},
    {nucleodeCount: '194m2', decayType: ['a (0.20%)']},
    {nucleodeCount: '195', decayType: ['b<sup>+</sup> (99.97%)']},
    {nucleodeCount: '195', decayType: ['a (0.030%)']},
    {nucleodeCount: '195m1', decayType: ['b<sup>+</sup> (67%)']},
    {nucleodeCount: '195m1', decayType: ['a (33%)']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '195m3', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '196', decayType: ['a (0.00115%)']},
    {nucleodeCount: '196m1', decayType: ['IT']},
    {nucleodeCount: '196m2', decayType: ['b<sup>+</sup> (74.2%)']},
    {nucleodeCount: '196m2', decayType: ['IT (25.8%)']},
    {nucleodeCount: '196m2', decayType: ['a (3.8x10<sup>-4</sup>%)']},
    {nucleodeCount: '197', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '197m1', decayType: ['a (55%)']},
    {nucleodeCount: '197m1', decayType: ['b<sup>+</sup> (45%)']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '197m3', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '198m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '198m2', decayType: ['IT']},
    {nucleodeCount: '199', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '199m1', decayType: ['b<sup>+</sup> (>98%)']},
    {nucleodeCount: '199m1', decayType: ['IT (<2%)']},
    {nucleodeCount: '199m1', decayType: ['a (0.01%)']},
    {nucleodeCount: '199m2', decayType: ['IT']},
    {nucleodeCount: '199m3', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '200m1', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '200m1', decayType: ['IT (?%)']},
    {nucleodeCount: '200m2', decayType: ['IT']},
    {nucleodeCount: '201', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '201m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '201m1', decayType: ['a (?%)']},
    {nucleodeCount: '201m2', decayType: ['IT']},
    {nucleodeCount: '201m3', decayType: ['IT']},
    {nucleodeCount: '201m4', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '202', decayType: ['a (<10<sup>-5</sup>%)']},
    {nucleodeCount: '202m1', decayType: ['IT']},
    {nucleodeCount: '202m2', decayType: ['IT']},
    {nucleodeCount: '203', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '203m1', decayType: ['IT']},
    {nucleodeCount: '203m2', decayType: ['IT']},
    {nucleodeCount: '204', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '204m1', decayType: ['IT']},
    {nucleodeCount: '204m2', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '205m1', decayType: ['IT']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '205m3', decayType: ['IT']},
    {nucleodeCount: '206', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '206m1', decayType: ['IT']},
    {nucleodeCount: '206m2', decayType: ['IT']},
    {nucleodeCount: '206m3', decayType: ['IT']},
    {nucleodeCount: '206m4', decayType: ['IT']},
    {nucleodeCount: '207', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '207m', decayType: ['IT']},
    {nucleodeCount: '208', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: '210', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '210', decayType: ['rowspan=2', '1-']},
    {nucleodeCount: '210', decayType: ['a (1.32x10<sup>-4</sup>%)']},
    {nucleodeCount: '210m', decayType: ['3.04(6)x10<sup>6</sup>&nbsp;y']},
    {nucleodeCount: '210m', decayType: ['a{{refn', 'group=n', 'Theoretically capable of [[isomeric transition]] to <sup>210</sup>Bi with a partial half-life of ~5.5x10<sup>20</sup> years or b<sup>-</sup> decay to <sup>210</sup>Po with a partial half-life over 10<sup>13</sup> years.<ref>{{cite thesis', 'last=Tuggle', 'first=D. G.', 'title=Decay studies of a long lived high spin isomer of <sup>210</sup>Bi', 'date=August 1976', 'url=https://inis.iaea.org/records/qnf50-y0t48', 'location=California Univ., Berkeley (USA)', 'publisher=Lawrence Berkeley Lab}} See the section "<sup>210m</sup>Bi Decay to <sup>210</sup>Po".</ref>}}']},
    {nucleodeCount: '211', decayType: ['a (99.72%)']},
    {nucleodeCount: '211', decayType: ['rowspan=2', '9/2-']},
    {nucleodeCount: '211', decayType: ['b<sup>-</sup> (0.276%)']},
    {nucleodeCount: '211m', decayType: ['IT']},
    {nucleodeCount: '212', decayType: ['b<sup>-</sup> (64.05%)']},
    {nucleodeCount: '212', decayType: ['rowspan=3', '1-']},
    {nucleodeCount: '212', decayType: ['a (35.94%)']},
    {nucleodeCount: '212', decayType: ['b<sup>-</sup>, a (0.014%)']},
    {nucleodeCount: '212m1', decayType: ['a (67%)']},
    {nucleodeCount: '212m1', decayType: ['b<sup>-</sup>, a (30%)']},
    {nucleodeCount: '212m1', decayType: ['b<sup>-</sup> (3%)']},
    {nucleodeCount: '212m2', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: 'None', decayType: ['b<sup>-</sup> (97.91%)']},
    {nucleodeCount: 'None', decayType: ['rowspan=2', '9/2-']},
    {nucleodeCount: 'None', decayType: ['a (2.09%)']},
    {nucleodeCount: '214', decayType: ['b<sup>-</sup> (99.98%)']},
    {nucleodeCount: '214', decayType: ['a (0.021%)']},
    {nucleodeCount: '214', decayType: ['b<sup>-</sup>, a (0.003%)']},
    {nucleodeCount: '215', decayType: ['7.62(13)&nbsp;min']},
    {nucleodeCount: '215', decayType: ['b<sup>-</sup>{{refn', 'group=n', 'Theoretically capable of a decay to <sup>211</sup>Tl; the branching ratio is expected to be ~8x10<sup>-5</sup>% (partial half-life ~18.1 y).<ref>{{cite web', 'url=https://www.nndc.bnl.gov/ensnds/215/Bi/adopted.pdf', 'title=Adopted Levels for <sup>215</sup>Bi', 'publisher=NNDC Chart of Nuclides}}</ref>}}']},
    {nucleodeCount: '215m', decayType: ['IT (76.9%)']},
    {nucleodeCount: '215m', decayType: ['b<sup>-</sup> (23.1%)']},
    {nucleodeCount: '216', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '216m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '217', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '217m', decayType: ['IT']},
    {nucleodeCount: '218', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '219', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '220', decayType: ['b<sup>-</sup>']},
]
