const bromine = [
    {nucleodeCount: '68', decayType: ['p?']},
    {nucleodeCount: '69', decayType: ['p']},
    {nucleodeCount: '70', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '70', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '70m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '70m', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '71', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '72', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '72m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '73', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '74', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '74m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '75', decayType: ['b<sup>+</sup> (76%)<ref name="lambert1994"/>']},
    {nucleodeCount: '75', decayType: ['[[Electron capture', 'EC]] (24%)']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup> (57%)<ref name="lambert1994"/>']},
    {nucleodeCount: '76', decayType: ['EC (43%)']},
    {nucleodeCount: '76m', decayType: ['IT (>99.4%)']},
    {nucleodeCount: '76m', decayType: ['b<sup>+</sup> (<0.6%)']},
    {nucleodeCount: '77', decayType: ['EC (99.3%)<ref name="kassis1982">{{cite journal', 'last1=Kassis', 'first1=A. I.', 'last2=Adelstein', 'first2=S. J.', 'last3=Haydock', 'first3=C.', 'last4=Sastry', 'first4=K. S. R.', 'last5=McElvany', 'first5=K. D.', 'last6=Welch', 'first6=M. J.', 'title=Lethality of Auger Electrons from the Decay of Bromine-77 in the DNA of Mammalian Cells', 'journal=Radiation Research', 'date=May 1982', 'volume=90', 'issue=2', 'pages=362', 'doi=10.2307/3575714', 'jstor=3575714', 'bibcode=1982RadR...90..362K', 'url=https://www.jstor.org/stable/pdf/3575714.pdf', 'issn=0033-7587}}</ref>']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup> (0.7%)']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '78', decayType: ['b<sup>+</sup> (>99.99%)']},
    {nucleodeCount: '78', decayType: ['b<sup>-</sup> (<0.01%)']},
    {nucleodeCount: '78m', decayType: ['IT']},
    {nucleodeCount: '79m', decayType: ['IT']},
    {nucleodeCount: '80', decayType: ['b<sup>-</sup> (91.7%)']},
    {nucleodeCount: '80', decayType: ['b<sup>+</sup> (8.3%)']},
    {nucleodeCount: '80m', decayType: ['IT']},
    {nucleodeCount: '81m', decayType: ['IT']},
    {nucleodeCount: '82', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '82m', decayType: ['IT (97.6%)']},
    {nucleodeCount: '82m', decayType: ['b<sup>-</sup> (2.4%)']},
    {nucleodeCount: '83', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '84m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '84m2', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup> (97.40%)']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (2.60%)']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup> (93.42%)']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup>, n (6.58%)']},
    {nucleodeCount: '88m', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup> (86.2%)']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup>, n (13.8%)']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup> (74.7%)']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>, n (25.3%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup> (70.5%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>, n (29.5%)']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup> (66.9%)']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>, n (33.1%)']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '92m1', decayType: ['IT']},
    {nucleodeCount: '92m2', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>, n (64%)']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup> (36%)']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>, n (68%)']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup> (32%)']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, 2n?']},
]
