const bromine = [
    {nucleodeCount: '68', decayType: ['p']},
    {nucleodeCount: '69', decayType: ['p']},
    {nucleodeCount: '70', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '70m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '71', decayType: ['b+']},
    {nucleodeCount: '72', decayType: ['b+']},
    {nucleodeCount: '72m', decayType: ['IT', 'b+']},
    {nucleodeCount: '73', decayType: ['b+']},
    {nucleodeCount: '74', decayType: ['b+']},
    {nucleodeCount: '74m', decayType: ['b+']},
    {nucleodeCount: '75', decayType: ['b+', 'e']},
    {nucleodeCount: '76', decayType: ['b+', 'e']},
    {nucleodeCount: '76m', decayType: ['IT', 'b+']},
    {nucleodeCount: '77', decayType: ['e', 'b+']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '78', decayType: ['b+', 'b-']},
    {nucleodeCount: '78m', decayType: ['IT']},
    {nucleodeCount: '79', decayType: ['Stable']},
    {nucleodeCount: '79m', decayType: ['IT']},
    {nucleodeCount: '80', decayType: ['b-', 'b+']},
    {nucleodeCount: '80m', decayType: ['IT']},
    {nucleodeCount: '81', decayType: ['Stable']},
    {nucleodeCount: '81m', decayType: ['IT']},
    {nucleodeCount: '82', decayType: ['b-']},
    {nucleodeCount: '82m', decayType: ['IT', 'b-']},
    {nucleodeCount: '83', decayType: ['b-']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b-']},
    {nucleodeCount: '84m1', decayType: ['b-']},
    {nucleodeCount: '84m2', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b-']},
    {nucleodeCount: '86', decayType: ['b-']},
    {nucleodeCount: '87', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '88', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '88m', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '90', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '91', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '92', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '92m1', decayType: ['IT']},
    {nucleodeCount: '92m2', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '94', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '98', decayType: ['b-', 'b-, n', 'b-, 2n']}
]
