const cadmium = [
    {nucleodeCount: '95', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '96', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '96m1', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '97m1', decayType: ['IT']},
    {nucleodeCount: '97m2', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '98', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '98m1', decayType: ['IT']},
    {nucleodeCount: '98m2', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '100', decayType: ['b+']},
    {nucleodeCount: '101', decayType: ['b+']},
    {nucleodeCount: '102', decayType: ['b+']},
    {nucleodeCount: '103', decayType: ['b+']},
    {nucleodeCount: '104', decayType: ['b+']},
    {nucleodeCount: '105', decayType: ['b+']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '106', decayType: ['Stable']},
    {nucleodeCount: '107', decayType: ['b+']},
    {nucleodeCount: '108', decayType: ['Stable']},
    {nucleodeCount: '109', decayType: ['e']},
    {nucleodeCount: '109m1', decayType: ['IT']},
    {nucleodeCount: '109m2', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['Stable']},
    {nucleodeCount: '111', decayType: ['Stable']},
    {nucleodeCount: '111m', decayType: ['IT']},
    {nucleodeCount: '112', decayType: ['Stable']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '113m', decayType: ['b-', 'IT']},
    {nucleodeCount: '114', decayType: ['Stable']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['b-']},
    {nucleodeCount: '116', decayType: ['b-b-']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['b-']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119m', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '121m', decayType: ['b-']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '123m', decayType: ['b-', 'IT']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125m1', decayType: ['b-']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127m1', decayType: ['b-']},
    {nucleodeCount: '127m2', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b-']},
    {nucleodeCount: '128m1', decayType: ['IT']},
    {nucleodeCount: '128m2', decayType: ['IT']},
    {nucleodeCount: '128m2', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '129m1', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '129m2', decayType: ['IT']},
    {nucleodeCount: '130', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '130m', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '132', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '133', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '134', decayType: ['b-']}
]