const caesium = [
    {nucleodeCount: '112', decayType: ['p', 'a']},
    {nucleodeCount: '113', decayType: ['p']},
    {nucleodeCount: '114', decayType: ['b+', 'b+, p', 'b+, a', 'a']},
    {nucleodeCount: '115', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '116', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '116m', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '117', decayType: ['b+']},
    {nucleodeCount: '117m', decayType: ['b+']},
    {nucleodeCount: '118', decayType: ['b+', 'b+, p' ,'b+, a']},
    {nucleodeCount: '118m1', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '118m3', decayType: ['IT']},
    {nucleodeCount: '118m4', decayType: ['IT']},
    {nucleodeCount: '118m5', decayType: ['IT']},
    {nucleodeCount: '119', decayType: ['b+', 'b+, a']},
    {nucleodeCount: '119m', decayType: ['b+']},
    {nucleodeCount: '120', decayType: ['b+', 'b+, a', 'b+, p']},
    {nucleodeCount: '120m', decayType: ['b+','b+, a', 'b+, p']},
    {nucleodeCount: '121', decayType: ['b+']},
    {nucleodeCount: '121m', decayType: ['b+', 'IT']},
    {nucleodeCount: '122', decayType: ['b+', 'b+, a']},
    {nucleodeCount: '122m1', decayType: ['IT']},
    {nucleodeCount: '122m2', decayType: ['b+']},
    {nucleodeCount: '122m3', decayType: ['IT']},
    {nucleodeCount: '123', decayType: ['b+']},
    {nucleodeCount: '123m1', decayType: ['IT']},
    {nucleodeCount: '123m2', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b+']},
    {nucleodeCount: '124m', decayType: ['IT', 'b+']},
    {nucleodeCount: '125', decayType: ['b+']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b+']},
    {nucleodeCount: '126m1', decayType: ['IT']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b+']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b+']},
    {nucleodeCount: '129', decayType: ['b+']},
    {nucleodeCount: '129m', decayType: ['IT']},
    {nucleodeCount: '130', decayType: ['b+', 'b-']},
    {nucleodeCount: '130m', decayType: ['IT', 'b+']},
    {nucleodeCount: '131', decayType: ['e']},
    {nucleodeCount: '132', decayType: ['b+', 'b-']},
    {nucleodeCount: '133', decayType: ['Stable']},
    {nucleodeCount: '134', decayType: ['b-', 'e']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b-']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['b-']},
    {nucleodeCount: '136m', decayType: ['b-', 'IT']},
    {nucleodeCount: '137', decayType: ['b-']},
    {nucleodeCount: '138', decayType: ['b-']},
    {nucleodeCount: '138m', decayType: ['IT', 'b-']},
    {nucleodeCount: '139', decayType: ['b-']},
    {nucleodeCount: '140', decayType: ['b-']},
    {nucleodeCount: '140m', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '142', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '143', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '144', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '144m', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '145m', decayType: ['IT']},
    {nucleodeCount: '146', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '146m', decayType: ['IT']},
    {nucleodeCount: '147', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '150', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '151', decayType: ['b-']}
]