const calcium = [
    {nucleodeCount: '35', decayType: ['b+, p', 'b+, 2p', 'b+ ']},
    {nucleodeCount: '36', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '37', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '38', decayType: ['b+']},
    {nucleodeCount: '39', decayType: ['b+']},
    {nucleodeCount: '40', decayType: ['Stable']},
    {nucleodeCount: '41', decayType: ['e']},
    {nucleodeCount: '42', decayType: ['Stable']},
    {nucleodeCount: '43', decayType: ['Stable']},
    {nucleodeCount: '44', decayType: ['Stable']},
    {nucleodeCount: '45', decayType: ['b-']},
    {nucleodeCount: '46', decayType: ['Stable']},
    {nucleodeCount: '47', decayType: ['b-']},
    {nucleodeCount: '48', decayType: ['2b-']},
    {nucleodeCount: '49', decayType: ['b-']},
    {nucleodeCount: '50', decayType: ['b-']},
    {nucleodeCount: '51', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '52', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '53', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '54', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '55', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '56', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '57', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '58', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '59', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '60', decayType: ['b-', 'b-, n', 'b-, 2n']}
]
