const californium = [
    {nucleodeCount: '237', decayType: ['a', 'b+ ']},
    {nucleodeCount: '238', decayType: ['a']},
    {nucleodeCount: '239', decayType: ['a', 'b+']},
    {nucleodeCount: '240', decayType: ['a', 'b+']},
    {nucleodeCount: '241', decayType: ['b+', 'a']},
    {nucleodeCount: '242', decayType: ['a', 'b+']},
    {nucleodeCount: '243', decayType: ['b+', 'a']},
    {nucleodeCount: '244', decayType: ['a', 'e']},
    {nucleodeCount: '245', decayType: ['b+', 'a']},
    {nucleodeCount: '245m', decayType: ['IT']},
    {nucleodeCount: '246', decayType: ['a', 'e']},
    {nucleodeCount: '247', decayType: ['e', 'a']},
    {nucleodeCount: '248', decayType: ['a']},
    {nucleodeCount: '249', decayType: ['a']},
    {nucleodeCount: '249m', decayType: ['IT']},
    {nucleodeCount: '250', decayType: ['a']},
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '251m', decayType: ['IT']},
    {nucleodeCount: '252', decayType: ['a']},
    {nucleodeCount: '253', decayType: ['b-', 'a']},
    {nucleodeCount: '254', decayType: ['a', '2b-']},
    {nucleodeCount: '255', decayType: ['b-', 'a']},
    {nucleodeCount: '256', decayType: ['a', '2b-']}
]