const californium = [
    {nucleodeCount: '237', decayType: ['[[alpha decay', 'a]] (70%)']},
    {nucleodeCount: '237', decayType: ['[[beta decay', 'b{{sup', '+}}]] (rare)']},
    {nucleodeCount: '238', decayType: ['a (<5%)']},
    {nucleodeCount: '239', decayType: ['a (65%)']},
    {nucleodeCount: '239', decayType: ['[[Beta decay', 'b{{sup', '+}}]] (35%)']},
    {nucleodeCount: '240', decayType: ['a (98.5%)']},
    {nucleodeCount: '240', decayType: ['b{{sup', '+}}?']},
    {nucleodeCount: '241', decayType: ['b{{sup', '+}} (85%)']},
    {nucleodeCount: '241', decayType: ['a (15%)']},
    {nucleodeCount: '242', decayType: ['a (61%)']},
    {nucleodeCount: '242', decayType: ['b{{sup', '+}} (39%)']},
    {nucleodeCount: '243', decayType: ['b{{sup', '+}} (86%)']},
    {nucleodeCount: '243', decayType: ['a (14%)']},
    {nucleodeCount: '244', decayType: ['a (75%)']},
    {nucleodeCount: '244', decayType: ['[[Electron capture', 'EC]] (25%)']},
    {nucleodeCount: '245', decayType: ['b{{sup', '+}} (64.7%)']},
    {nucleodeCount: '245', decayType: ['a (35.3%)']},
    {nucleodeCount: '245m', decayType: ['IT']},
    {nucleodeCount: '246', decayType: ['a']},
    {nucleodeCount: '246', decayType: ['EC?']},
    {nucleodeCount: '247', decayType: ['EC (99.965%)']},
    {nucleodeCount: '247', decayType: ['a (.035%)']},
    {nucleodeCount: '248', decayType: ['a (99.997%)']},
    {nucleodeCount: '249', decayType: ['a']},
    {nucleodeCount: '249m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '250', decayType: ['a (99.923%)']},
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '251m', decayType: ['IT']},
    {nucleodeCount: '252', decayType: ['a (96.8972%)']},
    {nucleodeCount: '253', decayType: ['b{{sup', '-}} (99.69%)']},
    {nucleodeCount: '253', decayType: ['a (.31%)']},
    {nucleodeCount: '254', decayType: ['a (.31%)']},
    {nucleodeCount: '254', decayType: ['[[Double beta decay', 'b{{sup', '-}}b{{sup', '-}}]]?']},
    {nucleodeCount: '255', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '255', decayType: ['a?']},
    {nucleodeCount: '256', decayType: ['a?']},
    {nucleodeCount: '256', decayType: ['b{{sup', '-}}b{{sup', '-}}?']},
]
