const carbon = [
    {nucleodeCount: '8', decayType: ['2p']},
    {nucleodeCount: '9', decayType: ['b+', 'b+a', 'b+p']},
    {nucleodeCount: '10', decayType: ['b+']},
    {nucleodeCount: '11', decayType: ['b+']},
    {nucleodeCount: '11m', decayType: ['p']},
    {nucleodeCount: '12', decayType: ['Stable']},
    {nucleodeCount: '13', decayType: ['Stable']},
    {nucleodeCount: '14', decayType: ['b-']},
    {nucleodeCount: '14m', decayType: ['IT']},
    {nucleodeCount: '15', decayType: ['b-']},
    {nucleodeCount: '16', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '17', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '18', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '19', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '20', decayType: ['b-, n', 'b-, 2n', 'b-']},
    {nucleodeCount: '21', decayType: ['n']},
    {nucleodeCount: '22', decayType: ['b-, n' ,'b-, 2n', 'b-']},
    {nucleodeCount: '23', decayType: ['n']}
]