const cerium = [
    {nucleodeCount: '121', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '122', decayType: ['b+']},
    {nucleodeCount: '123', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '124', decayType: ['b+']},
    {nucleodeCount: '125', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b+']},
    {nucleodeCount: '127', decayType: ['b+']},
    {nucleodeCount: '127m1', decayType: ['b+']},
    {nucleodeCount: '127m2', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b+']},
    {nucleodeCount: '129', decayType: ['b+']},
    {nucleodeCount: '130', decayType: ['b+']},
    {nucleodeCount: '130m', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b+']},
    {nucleodeCount: '131m', decayType: ['b+']},
    {nucleodeCount: '132', decayType: ['b+']},
    {nucleodeCount: '132m', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b+']},
    {nucleodeCount: '133m', decayType: ['b+']},
    {nucleodeCount: '134', decayType: ['e']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b+']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['Stable']},
    {nucleodeCount: '136m', decayType: ['IT']},
    {nucleodeCount: '137', decayType: ['b+']},
    {nucleodeCount: '137m', decayType: ['IT', 'b+']},
    {nucleodeCount: '138', decayType: ['Stable']},
    {nucleodeCount: '138m', decayType: ['IT']},
    {nucleodeCount: '139', decayType: ['e']},
    {nucleodeCount: '139m', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['Stable']},
    {nucleodeCount: '140m', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['b-']},
    {nucleodeCount: '142', decayType: ['Stable']},
    {nucleodeCount: '143', decayType: ['b-']},
    {nucleodeCount: '144', decayType: ['b-']},
    {nucleodeCount: '145', decayType: ['b-']},
    {nucleodeCount: '146', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-']},
    {nucleodeCount: '148', decayType: ['b-']},
    {nucleodeCount: '149', decayType: ['b-']},
    {nucleodeCount: '150', decayType: ['b-']},
    {nucleodeCount: '151', decayType: ['b-']},
    {nucleodeCount: '152', decayType: ['b-']},
    {nucleodeCount: '153', decayType: ['b-']},
    {nucleodeCount: '154', decayType: ['b-']},
    {nucleodeCount: '155', decayType: ['b-']},
    {nucleodeCount: '156', decayType: ['b-']},
    {nucleodeCount: '157', decayType: ['b-']},
    {nucleodeCount: '158', decayType: ['b-']}
]