const chlorine = [
    {nucleodeCount: '28', decayType: ['p']},
    {nucleodeCount: '29', decayType: ['p']},
    {nucleodeCount: '30', decayType: ['p']},
    {nucleodeCount: '31', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '32', decayType: ['b+', 'b+, a', 'b+, p']},
    {nucleodeCount: '33', decayType: ['b+']},
    {nucleodeCount: '34', decayType: ['b+']},
    {nucleodeCount: '34m', decayType: ['b+', 'IT']},
    {nucleodeCount: '35', decayType: ['Stable']},
    {nucleodeCount: '36', decayType: ['b-', 'b+']},
    {nucleodeCount: '37', decayType: ['Stable']},
    {nucleodeCount: '38', decayType: ['b-']},
    {nucleodeCount: '38m', decayType: ['IT']},
    {nucleodeCount: '39', decayType: ['b-']},
    {nucleodeCount: '40', decayType: ['b-']},
    {nucleodeCount: '41', decayType: ['b-']},
    {nucleodeCount: '42', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '43', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '44', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '45', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '46', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '47', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '48', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '49', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '50', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '51', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '52', decayType: ['b-', 'b-, n', 'b-, 2n']}
]