const cobalt = [
    {nucleodeCount: '50', decayType: ['b{{sup', '+}}, p (70.5%)']},
    {nucleodeCount: '50', decayType: ['b{{sup', '+}} (29.5%)']},
    {nucleodeCount: '50', decayType: ['b{{sup', '+}}, 2p?']},
    {nucleodeCount: '51', decayType: ['b{{sup', '+}} (96.2%)']},
    {nucleodeCount: '51', decayType: ['b{{sup', '+}}, p (<3.8%)']},
    {nucleodeCount: '52', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '52', decayType: ['b{{sup', '+}}, p?']},
    {nucleodeCount: '52m', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '52m', decayType: ['[[Isomeric transition', 'IT]]?']},
    {nucleodeCount: '52m', decayType: ['b{{sup', '+}}, p?']},
    {nucleodeCount: '53', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '53m', decayType: ['b{{sup', '+}}? (~98.5%)']},
    {nucleodeCount: '53m', decayType: ['p (~1.5%)']},
    {nucleodeCount: '54', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '54m', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '55', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '56', decayType: ['b{{sup', '+}}']},
    {nucleodeCount: '57', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '58', decayType: ['EC (85.21%)']},
    {nucleodeCount: '58', decayType: ['b{{sup', '+}} (14.79%)']},
    {nucleodeCount: '58m1', decayType: ['IT']},
    {nucleodeCount: '58m1', decayType: ['EC (0.00120%)']},
    {nucleodeCount: '58m2', decayType: ['IT']},
    {nucleodeCount: '60', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '60m', decayType: ['IT (99.75%)']},
    {nucleodeCount: '60m', decayType: ['b{{sup', '-}} (0.25%)']},
    {nucleodeCount: '61', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '62', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '62m', decayType: ['b{{sup', '-}} (>99.5%)']},
    {nucleodeCount: '62m', decayType: ['IT (<0.5%)']},
    {nucleodeCount: '63', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '64', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '64m', decayType: ['b{{sup', '-}}?']},
    {nucleodeCount: '64m', decayType: ['IT?']},
    {nucleodeCount: '65', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '66', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '66', decayType: ['b{{sup', '-}}, [[neutron emission', 'n]]?']},
    {nucleodeCount: '66m1', decayType: ['IT']},
    {nucleodeCount: '66m2', decayType: ['IT']},
    {nucleodeCount: '67', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '67', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '67m', decayType: ['IT (>80%)']},
    {nucleodeCount: '67m', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '68', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '68', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '68m1', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '68m1', decayType: ['b{{sup', '-}}, n (>2.6%)']},
    {nucleodeCount: '68m2', decayType: ['IT']},
    {nucleodeCount: '69', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '69', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '69m', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '70', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '70', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '70', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '70m', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '70m', decayType: ['IT?']},
    {nucleodeCount: '70m', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '70m', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '71', decayType: ['b{{sup', '-}} (97%)']},
    {nucleodeCount: '71', decayType: ['b{{sup', '-}}, n (3%)']},
    {nucleodeCount: '72', decayType: ['b{{sup', '-}} (<96%)']},
    {nucleodeCount: '72', decayType: ['b{{sup', '-}}, n (>4%)']},
    {nucleodeCount: '72', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '72m', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '73', decayType: ['b{{sup', '-}} (94%)']},
    {nucleodeCount: '73', decayType: ['b{{sup', '-}}, n (6%)']},
    {nucleodeCount: '73', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '74', decayType: ['b{{sup', '-}} (82%)']},
    {nucleodeCount: '74', decayType: ['b{{sup', '-}}, n (18%)']},
    {nucleodeCount: '74', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '75', decayType: ['b{{sup', '-}} (>84%)']},
    {nucleodeCount: '75', decayType: ['b{{sup', '-}}, n (<16%)']},
    {nucleodeCount: '75', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '76', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '76', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '76', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '76m1', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '76m2', decayType: ['IT']},
    {nucleodeCount: '77', decayType: ['b{{sup', '-}}']},
    {nucleodeCount: '77', decayType: ['b{{sup', '-}}, n?']},
    {nucleodeCount: '77', decayType: ['b{{sup', '-}}, 2n?']},
    {nucleodeCount: '77', decayType: ['b{{sup', '-}}, 3n?']},
    {nucleodeCount: '78', decayType: ['b{{sup', '-}}?']},
]
