const cobalt = [
    {nucleodeCount: '50', decayType: ['b+, p', 'b+', 'b+, 2p']},
    {nucleodeCount: '51', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '52', decayType: ['b+','b+, p']},
    {nucleodeCount: '52m', decayType: ['b+', 'IT', 'b+, p']},
    {nucleodeCount: '53', decayType: ['b+']},
    {nucleodeCount: '53m', decayType: ['b+', 'p']},
    {nucleodeCount: '54', decayType: ['b+']},
    {nucleodeCount: '54m', decayType: ['b+']},
    {nucleodeCount: '55', decayType: ['b+']},
    {nucleodeCount: '56', decayType: ['b+']},
    {nucleodeCount: '57', decayType: ['e']},
    {nucleodeCount: '58', decayType: ['e', 'b+']},
    {nucleodeCount: '58m1', decayType: ['IT', 'e']},
    {nucleodeCount: '58m2', decayType: ['IT']},
    {nucleodeCount: '59', decayType: ['Stable']},
    {nucleodeCount: '60', decayType: ['b-']},
    {nucleodeCount: '60m', decayType: ['IT', 'b-']},
    {nucleodeCount: '61', decayType: ['b-']},
    {nucleodeCount: '62', decayType: ['b-']},
    {nucleodeCount: '62m', decayType: ['b-', 'IT']},
    {nucleodeCount: '63', decayType: ['b-']},
    {nucleodeCount: '64', decayType: ['b-']},
    {nucleodeCount: '64m', decayType: ['b-', 'IT']},
    {nucleodeCount: '65', decayType: ['b-']},
    {nucleodeCount: '66', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '66m1', decayType: ['IT']},
    {nucleodeCount: '66m2', decayType: ['IT']},
    {nucleodeCount: '67', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '67m', decayType: ['IT', 'b-']},
    {nucleodeCount: '68', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '68m1', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '68m2', decayType: ['IT']},
    {nucleodeCount: '69', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '69m', decayType: ['b-']},
    {nucleodeCount: '70', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '70m', decayType: ['b-', 'IT', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '71', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '72', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '72m', decayType: ['b-']},
    {nucleodeCount: '73', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '74', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '75', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '76', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '76m1', decayType: ['b-']},
    {nucleodeCount: '76m2', decayType: ['IT']},
    {nucleodeCount: '77', decayType: ['b-', 'b-, n', 'b-, 2n', 'b-, 3n']},
    {nucleodeCount: '78', decayType: ['b-']}
]