const copper = [
    {nucleodeCount: '55', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '55', decayType: ['b<sup>+</sup>, [[Proton emission', 'p]] (?%)']},
    {nucleodeCount: '56', decayType: ['b<sup>+</sup> (99.60%)']},
    {nucleodeCount: '56', decayType: ['b<sup>+</sup>, p (0.40%)']},
    {nucleodeCount: '57', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '58', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '59', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '60', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '61', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '62', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '64', decayType: ['b<sup>+</sup> (61.52%)']},
    {nucleodeCount: '64', decayType: ['b<sup>-</sup> (38.48%)']},
    {nucleodeCount: '66', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '66m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '67', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '68', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '68m', decayType: ['IT (86%)']},
    {nucleodeCount: '68m', decayType: ['b<sup>-</sup> (14%)']},
    {nucleodeCount: '69', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '69m', decayType: ['IT']},
    {nucleodeCount: '70', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '70m1', decayType: ['b<sup>-</sup> (52%)']},
    {nucleodeCount: '70m1', decayType: ['IT (48%)']},
    {nucleodeCount: '70m2', decayType: ['b<sup>-</sup> (93.2%)']},
    {nucleodeCount: '70m2', decayType: ['IT (6.8%)']},
    {nucleodeCount: '71', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '71m', decayType: ['IT']},
    {nucleodeCount: '72', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73', decayType: ['b<sup>-</sup> (99.71%)']},
    {nucleodeCount: '73', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (0.29%)']},
    {nucleodeCount: '74', decayType: ['b<sup>-</sup> (99.93%)']},
    {nucleodeCount: '74', decayType: ['b<sup>-</sup>, n (0.075%)']},
    {nucleodeCount: '75', decayType: ['b<sup>-</sup> (97.3%)']},
    {nucleodeCount: '75', decayType: ['b<sup>-</sup>, n (2.7%)']},
    {nucleodeCount: '75m1', decayType: ['IT']},
    {nucleodeCount: '75m2', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['b<sup>-</sup> (?%)']},
    {nucleodeCount: '76', decayType: ['b<sup>-</sup>, n (?%)']},
    {nucleodeCount: '76m', decayType: ['b<sup>-</sup> (?%)']},
    {nucleodeCount: '76m', decayType: ['b<sup>-</sup>, n (?%)']},
    {nucleodeCount: '76m', decayType: ['IT (10–17%)']},
    {nucleodeCount: '77', decayType: ['b<sup>-</sup> (69.9%)']},
    {nucleodeCount: '77', decayType: ['b<sup>-</sup>, n (30.1%)']},
    {nucleodeCount: '78', decayType: ['b<sup>-</sup>, n (50.6%)']},
    {nucleodeCount: '78', decayType: ['b<sup>-</sup> (49.4%)']},
    {nucleodeCount: '79', decayType: ['b<sup>-</sup>, n (66%)']},
    {nucleodeCount: '79', decayType: ['b<sup>-</sup> (34%)']},
    {nucleodeCount: '80', decayType: ['b<sup>-</sup>, n (59%)']},
    {nucleodeCount: '80', decayType: ['b<sup>-</sup> (41%)']},
    {nucleodeCount: '81', decayType: ['b<sup>-</sup>, n (81%)']},
    {nucleodeCount: '81', decayType: ['b<sup>-</sup> (19%)']},
    {nucleodeCount: '82', decayType: ['b<sup>-</sup>']},
]
