const copper = [
    {nucleodeCount: '55', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '56', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '57', decayType: ['b+']},
    {nucleodeCount: '58', decayType: ['b+']},
    {nucleodeCount: '59', decayType: ['b+']},
    {nucleodeCount: '60', decayType: ['b+']},
    {nucleodeCount: '61', decayType: ['b+']},
    {nucleodeCount: '62', decayType: ['b+']},
    {nucleodeCount: '63', decayType: ['Stable']},
    {nucleodeCount: '64', decayType: ['b+', 'b-']},
    {nucleodeCount: '65', decayType: ['Stable']},
    {nucleodeCount: '66', decayType: ['b-']},
    {nucleodeCount: '66m', decayType: ['IT']},
    {nucleodeCount: '67', decayType: ['b-']},
    {nucleodeCount: '68', decayType: ['b-']},
    {nucleodeCount: '68m', decayType: ['IT', 'b-']},
    {nucleodeCount: '69', decayType: ['b-']},
    {nucleodeCount: '69m', decayType: ['IT']},
    {nucleodeCount: '70', decayType: ['b-']},
    {nucleodeCount: '70m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '70m2', decayType: ['b-', 'IT']},
    {nucleodeCount: '71', decayType: ['b-']},
    {nucleodeCount: '71m', decayType: ['IT']},
    {nucleodeCount: '72', decayType: ['b-']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '74', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '75', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '75m1', decayType: ['IT']},
    {nucleodeCount: '75m2', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '76m', decayType: ['b-', 'b-, n', 'IT']},
    {nucleodeCount: '77', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '78', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '79', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '80', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '81', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '82', decayType: ['b-']}
]