const curium = [
    {nucleodeCount: '233', decayType: ['b+', 'a']},
    {nucleodeCount: '234', decayType: ['b+', 'a']},
    {nucleodeCount: '235', decayType: ['b+', 'a']},
    {nucleodeCount: '236', decayType: ['b+', 'a']},
    {nucleodeCount: '237', decayType: ['a']},
    {nucleodeCount: '238', decayType: ['e', 'a']},
    {nucleodeCount: '239', decayType: ['b+', 'a']},
    {nucleodeCount: '240', decayType: ['a']},
    {nucleodeCount: '241', decayType: ['e', 'a']},
    {nucleodeCount: '242', decayType: ['a', '2b+']},
    {nucleodeCount: '243', decayType: ['a', 'e']},
    {nucleodeCount: '243m', decayType: ['IT']},
    {nucleodeCount: '244', decayType: ['a']},
    {nucleodeCount: '244m1', decayType: ['IT']},
    {nucleodeCount: '245', decayType: ['a']},
    {nucleodeCount: '245m', decayType: ['IT']},
    {nucleodeCount: '246', decayType: ['a']},
    {nucleodeCount: '246m', decayType: ['IT']},
    {nucleodeCount: '247', decayType: ['a']},
    {nucleodeCount: '247m1', decayType: ['IT']},
    {nucleodeCount: '247m2', decayType: ['IT']},
    {nucleodeCount: '248', decayType: ['a', '2b-']},
    {nucleodeCount: '248m', decayType: ['IT']},
    {nucleodeCount: '249', decayType: ['b-']},
    {nucleodeCount: '249m', decayType: ['a']},
    {nucleodeCount: '250', decayType: ['a', 'b-']},
    {nucleodeCount: '251', decayType: ['b-']}
]