const dubnium = [
    {nucleodeCount: '255', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['b+']},
    {nucleodeCount: '257', decayType: ['a']},
    {nucleodeCount: '257', decayType: ['b+']},
    {nucleodeCount: '257m', decayType: ['a']},
    {nucleodeCount: '257m', decayType: ['b+']},
    {nucleodeCount: '258', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['b+']},
    {nucleodeCount: '258m', decayType: ['a']},
    {nucleodeCount: '258m', decayType: ['b+']},
    {nucleodeCount: '259', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['b+']},
    {nucleodeCount: '260m', decayType: ['a']},
    {nucleodeCount: '261', decayType: ['a']},
    {nucleodeCount: '262', decayType: ['a']},
    {nucleodeCount: '263', decayType: ['a (~)']},
    {nucleodeCount: '263', decayType: ['b+ (~)<ref group="n">Heaviest nuclide known to undergo b+ decay</ref>']},
    {nucleodeCount: 'None', decayType: ['EC']},
    {nucleodeCount: 'None', decayType: ['website=nscl.msu.edu', 'access-date=29 June 2023}}</ref>']},
    {nucleodeCount: 'None', decayType: ['a<ref name=Mc2022/>']},
    {nucleodeCount: 'None', decayType: ['EC']},
    {nucleodeCount: 'None', decayType: ['a (~)']},
    {nucleodeCount: 'None', decayType: ['EC<ref name="270Db-Stock">{{Cite book', 'url=https://books.google.com/booksid=zVrdAAAAQBAJ&q=isotope+29Rf&pg=PT305', 'title=Encyclopedia of Nuclear Physics and its Applications', 'isbn=9783527649266', 'last1=Stock', 'first1=Reinhard', 'date=2013-09-13', 'publisher=John Wiley & Sons}}</ref>']},
]
