const dysprosium = [
    {nucleodeCount: '139', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '140', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '140m', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '142', decayType: ['b+', 'e', 'b+, p']},
    {nucleodeCount: '143', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '143m1', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '143m2', decayType: ['IT']},
    {nucleodeCount: '144', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '145', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '145m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '146', decayType: ['b+']},
    {nucleodeCount: '146m', decayType: ['IT']},
    {nucleodeCount: '147', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '147m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '147m2', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['b+']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b+']},
    {nucleodeCount: '149m', decayType: ['IT', 'b+']},
    {nucleodeCount: '150', decayType: ['b+', 'a']},
    {nucleodeCount: '151', decayType: ['b+', 'a']},
    {nucleodeCount: '152', decayType: ['e', 'a']},
    {nucleodeCount: '153', decayType: ['b+', 'a']},
    {nucleodeCount: '154', decayType: ['a', '2b+']},
    {nucleodeCount: '155', decayType: ['b+']},
    {nucleodeCount: '155m', decayType: ['IT']},
    {nucleodeCount: '156', decayType: ['Stable']},
    {nucleodeCount: '157', decayType: ['b+']},
    {nucleodeCount: '157m1', decayType: ['IT']},
    {nucleodeCount: '157m2', decayType: ['IT']},
    {nucleodeCount: '158', decayType: ['Stable']},
    {nucleodeCount: '159', decayType: ['e']},
    {nucleodeCount: '159m', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['Stable']},
    {nucleodeCount: '161', decayType: ['Stable']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['Stable']},
    {nucleodeCount: '162m', decayType: ['IT']},
    {nucleodeCount: '163', decayType: ['Stable']},
    {nucleodeCount: '164', decayType: ['Stable']},
    {nucleodeCount: '165', decayType: ['b-']},
    {nucleodeCount: '165m', decayType: ['IT', 'b-']},
    {nucleodeCount: '166', decayType: ['b-']},
    {nucleodeCount: '167', decayType: ['b-']},
    {nucleodeCount: '168', decayType: ['b-']},
    {nucleodeCount: '168m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b-']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['b-']},
    {nucleodeCount: '170m', decayType: ['IT']},
    {nucleodeCount: '171', decayType: ['b-']},
    {nucleodeCount: '172', decayType: ['b-']},
    {nucleodeCount: '172m', decayType: ['IT', 'b-']},
    {nucleodeCount: '173', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '174', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '175', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '176', decayType: ['b-', 'b-, n']}
]