const einsteinium = [
    {nucleodeCount: '240', decayType: ['a', 'b+']},
    {nucleodeCount: '241', decayType: ['a', 'b+']},
    {nucleodeCount: '242', decayType: ['b+', 'a']},
    {nucleodeCount: '243', decayType: ['a', 'b+']},
    {nucleodeCount: '244', decayType: ['b+', 'a']},
    {nucleodeCount: '245', decayType: ['b+', 'a']},
    {nucleodeCount: '245m', decayType: ['IT', 'a', 'b+']},
    {nucleodeCount: '246', decayType: ['b+', 'a']},
    {nucleodeCount: '247', decayType: ['b+', 'a']},
    {nucleodeCount: '248', decayType: ['b+', 'a']},
    {nucleodeCount: '249', decayType: ['b+', 'a']},
    {nucleodeCount: '250', decayType: ['b+', 'a']},
    {nucleodeCount: '250m', decayType: ['b+', 'a']},
    {nucleodeCount: '251', decayType: ['e', 'a']},
    {nucleodeCount: '252', decayType: ['a', 'e']},
    {nucleodeCount: '253', decayType: ['a']},
    {nucleodeCount: '254', decayType: ['a', 'e', 'b-']},
    {nucleodeCount: '254m', decayType: ['b-', 'IT', 'a', 'e']},
    {nucleodeCount: '255', decayType: ['b-', 'a']},
    {nucleodeCount: '256', decayType: ['b-']},
    {nucleodeCount: '256m', decayType: ['b-']},
    {nucleodeCount: '257', decayType: ['b-', 'a']}
]