const einsteinium = [
    {nucleodeCount: '240', decayType: ['[[alpha decay', 'a]] (70%)']},
    {nucleodeCount: '240', decayType: ['[[beta decay', 'b<sup>+</sup>]] (30%)']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '242', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '242', decayType: ['a (41%)']},
    {nucleodeCount: '243', decayType: ['a (61%)']},
    {nucleodeCount: '243', decayType: ['b<sup>+</sup> (39%)']},
    {nucleodeCount: '244', decayType: ['b<sup>+</sup> (95%)']},
    {nucleodeCount: '244', decayType: ['a (5%)']},
    {nucleodeCount: '245', decayType: ['b<sup>+</sup> (51%)']},
    {nucleodeCount: '245', decayType: ['a (49%)']},
    {nucleodeCount: '245m', decayType: ['[[Isomeric transition', 'IT]]?']},
    {nucleodeCount: '245m', decayType: ['a?']},
    {nucleodeCount: '245m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '246', decayType: ['b<sup>+</sup> (90.1%)']},
    {nucleodeCount: '246', decayType: ['a (9.9%)']},
    {nucleodeCount: '247', decayType: ['b<sup>+</sup> (93%)']},
    {nucleodeCount: '247', decayType: ['a (7%)']},
    {nucleodeCount: '248', decayType: ['b<sup>+</sup> (99.75%)']},
    {nucleodeCount: '248', decayType: ['a (.25%)']},
    {nucleodeCount: '249', decayType: ['b<sup>+</sup> (99.43%)']},
    {nucleodeCount: '249', decayType: ['a (.57%)']},
    {nucleodeCount: '250', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '250', decayType: ['a?']},
    {nucleodeCount: '250m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '250m', decayType: ['a?']},
    {nucleodeCount: '251', decayType: ['[[Electron capture', 'EC]] (99.5%)']},
    {nucleodeCount: '251', decayType: ['a (.5%)']},
    {nucleodeCount: '252', decayType: ['a (78(2)%)']},
    {nucleodeCount: '252', decayType: ['EC (22(2)%)']},
    {nucleodeCount: '253', decayType: ['a']},
    {nucleodeCount: '254', decayType: ['rowspan=3', '275.7(5)&nbsp;d']},
    {nucleodeCount: '254', decayType: ['a{{r', 'g=n', 'EC254', 'r=Theoretically capable of electron capture to <sup>254</sup>Cf{{NUBASE2020', 'ref}}}}']},
    {nucleodeCount: '254', decayType: ['b<sup>-</sup> (1.74x10<sup>-4</sup>%)']},
    {nucleodeCount: '254m', decayType: ['b<sup>-</sup> (98(2)%)']},
    {nucleodeCount: '254m', decayType: ['IT (<3%)']},
    {nucleodeCount: '254m', decayType: ['a (0.32(1)%)']},
    {nucleodeCount: '254m', decayType: ['EC (0.076(7)%)']},
    {nucleodeCount: '255', decayType: ['b<sup>-</sup> (92.0%)']},
    {nucleodeCount: '255', decayType: ['a (8.0%)']},
    {nucleodeCount: '256', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '256m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '257', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '257', decayType: ['a?']},
]
