const einsteinium = [
    {nucleodeCount: '240', decayType: ['a']},
    {nucleodeCount: '240', decayType: ['b+']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['b+']},
    {nucleodeCount: '242', decayType: ['b+']},
    {nucleodeCount: '242', decayType: ['a']},
    {nucleodeCount: '243', decayType: ['a']},
    {nucleodeCount: '243', decayType: ['b+']},
    {nucleodeCount: '244', decayType: ['b+']},
    {nucleodeCount: '244', decayType: ['a']},
    {nucleodeCount: '245', decayType: ['b+']},
    {nucleodeCount: '245', decayType: ['a']},
    {nucleodeCount: '245m', decayType: ['IT']},
    {nucleodeCount: '245m', decayType: ['a']},
    {nucleodeCount: '245m', decayType: ['b+']},
    {nucleodeCount: '246', decayType: ['b+']},
    {nucleodeCount: '246', decayType: ['a']},
    {nucleodeCount: '247', decayType: ['b+']},
    {nucleodeCount: '247', decayType: ['a']},
    {nucleodeCount: '248', decayType: ['b+']},
    {nucleodeCount: '248', decayType: ['a']},
    {nucleodeCount: '249', decayType: ['b+']},
    {nucleodeCount: '249', decayType: ['a']},
    {nucleodeCount: '250', decayType: ['b+']},
    {nucleodeCount: '250', decayType: ['a']},
    {nucleodeCount: '250m', decayType: ['b+']},
    {nucleodeCount: '250m', decayType: ['a']},
    {nucleodeCount: '251', decayType: ['EC']},
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '252', decayType: ['a (78(2))']},
    {nucleodeCount: '252', decayType: ['EC (22(2))']},
    {nucleodeCount: '253', decayType: ['a']},
    {nucleodeCount: '254', decayType: ['rowspan=3', '275.7(5)&nbsp;d']},
    {nucleodeCount: '254', decayType: ['a{{r', 'g=n', 'EC254', 'r=Theoretically capable of electron capture to <sup>254</sup>Cf{{NUBASE2020', 'ref}}}}']},
    {nucleodeCount: '254', decayType: ['b- (1.74x10<sup>-4</sup)']},
    {nucleodeCount: '254m', decayType: ['b- (98(2))']},
    {nucleodeCount: '254m', decayType: ['IT']},
    {nucleodeCount: '254m', decayType: ['a (0.32(1))']},
    {nucleodeCount: '254m', decayType: ['EC (0.076(7))']},
    {nucleodeCount: '255', decayType: ['b-']},
    {nucleodeCount: '255', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['b-']},
    {nucleodeCount: '256m', decayType: ['b-']},
    {nucleodeCount: '257', decayType: ['b-']},
    {nucleodeCount: '257', decayType: ['a']},
]
