const erbium = [
    {nucleodeCount: '145', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '145', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (?%)']},
    {nucleodeCount: '145m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '145m', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '146', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '147', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '147', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '147m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '147m', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '148', decayType: ['b<sup>+</sup> (99.85%)']},
    {nucleodeCount: '148', decayType: ['b<sup>+</sup>, p (0.15%)']},
    {nucleodeCount: '148m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup> (93%)']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup>, p (7%)']},
    {nucleodeCount: '149m1', decayType: ['b<sup>+</sup> (96.3%)']},
    {nucleodeCount: '149m1', decayType: ['IT (3.5%)']},
    {nucleodeCount: '149m1', decayType: ['b<sup>+</sup>, p (0.18%)']},
    {nucleodeCount: '149m2', decayType: ['IT']},
    {nucleodeCount: '149m3', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150m', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '151m1', decayType: ['IT (95.3%)']},
    {nucleodeCount: '151m1', decayType: ['b<sup>+</sup> (4.7%)']},
    {nucleodeCount: '151m2', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['[[alpha decay', 'a]] (90%)']},
    {nucleodeCount: '152', decayType: ['b<sup>+</sup> (10%)']},
    {nucleodeCount: '153', decayType: ['a (53%)']},
    {nucleodeCount: '153', decayType: ['b<sup>+</sup> (47%)']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b<sup>+</sup> (99.53%)']},
    {nucleodeCount: '154', decayType: ['a (0.47%)']},
    {nucleodeCount: '155', decayType: ['b<sup>+</sup> (99.978%)']},
    {nucleodeCount: '155', decayType: ['a (0.022%)']},
    {nucleodeCount: '156', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '156', decayType: ['a (1.2{{e', '-5}}%)']},
    {nucleodeCount: '157', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '157m', decayType: ['IT']},
    {nucleodeCount: '158', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '159', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '159m1', decayType: ['IT']},
    {nucleodeCount: '159m2', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['EC']},
    {nucleodeCount: '161', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['161.9287873(8)']},
    {nucleodeCount: '162m', decayType: ['IT']},
    {nucleodeCount: '163', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['163.9292077(8)']},
    {nucleodeCount: '165', decayType: ['EC']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['165.9303011(4)']},
    {nucleodeCount: '167', decayType: ['166.9320562(3)']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['167.93237828(28)']},
    {nucleodeCount: '168m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '169m1', decayType: ['IT']},
    {nucleodeCount: '169m2', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['169.9354719(15)']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '171m', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '174', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '174m', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b<sup>-</sup>']},
]
