const erbium = [
    {nucleodeCount: '145', decayType: ['b+']},
    {nucleodeCount: '145', decayType: ['b+, p']},
    {nucleodeCount: '145m', decayType: ['b+']},
    {nucleodeCount: '145m', decayType: ['b+, p']},
    {nucleodeCount: '146', decayType: ['b+']},
    {nucleodeCount: '146', decayType: ['b+, p']},
    {nucleodeCount: '147', decayType: ['b+']},
    {nucleodeCount: '147', decayType: ['b+, p']},
    {nucleodeCount: '147m', decayType: ['b+']},
    {nucleodeCount: '147m', decayType: ['b+, p']},
    {nucleodeCount: '148', decayType: ['b+']},
    {nucleodeCount: '148', decayType: ['b+, p']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b+']},
    {nucleodeCount: '149', decayType: ['b+, p']},
    {nucleodeCount: '149m1', decayType: ['b+']},
    {nucleodeCount: '149m1', decayType: ['IT']},
    {nucleodeCount: '149m1', decayType: ['b+, p']},
    {nucleodeCount: '149m2', decayType: ['IT']},
    {nucleodeCount: '149m3', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b+']},
    {nucleodeCount: '150m', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['b+']},
    {nucleodeCount: '151m1', decayType: ['IT']},
    {nucleodeCount: '151m1', decayType: ['b+']},
    {nucleodeCount: '151m2', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['a']},
    {nucleodeCount: '152', decayType: ['b+']},
    {nucleodeCount: '153', decayType: ['a']},
    {nucleodeCount: '153', decayType: ['b+']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b+']},
    {nucleodeCount: '154', decayType: ['a']},
    {nucleodeCount: '155', decayType: ['b+']},
    {nucleodeCount: '155', decayType: ['a']},
    {nucleodeCount: '156', decayType: ['b+']},
    {nucleodeCount: '156', decayType: ['a (1.2{{e', '-5}})']},
    {nucleodeCount: '157', decayType: ['b+']},
    {nucleodeCount: '157m', decayType: ['IT']},
    {nucleodeCount: '158', decayType: ['EC']},
    {nucleodeCount: '159', decayType: ['b+']},
    {nucleodeCount: '159m1', decayType: ['IT']},
    {nucleodeCount: '159m2', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['EC']},
    {nucleodeCount: '161', decayType: ['b+']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['161.9287873(8)']},
    {nucleodeCount: '162m', decayType: ['IT']},
    {nucleodeCount: '163', decayType: ['b+']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['163.9292077(8)']},
    {nucleodeCount: '165', decayType: ['EC']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['165.9303011(4)']},
    {nucleodeCount: '167', decayType: ['166.9320562(3)']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['167.93237828(28)']},
    {nucleodeCount: '168m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b-']},
    {nucleodeCount: '169m1', decayType: ['IT']},
    {nucleodeCount: '169m2', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['169.9354719(15)']},
    {nucleodeCount: '171', decayType: ['b-']},
    {nucleodeCount: '171m', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['b-']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['b-']},
    {nucleodeCount: '174', decayType: ['b-']},
    {nucleodeCount: '174m', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b-']},
]
