const erbium = [
    {nucleodeCount: '145', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '145m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '146', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '147', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '147m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '148', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '149m1', decayType: ['b+', 'IT', 'b+, p']},
    {nucleodeCount: '149m2', decayType: ['IT']},
    {nucleodeCount: '149m3', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b+']},
    {nucleodeCount: '150m', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['b+']},
    {nucleodeCount: '151m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '151m2', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['a', 'b+']},
    {nucleodeCount: '153', decayType: ['a', 'b+']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b+', 'a']},
    {nucleodeCount: '155', decayType: ['b+', 'a']},
    {nucleodeCount: '156', decayType: ['b+', 'a']},
    {nucleodeCount: '157', decayType: ['b+']},
    {nucleodeCount: '157m', decayType: ['IT']},
    {nucleodeCount: '158', decayType: ['e']},
    {nucleodeCount: '159', decayType: ['b+']},
    {nucleodeCount: '159m1', decayType: ['IT']},
    {nucleodeCount: '159m2', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['e']},
    {nucleodeCount: '161', decayType: ['b+']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['Stable']},
    {nucleodeCount: '162m', decayType: ['IT']},
    {nucleodeCount: '163', decayType: ['b+']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['Stable']},
    {nucleodeCount: '165', decayType: ['e']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['Stable']},
    {nucleodeCount: '167', decayType: ['Stable']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['Stable']},
    {nucleodeCount: '168m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b-']},
    {nucleodeCount: '169m1', decayType: ['IT']},
    {nucleodeCount: '169m2', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['Stable']},
    {nucleodeCount: '171', decayType: ['b-']},
    {nucleodeCount: '171m', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['b-']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['b-']},
    {nucleodeCount: '174', decayType: ['b-']},
    {nucleodeCount: '174m', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b-']}
]