const europium = [
    {nucleodeCount: '130', decayType: ['p']},
    {nucleodeCount: '131', decayType: ['p', 'b+', 'b+, p']},
    {nucleodeCount: '134', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '135', decayType: ['b+']},
    {nucleodeCount: '136', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '136m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '137', decayType: ['b+']},
    {nucleodeCount: '138m', decayType: ['b+']},
    {nucleodeCount: '139', decayType: ['b+']},
    {nucleodeCount: '139m', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['b+']},
    {nucleodeCount: '140', decayType: ['e']},
    {nucleodeCount: '140m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '140m2', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['b+']},
    {nucleodeCount: '141m', decayType: ['IT', 'b+']},
    {nucleodeCount: '142', decayType: ['b+', 'EC']},
    {nucleodeCount: '142m', decayType: ['b+']},
    {nucleodeCount: '143', decayType: ['b+']},
    {nucleodeCount: '143m', decayType: ['IT']},
    {nucleodeCount: '144', decayType: ['b+']},
    {nucleodeCount: '144m', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b+']},
    {nucleodeCount: '145m', decayType: ['IT']},
    {nucleodeCount: '146', decayType: ['b+']},
    {nucleodeCount: '146m', decayType: ['IT']},
    {nucleodeCount: '147', decayType: ['b+', 'a']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['b+', 'a']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['e']},
    {nucleodeCount: '149m', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b+']},
    {nucleodeCount: '150m', decayType: ['b-', 'b+', 'IT']},
    {nucleodeCount: '150', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['a']},
    {nucleodeCount: '151m', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['b+', 'b-']},
    {nucleodeCount: '152m1', decayType: ['b-', 'b+']},
    {nucleodeCount: '152m2', decayType: ['IT']},
    {nucleodeCount: '152m3', decayType: ['IT']},
    {nucleodeCount: '152m4', decayType: ['IT']},
    {nucleodeCount: '152m5', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['Stable']},
    {nucleodeCount: '153m', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b-', 'e']},
    {nucleodeCount: '154m1', decayType: ['IT']},
    {nucleodeCount: '154m2', decayType: ['IT']},
    {nucleodeCount: '155', decayType: ['b-']},
    {nucleodeCount: '156', decayType: ['b-']},
    {nucleodeCount: '157', decayType: ['b-']},
    {nucleodeCount: '158', decayType: ['b-']},
    {nucleodeCount: '159', decayType: ['b-']},
    {nucleodeCount: '160', decayType: ['b-']},
    {nucleodeCount: '160m', decayType: ['IT']},
    {nucleodeCount: '161', decayType: ['b-']},
    {nucleodeCount: '162', decayType: ['b-']},
    {nucleodeCount: '162m', decayType: ['IT']},
    {nucleodeCount: '163', decayType: ['b-']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['b-']},
    {nucleodeCount: '165', decayType: ['b-']},
    {nucleodeCount: '166', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '167', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '168', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '169', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '170', decayType: ['b-', 'b-, n']}
]