const fermium = [
    {nucleodeCount: '241', decayType: ['a', 'b+']},
    {nucleodeCount: '242', decayType: ['a']},
    {nucleodeCount: '243', decayType: ['a', 'b+']},
    {nucleodeCount: '244', decayType: ['b+', 'a']},
    {nucleodeCount: '245', decayType: ['a', 'b+']},
    {nucleodeCount: '246', decayType: ['a', 'e']},
    {nucleodeCount: '247', decayType: ['a', 'b+']},
    {nucleodeCount: '247m', decayType: ['a', 'IT', 'b+']},
    {nucleodeCount: '248', decayType: ['a', 'b+']},
    {nucleodeCount: '248m', decayType: ['IT', 'a', 'b+']},
    {nucleodeCount: '249', decayType: ['b+', 'a']},
    {nucleodeCount: '250', decayType: ['a', 'e']},
    {nucleodeCount: '250m', decayType: ['IT', 'a', 'b+']},
    {nucleodeCount: '251', decayType: ['b+', 'a']},
    {nucleodeCount: '251m', decayType: ['IT']},
    {nucleodeCount: '252', decayType: ['a', '2b+']},
    {nucleodeCount: '253', decayType: ['e', 'a']},
    {nucleodeCount: '253m', decayType: ['IT']},
    {nucleodeCount: '254', decayType: ['a']},
    {nucleodeCount: '255', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['a']},
    {nucleodeCount: '257', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['a']}
]