const fluorine = [
    {nucleodeCount: '13', decayType: ['p']},
    {nucleodeCount: '14', decayType: ['p']},
    {nucleodeCount: '15', decayType: ['p']},
    {nucleodeCount: '16', decayType: ['p']},
    {nucleodeCount: '17', decayType: ['b+']},
    {nucleodeCount: '18', decayType: ['b+']},
    {nucleodeCount: '18m', decayType: ['IT']},
    {nucleodeCount: '19', decayType: ['Stable']},
    {nucleodeCount: '20', decayType: ['b-']},
    {nucleodeCount: '21', decayType: ['b-']},
    {nucleodeCount: '22', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '23', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '24', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '25', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '26', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '26m', decayType: ['IT', 'b-, n', 'b-']},
    {nucleodeCount: '27', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '28', decayType: ['n']},
    {nucleodeCount: '29', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '30', decayType: ['n']},
    {nucleodeCount: '31', decayType: ['b-', 'b-, n', 'b-, 2n']}
]