const francium = [
    {nucleodeCount: '197', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '198', decayType: ['a']},
    {nucleodeCount: '199', decayType: ['a']},
    {nucleodeCount: '200', decayType: ['a']},
    {nucleodeCount: '200m', decayType: ['a']},
    {nucleodeCount: '201', decayType: ['a (99%)']},
    {nucleodeCount: '201', decayType: ['b<sup>+</sup> (1%)']},
    {nucleodeCount: '202', decayType: ['a (97%)']},
    {nucleodeCount: '202', decayType: ['b<sup>+</sup> (3%)']},
    {nucleodeCount: '202m', decayType: ['a (97%)']},
    {nucleodeCount: '202m', decayType: ['b<sup>+</sup> (3%)']},
    {nucleodeCount: '203', decayType: ['a (95%)']},
    {nucleodeCount: '203', decayType: ['b<sup>+</sup> (5%)']},
    {nucleodeCount: '204', decayType: ['a (96%)']},
    {nucleodeCount: '204', decayType: ['b<sup>+</sup> (4%)']},
    {nucleodeCount: '204m1', decayType: ['a (90%)']},
    {nucleodeCount: '204m1', decayType: ['b<sup>+</sup> (10%)']},
    {nucleodeCount: '205', decayType: ['a (99%)']},
    {nucleodeCount: '205', decayType: ['b<sup>+</sup> (1%)']},
    {nucleodeCount: '206', decayType: ['b<sup>+</sup> (58%)']},
    {nucleodeCount: '206', decayType: ['a (42%)']},
    {nucleodeCount: '207', decayType: ['a (95%)']},
    {nucleodeCount: '207', decayType: ['b<sup>+</sup> (5%)']},
    {nucleodeCount: '208', decayType: ['a (90%)']},
    {nucleodeCount: '208', decayType: ['b<sup>+</sup> (10%)']},
    {nucleodeCount: '209', decayType: ['a (89%)']},
    {nucleodeCount: '209', decayType: ['b<sup>+</sup> (11%)']},
    {nucleodeCount: '210', decayType: ['a (60%)']},
    {nucleodeCount: '210', decayType: ['b<sup>+</sup> (40%)']},
    {nucleodeCount: '211', decayType: ['a (80%)']},
    {nucleodeCount: '211', decayType: ['b<sup>+</sup> (20%)']},
    {nucleodeCount: '212', decayType: ['b<sup>+</sup> (57%)']},
    {nucleodeCount: '212', decayType: ['a (43%)']},
    {nucleodeCount: '213', decayType: ['rowspan=2', '212.996184(5)']},
    {nucleodeCount: '213', decayType: ['a (99.45%)']},
    {nucleodeCount: '213', decayType: ['b<sup>+</sup> (.55%)']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214m1', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m', decayType: ['850(30)&nbsp;ns']},
    {nucleodeCount: '216m', decayType: ['a{{refn', 'group=n', 'Theoretically capable of b<sup>+</sup> decay to <sup>216</sup>Rn{{NUBASE2020', 'ref}}}}']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m1', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a (99.65%)']},
    {nucleodeCount: '220', decayType: ['b<sup>-</sup> (.35%)']},
    {nucleodeCount: '221', decayType: ['a (99.9%)']},
    {nucleodeCount: '221', decayType: ['rowspan=3', '5/2-']},
    {nucleodeCount: '221', decayType: ['b<sup>-</sup> (.1%)']},
    {nucleodeCount: '221', decayType: ['[[Cluster decay', 'CD]] (8.79x10<sup>-11</sup>%)<ref group="n">The nuclide with the lowest [[atomic number]] known to undergo [[cluster decay]]</ref>']},
    {nucleodeCount: '222', decayType: ['14.2(3)&nbsp;min']},
    {nucleodeCount: '222', decayType: ['b<sup>-</sup>{{refn', 'group=n', 'Theoretically capable of a decay to <sup>218</sup>At with a partial half-life of ~1 d (branching ratio ~1%).<ref>{{Citation', 'last1=Hyde', 'first1=E. K.', 'last2=Ghiorso', 'first2=A.', 'title=Preparation of a New Isotope of Francium - Fr<sup>222</sup>', 'date=4 February 1950', 'url=https://escholarship.org/uc/item/6xx699r2', 'location=California Univ., Berkeley (USA)', 'publisher=Radiation Laboratory}}</ref>}}']},
    {nucleodeCount: '223', decayType: ['b<sup>-</sup> (99.99%)']},
    {nucleodeCount: '223', decayType: ['rowspan=2', '3/2(-)']},
    {nucleodeCount: '223', decayType: ['a (.006%)']},
    {nucleodeCount: '224', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '225', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '226', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '227', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '228', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '229', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '230', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '231', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '232', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '233', decayType: ['b<sup>-</sup>']},
]
