const francium = [
    {nucleodeCount: '197', decayType: ['a']},
    {nucleodeCount: '198', decayType: ['a']},
    {nucleodeCount: '199', decayType: ['a']},
    {nucleodeCount: '200', decayType: ['a']},
    {nucleodeCount: '200m', decayType: ['a']},
    {nucleodeCount: '201', decayType: ['a', 'b+']},
    {nucleodeCount: '202', decayType: ['a', 'b+']},
    {nucleodeCount: '202m', decayType: ['a', 'b+']},
    {nucleodeCount: '203', decayType: ['a', 'b+']},
    {nucleodeCount: '204', decayType: ['a', 'b+']},
    {nucleodeCount: '204m1', decayType: ['a', 'b+']},
    {nucleodeCount: '205', decayType: ['a', 'b+']},
    {nucleodeCount: '206', decayType: ['b+', 'a']},
    {nucleodeCount: '207', decayType: ['a', 'b+']},
    {nucleodeCount: '208', decayType: ['a', 'b+']},
    {nucleodeCount: '209', decayType: ['a', 'b+']},
    {nucleodeCount: '210', decayType: ['a', 'b+']},
    {nucleodeCount: '211', decayType: ['a', 'b+']},
    {nucleodeCount: '212', decayType: ['b+', 'a']},
    {nucleodeCount: '213', decayType: ['a', 'b+']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214m1', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m', decayType: ['a', 'b+']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m1', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a', 'b-']},
    {nucleodeCount: '221', decayType: ['a', 'b-']},
    {nucleodeCount: '222', decayType: ['b-', 'a']},
    {nucleodeCount: '223', decayType: ['b-', 'a']},
    {nucleodeCount: '224', decayType: ['b-']},
    {nucleodeCount: '225', decayType: ['b-']},
    {nucleodeCount: '226', decayType: ['b-']},
    {nucleodeCount: '227', decayType: ['b-']},
    {nucleodeCount: '228', decayType: ['b-']},
    {nucleodeCount: '229', decayType: ['b-']},
    {nucleodeCount: '230', decayType: ['b-']},
    {nucleodeCount: '231', decayType: ['b-']},
    {nucleodeCount: '232', decayType: ['b-']},
    {nucleodeCount: '233', decayType: ['b-']}
]