const gadolinium = [
    {nucleodeCount: '135', decayType: ['[[beta decay', 'b<sup>+</sup>]] (98%)']},
    {nucleodeCount: '135', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (98%)']},
    {nucleodeCount: '136', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '136', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '137', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '137', decayType: ['b<sup>+</sup>, [[proton emission', 'p]]?']},
    {nucleodeCount: '138', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '138m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '139', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '139m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139m', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '140', decayType: ['b<sup>+</sup> (67(8)%)']},
    {nucleodeCount: '141', decayType: ['b<sup>+</sup> (99.97%)']},
    {nucleodeCount: '141', decayType: ['b<sup>+</sup>, p (0.03%)']},
    {nucleodeCount: '141m', decayType: ['b<sup>+</sup> (89%)']},
    {nucleodeCount: '141m', decayType: ['[[Isomeric transition', 'IT]] (11%)']},
    {nucleodeCount: '142', decayType: ['EC (52(5)%)']},
    {nucleodeCount: '143', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '143', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '143', decayType: ['b<sup>+</sup>, [[alpha decay', 'a]]?']},
    {nucleodeCount: '143m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '143m', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '143m', decayType: ['b<sup>+</sup>, [[alpha decay', 'a]]?']},
    {nucleodeCount: '144', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '144m', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '145m', decayType: ['IT (94.3%)']},
    {nucleodeCount: '145m', decayType: ['b<sup>+</sup> (5.7%)']},
    {nucleodeCount: '146', decayType: ['EC']},
    {nucleodeCount: '147', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['86.9(39)&nbsp;y<ref name="148Gd"/>']},
    {nucleodeCount: '148', decayType: ['a<ref group="n">Theorized to also undergo b<sup>+</sup>b<sup>+</sup> decay to \'\'\'\'\'<sup>148</sup>Sm\'\'\'\'\'</ref>']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '149', decayType: ['a (4.3x10<sup>-4</sup>%)']},
    {nucleodeCount: '150', decayType: ['1.79(8)x10<sup>6</sup>&nbsp;y']},
    {nucleodeCount: '150', decayType: ['a<ref group="n">Theorized to also undergo b<sup>+</sup>b<sup>+</sup> decay to \'\'\'<sup>150</sup>Sm\'\'\'</ref>']},
    {nucleodeCount: '151', decayType: ['EC']},
    {nucleodeCount: '151', decayType: ['a (1.1x10<sup>-6</sup>%)']},
    {nucleodeCount: '152', decayType: ["'''1.08(8)x10<sup>14</sup>&nbsp;y'''"]},
    {nucleodeCount: '152', decayType: ['a<ref group="n">Theorized to also undergo b<sup>+</sup>b<sup>+</sup> decay to \'\'\'<sup>152</sup>Sm\'\'\'</ref>']},
    {nucleodeCount: '153', decayType: ['EC']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['153.9208730(11)']},
    {nucleodeCount: '155', decayType: ['154.9226294(11)']},
    {nucleodeCount: '155m', decayType: ['IT']},
    {nucleodeCount: '156m', decayType: ['IT']},
    {nucleodeCount: '157m1', decayType: ['IT']},
    {nucleodeCount: '157m2', decayType: ['IT']},
    {nucleodeCount: '159', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '161', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '162', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '163', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '163m', decayType: ['IT?']},
    {nucleodeCount: '163m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '164', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '164m', decayType: ['IT']},
    {nucleodeCount: '165', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166m', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '168', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '169', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '169', decayType: ['b<sup>-</sup>, n? (<0.7%)<ref name=Ln922>{{cite journal', 'last1=Kiss', 'first1=G. G.', 'last2=Vitéz-Sveiczer', 'first2=A.', 'last3=Saito', 'first3=Y.', 'display-authors=et al.', 'title=Measuring the b-decay properties of neutron-rich exotic Pm, Sm, Eu, and Gd isotopes to constrain the nucleosynthesis yields in the rare-earth region', 'journal=The Astrophysical Journal', 'volume=936', 'issue=107', 'date=2022', 'page=107', 'doi=10.3847/1538-4357/ac80fc', 'bibcode=2022ApJ...936..107K', 'doi-access=free', 'hdl=2117/375253', 'hdl-access=free }}</ref><!--only half-lives updated on 2022-11-29-->']},
    {nucleodeCount: '170', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '170', decayType: ['b<sup>-</sup>, n? (<3%)<ref name=Ln922/>']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>, n? (<10%)<ref name=Ln922/>']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>, n? (<50%)<ref name=Ln922/>']},
]
