const gadolinium = [
    {nucleodeCount: '135', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '136', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '137', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '138', decayType: ['b+']},
    {nucleodeCount: '138m', decayType: ['IT']},
    {nucleodeCount: '139', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '139m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '140', decayType: ['b+', 'e']},
    {nucleodeCount: '141', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '141m', decayType: ['b+', 'IT']},
    {nucleodeCount: '142', decayType: ['e', 'b+']},
    {nucleodeCount: '143', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '143m', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '144', decayType: ['b+']},
    {nucleodeCount: '144m', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b+']},
    {nucleodeCount: '145m', decayType: ['IT', 'b+']},
    {nucleodeCount: '146', decayType: ['e']},
    {nucleodeCount: '147', decayType: ['b+']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['a']},
    {nucleodeCount: '149', decayType: ['b+', 'a']},
    {nucleodeCount: '150', decayType: ['a', '2b+']},
    {nucleodeCount: '151', decayType: ['e', 'a']},
    {nucleodeCount: '152', decayType: ['a']},
    {nucleodeCount: '153', decayType: ['e']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['Stable']},
    {nucleodeCount: '155', decayType: ['Stable']},
    {nucleodeCount: '155m', decayType: ['IT']},
    {nucleodeCount: '156', decayType: ['Stable']},
    {nucleodeCount: '156m', decayType: ['IT']},
    {nucleodeCount: '157', decayType: ['Stable']},
    {nucleodeCount: '157m1', decayType: ['IT']},
    {nucleodeCount: '157m2', decayType: ['IT']},
    {nucleodeCount: '158', decayType: ['Stable']},
    {nucleodeCount: '159', decayType: ['b-']},
    {nucleodeCount: '160', decayType: ['Stable']},
    {nucleodeCount: '161', decayType: ['b-']},
    {nucleodeCount: '162', decayType: ['b-']},
    {nucleodeCount: '163', decayType: ['b-']},
    {nucleodeCount: '163m', decayType: ['IT', 'b-']},
    {nucleodeCount: '164', decayType: ['b-']},
    {nucleodeCount: '164m', decayType: ['IT']},
    {nucleodeCount: '165', decayType: ['b-']},
    {nucleodeCount: '166', decayType: ['b-']},
    {nucleodeCount: '166m', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['b-']},
    {nucleodeCount: '168', decayType: ['b-']},
    {nucleodeCount: '169', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '170', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '171', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '172', decayType: ['b-', 'b-, n']}
]