const gallium = [
    {nucleodeCount: '60', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '61', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '62', decayType: ['b+']},
    {nucleodeCount: '63', decayType: ['b+']},
    {nucleodeCount: '64', decayType: ['b+']},
    {nucleodeCount: '64m', decayType: ['IT']},
    {nucleodeCount: '65', decayType: ['b+']},
    {nucleodeCount: '66', decayType: ['b+']},
    {nucleodeCount: '67', decayType: ['e']},
    {nucleodeCount: '68', decayType: ['b+']},
    {nucleodeCount: '69', decayType: ['Stable']},
    {nucleodeCount: '70', decayType: ['b-', 'e']},
    {nucleodeCount: '71', decayType: ['Stable']},
    {nucleodeCount: '72', decayType: ['b-']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73', decayType: ['b-']},
    {nucleodeCount: '73m', decayType: ['IT', 'b-']},
    {nucleodeCount: '74', decayType: ['b-']},
    {nucleodeCount: '74m', decayType: ['IT', 'b-']},
    {nucleodeCount: '75', decayType: ['b-']},
    {nucleodeCount: '76', decayType: ['b-']},
    {nucleodeCount: '77', decayType: ['b-']},
    {nucleodeCount: '78', decayType: ['b-']},
    {nucleodeCount: '78m', decayType: ['IT']},
    {nucleodeCount: '79', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '80', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '80m', decayType: ['b-', 'b-, n', 'IT']},
    {nucleodeCount: '81', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '82', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '82m', decayType: ['IT']},
    {nucleodeCount: '83', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '84', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '85', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '86', decayType: ['b-, n', 'b-, 2n', 'b-']},
    {nucleodeCount: '87', decayType: ['b-, n', 'b-, 2n', 'b-']},
    {nucleodeCount: '88', decayType: ['b-', 'b-, n']}
]