const germanium = [
    {nucleodeCount: '59', decayType: ['b+, p']},
    {nucleodeCount: '59', decayType: ['b+']},
    {nucleodeCount: '59', decayType: ['2p']},
    {nucleodeCount: '60', decayType: ['b+, p']},
    {nucleodeCount: '60', decayType: ['b+, 2p']},
    {nucleodeCount: '61', decayType: ['b+, p']},
    {nucleodeCount: '61', decayType: ['b+']},
    {nucleodeCount: '62', decayType: ['b+']},
    {nucleodeCount: '63', decayType: ['b+']},
    {nucleodeCount: '64', decayType: ['b+']},
    {nucleodeCount: '65', decayType: ['b+']},
    {nucleodeCount: '65', decayType: ['b+, p']},
    {nucleodeCount: '66', decayType: ['b+']},
    {nucleodeCount: '67', decayType: ['b+']},
    {nucleodeCount: '67m1', decayType: ['IT']},
    {nucleodeCount: '67m2', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['EC']},
    {nucleodeCount: '69', decayType: ['b+']},
    {nucleodeCount: '69m1', decayType: ['IT']},
    {nucleodeCount: '69m2', decayType: ['IT']},
    {nucleodeCount: '71', decayType: ['EC']},
    {nucleodeCount: '71m', decayType: ['IT']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73m1', decayType: ['IT']},
    {nucleodeCount: '73m2', decayType: ['IT']},
    {nucleodeCount: '75', decayType: ['b-']},
    {nucleodeCount: '75m1', decayType: ['IT']},
    {nucleodeCount: '75m1', decayType: ['b-']},
    {nucleodeCount: '75m2', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['75.921402725(19)']},
    {nucleodeCount: '76', decayType: ['b-b-']},
    {nucleodeCount: '77', decayType: ['b-']},
    {nucleodeCount: '77m', decayType: ['b-']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '78', decayType: ['b-']},
    {nucleodeCount: '79', decayType: ['b-']},
    {nucleodeCount: '79m', decayType: ['b-']},
    {nucleodeCount: '79m', decayType: ['IT']},
    {nucleodeCount: '80', decayType: ['b-']},
    {nucleodeCount: '81', decayType: ['b-']},
    {nucleodeCount: '81m', decayType: ['b-']},
    {nucleodeCount: '81m', decayType: ['IT']},
    {nucleodeCount: '82', decayType: ['b-']},
    {nucleodeCount: '83', decayType: ['b-']},
    {nucleodeCount: '84', decayType: ['b-']},
    {nucleodeCount: '84', decayType: ['b-, n']},
    {nucleodeCount: '85', decayType: ['b-']},
    {nucleodeCount: '85', decayType: ['b-, n']},
    {nucleodeCount: '86', decayType: ['b-']},
    {nucleodeCount: '86', decayType: ['b-, n']},
    {nucleodeCount: '87', decayType: ['b-']},
    {nucleodeCount: '88', decayType: ['b-']},
]
