const germanium = [
    {nucleodeCount: '59', decayType: ['[[Beta decay', 'b<sup>+</sup>]], [[Proton emission', 'p]] (93%)']},
    {nucleodeCount: '59', decayType: ['b<sup>+</sup> (7%)']},
    {nucleodeCount: '59', decayType: ['2p (<0.2%)']},
    {nucleodeCount: '60', decayType: ['[[Beta decay', 'b<sup>+</sup>]], p']},
    {nucleodeCount: '60', decayType: ['b<sup>+</sup>, 2p (<14%)']},
    {nucleodeCount: '61', decayType: ['b<sup>+</sup>, p (87%)']},
    {nucleodeCount: '61', decayType: ['b<sup>+</sup> (18%)']},
    {nucleodeCount: '62', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '63', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '64', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '65', decayType: ['b<sup>+</sup> (99.99%)']},
    {nucleodeCount: '65', decayType: ['b<sup>+</sup>, p (0.011%)']},
    {nucleodeCount: '66', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '67', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '67m1', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '67m2', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '69', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '69m1', decayType: ['IT']},
    {nucleodeCount: '69m2', decayType: ['IT']},
    {nucleodeCount: '71', decayType: ['EC']},
    {nucleodeCount: '71m', decayType: ['IT']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73m1', decayType: ['IT']},
    {nucleodeCount: '73m2', decayType: ['IT']},
    {nucleodeCount: '75', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '75m1', decayType: ['IT (99.97%)']},
    {nucleodeCount: '75m1', decayType: ['b<sup>-</sup> (0.030%)']},
    {nucleodeCount: '75m2', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['75.921402725(19)']},
    {nucleodeCount: '76', decayType: ['b<sup>-</sup>b<sup>-</sup>']},
    {nucleodeCount: '77', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '77m', decayType: ['b<sup>-</sup> (81%)']},
    {nucleodeCount: '77m', decayType: ['IT (19%)']},
    {nucleodeCount: '78', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '79', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '79m', decayType: ['b<sup>-</sup> (96%)']},
    {nucleodeCount: '79m', decayType: ['IT (4%)']},
    {nucleodeCount: '80', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '81', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '81m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '81m', decayType: ['IT (<1%)']},
    {nucleodeCount: '82', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '83', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '84', decayType: ['b<sup>-</sup> (89.4%)']},
    {nucleodeCount: '84', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (10.6%)']},
    {nucleodeCount: '85', decayType: ['b<sup>-</sup> (82.8%)']},
    {nucleodeCount: '85', decayType: ['b<sup>-</sup>, n (17.2%)']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup> (55%)']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup>, n (45%)']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup>']},
]
