const germanium = [
    {nucleodeCount: '59', decayType: ['b+, p', 'b+', '2p']},
    {nucleodeCount: '60', decayType: ['b+, p', 'b+, 2p']},
    {nucleodeCount: '61', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '62', decayType: ['b+']},
    {nucleodeCount: '63', decayType: ['b+']},
    {nucleodeCount: '64', decayType: ['b+']},
    {nucleodeCount: '65', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '66', decayType: ['b+']},
    {nucleodeCount: '67', decayType: ['b+']},
    {nucleodeCount: '67m1', decayType: ['IT']},
    {nucleodeCount: '67m2', decayType: ['IT']},
    {nucleodeCount: '68', decayType: ['e']},
    {nucleodeCount: '69', decayType: ['b+']},
    {nucleodeCount: '69m1', decayType: ['IT']},
    {nucleodeCount: '69m2', decayType: ['IT']},
    {nucleodeCount: '70', decayType: ['Stable']},
    {nucleodeCount: '71', decayType: ['e']},
    {nucleodeCount: '71m', decayType: ['IT']},
    {nucleodeCount: '72', decayType: ['Stable']},
    {nucleodeCount: '72m', decayType: ['IT']},
    {nucleodeCount: '73', decayType: ['Stable']},
    {nucleodeCount: '73m1', decayType: ['IT']},
    {nucleodeCount: '73m2', decayType: ['IT']},
    {nucleodeCount: '74', decayType: ['Stable']},
    {nucleodeCount: '75', decayType: ['b-']},
    {nucleodeCount: '75m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '75m2', decayType: ['IT']},
    {nucleodeCount: '76', decayType: ['2b-']},
    {nucleodeCount: '77', decayType: ['b-']},
    {nucleodeCount: '77m', decayType: ['b-', 'IT']},
    {nucleodeCount: '78', decayType: ['b-']},
    {nucleodeCount: '79', decayType: ['b-']},
    {nucleodeCount: '79m', decayType: ['b-', 'IT']},
    {nucleodeCount: '80', decayType: ['b-']},
    {nucleodeCount: '81', decayType: ['b-']},
    {nucleodeCount: '81m', decayType: ['b-', 'IT']},
    {nucleodeCount: '82', decayType: ['b-']},
    {nucleodeCount: '83', decayType: ['b-']},
    {nucleodeCount: '84', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '85', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '86', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '87', decayType: ['b-']},
    {nucleodeCount: '88', decayType: ['b-']}
]