const gold = [
    {nucleodeCount: '169', decayType: ['p', 'a']},
    {nucleodeCount: '170', decayType: ['p', 'a']},
    {nucleodeCount: '170m', decayType: ['p', 'a']},
    {nucleodeCount: '171', decayType: ['p', 'a']},
    {nucleodeCount: '171m', decayType: ['a', 'p']},
    {nucleodeCount: '172', decayType: ['a', 'p']},
    {nucleodeCount: '172', decayType: ['b+']},
    {nucleodeCount: '172m', decayType: ['a', 'p']},
    {nucleodeCount: '173', decayType: ['a', 'b+']},
    {nucleodeCount: '173m', decayType: ['a', 'b+']},
    {nucleodeCount: '174', decayType: ['a', 'b+']},
    {nucleodeCount: '174m', decayType: ['a', 'b+']},
    {nucleodeCount: '175', decayType: ['a', 'b+']},
    {nucleodeCount: '175m', decayType: ['a', 'b+']},
    {nucleodeCount: '176', decayType: ['a', 'b+']},
    {nucleodeCount: '176m', decayType: ['a', 'b+']},
    {nucleodeCount: '177', decayType: ['b+', 'a']},
    {nucleodeCount: '177m', decayType: ['a' ,'b+']},
    {nucleodeCount: '178', decayType: ['b+', 'a']},
    {nucleodeCount: '178m1', decayType: ['IT']},
    {nucleodeCount: '178m2', decayType: ['b+' ,'a']},
    {nucleodeCount: '178m3', decayType: ['IT']},
    {nucleodeCount: '179', decayType: ['b+', 'a']},
    {nucleodeCount: '179m', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['b+', 'a']},
    {nucleodeCount: '181', decayType: ['b+', 'a']},
    {nucleodeCount: '182', decayType: ['b+', 'a']},
    {nucleodeCount: '183', decayType: ['b+', 'a']},
    {nucleodeCount: '183m', decayType: ['IT']},
    {nucleodeCount: '184', decayType: ['b+', 'a']},
    {nucleodeCount: '184m', decayType: ['b+', 'IT', 'a']},
    {nucleodeCount: '185', decayType: ['b+', 'a']},
    {nucleodeCount: '185m', decayType: ['b+', 'IT']},
    {nucleodeCount: '186', decayType: ['b+', 'a']},
    {nucleodeCount: '186m', decayType: ['IT']},
    {nucleodeCount: '187', decayType: ['b+', 'a']},
    {nucleodeCount: '187m', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['b+']},
    {nucleodeCount: '189', decayType: ['b+', 'a']},
    {nucleodeCount: '189m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '189m3', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['b+', 'a']},
    {nucleodeCount: '190m', decayType: ['IT', 'b+']},
    {nucleodeCount: '191', decayType: ['b+']},
    {nucleodeCount: '191m1', decayType: ['IT']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b+']},
    {nucleodeCount: '192m1', decayType: ['IT']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['b+', 'a']},
    {nucleodeCount: '193m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b+']},
    {nucleodeCount: '194m1', decayType: ['IT']},
    {nucleodeCount: '194m2', decayType: ['IT']},
    {nucleodeCount: '195', decayType: ['e']},
    {nucleodeCount: '195m1', decayType: ['IT']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b+', 'b-']},
    {nucleodeCount: '196m1', decayType: ['IT']},
    {nucleodeCount: '196m2', decayType: ['IT']},
    {nucleodeCount: '197', decayType: ['Stable']},
    {nucleodeCount: '197m1', decayType: ['IT']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b-']},
    {nucleodeCount: '198m1', decayType: ['IT']},
    {nucleodeCount: '198m2', decayType: ['IT']},
    {nucleodeCount: '199', decayType: ['b-']},
    {nucleodeCount: '199m', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['b-']},
    {nucleodeCount: '200m', decayType: ['b-', 'IT']},
    {nucleodeCount: '201', decayType: ['b-']},
    {nucleodeCount: '201m1', decayType: ['IT']},
    {nucleodeCount: '201m2', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['b-']},
    {nucleodeCount: '203', decayType: ['b-']},
    {nucleodeCount: '203m', decayType: ['IT']},
    {nucleodeCount: '204', decayType: ['b-']},
    {nucleodeCount: '204m', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b-']},
    {nucleodeCount: '205m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '206', decayType: ['b-']},
    {nucleodeCount: '207', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '208', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '209', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '210', decayType: ['b-', 'b-, n']}
]