const hafnium = [
    {nucleodeCount: '154', decayType: ['b+', 'a']},
    {nucleodeCount: '154m', decayType: ['IT']},
    {nucleodeCount: '155', decayType: ['b+']},
    {nucleodeCount: '156', decayType: ['a']},
    {nucleodeCount: '156m', decayType: ['a']},
    {nucleodeCount: '157', decayType: ['a', 'b+']},
    {nucleodeCount: '158', decayType: ['b+', 'a']},
    {nucleodeCount: '159', decayType: ['b+', 'a']},
    {nucleodeCount: '160', decayType: ['b+', 'a']},
    {nucleodeCount: '161', decayType: ['b+' ,'a']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b+' ,'a']},
    {nucleodeCount: '163', decayType: ['b+']},
    {nucleodeCount: '164', decayType: ['b+']},
    {nucleodeCount: '165', decayType: ['b+']},
    {nucleodeCount: '166', decayType: ['b+']},
    {nucleodeCount: '167', decayType: ['b+']},
    {nucleodeCount: '168', decayType: ['e' ,'b+']},
    {nucleodeCount: '169', decayType: ['b+']},
    {nucleodeCount: '170', decayType: ['e']},
    {nucleodeCount: '171', decayType: ['b+']},
    {nucleodeCount: '171m', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['e']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['b+']},
    {nucleodeCount: '173m1', decayType: ['IT']},
    {nucleodeCount: '173m2', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['a', '2b+']},
    {nucleodeCount: '174m1', decayType: ['IT']},
    {nucleodeCount: '174m2', decayType: ['IT']},
    {nucleodeCount: '174m3', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['e']},
    {nucleodeCount: '175m1', decayType: ['IT']},
    {nucleodeCount: '175m2', decayType: ['IT']},
    {nucleodeCount: '175m3', decayType: ['IT']},
    {nucleodeCount: '175m4', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['Stable']},
    {nucleodeCount: '176m1', decayType: ['IT']},
    {nucleodeCount: '176m2', decayType: ['IT']},
    {nucleodeCount: '176m3', decayType: ['IT']},
    {nucleodeCount: '176m4', decayType: ['IT']},
    {nucleodeCount: '177', decayType: ['Stable']},
    {nucleodeCount: '177m1', decayType: ['IT']},
    {nucleodeCount: '177m2', decayType: ['IT']},
    {nucleodeCount: '177m3', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['Stable']},
    {nucleodeCount: '178m1', decayType: ['IT']},
    {nucleodeCount: '178m2', decayType: ['IT']},
    {nucleodeCount: '178m3', decayType: ['IT']},
    {nucleodeCount: '179', decayType: ['Stable']},
    {nucleodeCount: '179m1', decayType: ['IT']},
    {nucleodeCount: '179m2', decayType: ['IT']},
    {nucleodeCount: '179m3', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['Stable']},
    {nucleodeCount: '180m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '180m2', decayType: ['IT']},
    {nucleodeCount: '180m3', decayType: ['IT']},
    {nucleodeCount: '180m4', decayType: ['IT']},
    {nucleodeCount: '181', decayType: ['b-']},
    {nucleodeCount: '181m1', decayType: ['IT']},
    {nucleodeCount: '181m2', decayType: ['IT']},
    {nucleodeCount: '181m3', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['b-']},
    {nucleodeCount: '182m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '182m2', decayType: ['IT']},
    {nucleodeCount: '183', decayType: ['b-']},
    {nucleodeCount: '183m', decayType: ['IT']},
    {nucleodeCount: '184', decayType: ['b-']},
    {nucleodeCount: '184m1', decayType: ['IT']},
    {nucleodeCount: '185', decayType: ['b-']},
    {nucleodeCount: '186', decayType: ['b-']},
    {nucleodeCount: '187m', decayType: ['IT']}
]