const holmium = [
    {nucleodeCount: '140', decayType: ['p']},
    {nucleodeCount: '141', decayType: ['p']},
    {nucleodeCount: '141m', decayType: ['p']},
    {nucleodeCount: '142', decayType: ['b+', 'b+, p', 'p']},
    {nucleodeCount: '144', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '144m', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b+']},
    {nucleodeCount: '146', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '147', decayType: ['b+']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['b+']},
    {nucleodeCount: '148m1', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '148m2', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b+']},
    {nucleodeCount: '149m', decayType: ['b+']},
    {nucleodeCount: '150', decayType: ['b+']},
    {nucleodeCount: '150m1', decayType: ['b+']},
    {nucleodeCount: '150m2', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['b+', 'a']},
    {nucleodeCount: '151m', decayType: ['a', 'b+']},
    {nucleodeCount: '152', decayType: ['b+', 'a']},
    {nucleodeCount: '152m1', decayType: ['b+', 'a']},
    {nucleodeCount: '152m2', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['b+', 'a']},
    {nucleodeCount: '153m1', decayType: ['b+', 'a']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b+', 'a']},
    {nucleodeCount: '154m', decayType: ['b+', 'a', 'IT']},
    {nucleodeCount: '155', decayType: ['b+']},
    {nucleodeCount: '155m', decayType: ['IT']},
    {nucleodeCount: '156', decayType: ['b+']},
    {nucleodeCount: '156m1', decayType: ['IT']},
    {nucleodeCount: '156m2', decayType: ['b+', 'IT']},
    {nucleodeCount: '157', decayType: ['b+']},
    {nucleodeCount: '158', decayType: ['b+']},
    {nucleodeCount: '158m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '158m2', decayType: ['IT']},
    {nucleodeCount: '158m3', decayType: ['b+']},
    {nucleodeCount: '159', decayType: ['b+']},
    {nucleodeCount: '159m', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['b+']},
    {nucleodeCount: '160m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '160m2', decayType: ['IT']},
    {nucleodeCount: '161', decayType: ['e']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b+']},
    {nucleodeCount: '162m', decayType: ['IT', 'b+']},
    {nucleodeCount: '163', decayType: ['e']},
    {nucleodeCount: '163m1', decayType: ['IT']},
    {nucleodeCount: '163m2', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['e', 'b-']},
    {nucleodeCount: '164m', decayType: ['IT']},
    {nucleodeCount: '165', decayType: ['Stable']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['b-']},
    {nucleodeCount: '166m1', decayType: ['b-']},
    {nucleodeCount: '166m2', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['b-']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['b-']},
    {nucleodeCount: '168m1', decayType: ['IT']},
    {nucleodeCount: '168m2', decayType: ['IT']},
    {nucleodeCount: '168m3', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b-']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['b-']},
    {nucleodeCount: '170m', decayType: ['b-']},
    {nucleodeCount: '171', decayType: ['b-']},
    {nucleodeCount: '172', decayType: ['b-']},
    {nucleodeCount: '173', decayType: ['b-']},
    {nucleodeCount: '173m', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['b-']},
    {nucleodeCount: '175', decayType: ['b-']},
    {nucleodeCount: '177', decayType: ['b-']}
]