const holmium = [
    {nucleodeCount: '140', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '141', decayType: ['p']},
    {nucleodeCount: '141m', decayType: ['p']},
    {nucleodeCount: '142', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '142', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '142', decayType: ['p (?%)']},
    {nucleodeCount: '144', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '144', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '144m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '145', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '147', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '147m', decayType: ['IT']},
    {nucleodeCount: '148', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '148m1', decayType: ['b<sup>+</sup> (99.92%)']},
    {nucleodeCount: '148m1', decayType: ['b<sup>+</sup>, p (0.08%)']},
    {nucleodeCount: '148m2', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '149m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150m2', decayType: ['IT']},
    {nucleodeCount: '151', decayType: ['b<sup>+</sup> (78%)']},
    {nucleodeCount: '151', decayType: ['[[alpha decay', 'a]] (22%)']},
    {nucleodeCount: '151m', decayType: ['a (77%)']},
    {nucleodeCount: '151m', decayType: ['b<sup>+</sup> (23%)']},
    {nucleodeCount: '152', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '152', decayType: ['a (12%)']},
    {nucleodeCount: '152m1', decayType: ['b<sup>+</sup> (89.2%)']},
    {nucleodeCount: '152m1', decayType: ['a (10.8%)']},
    {nucleodeCount: '152m2', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['b<sup>+</sup> (99.95%)']},
    {nucleodeCount: '153', decayType: ['a (0.051%)']},
    {nucleodeCount: '153m1', decayType: ['b<sup>+</sup> (99.82%)']},
    {nucleodeCount: '153m1', decayType: ['a (0.18%)']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b<sup>+</sup> (99.98%)']},
    {nucleodeCount: '154', decayType: ['a (0.019%)']},
    {nucleodeCount: '154m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '154m', decayType: ['a (<0.001%)']},
    {nucleodeCount: '154m', decayType: ['[[Isomeric transition', 'IT]] (rare)']},
    {nucleodeCount: '155', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '155m', decayType: ['IT']},
    {nucleodeCount: '156', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '156m1', decayType: ['IT']},
    {nucleodeCount: '156m2', decayType: ['b<sup>+</sup> (75%)']},
    {nucleodeCount: '156m2', decayType: ['IT (25%)']},
    {nucleodeCount: '157', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '158', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '158m1', decayType: ['IT (91%)']},
    {nucleodeCount: '158m1', decayType: ['b<sup>+</sup> (9%)']},
    {nucleodeCount: '158m2', decayType: ['IT']},
    {nucleodeCount: '158m3', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '159', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '159m', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '160m1', decayType: ['IT (73%)']},
    {nucleodeCount: '160m1', decayType: ['b<sup>+</sup> (27%)']},
    {nucleodeCount: '160m2', decayType: ['IT']},
    {nucleodeCount: '161', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '162m', decayType: ['IT (62%)']},
    {nucleodeCount: '162m', decayType: ['b<sup>+</sup> (38%)']},
    {nucleodeCount: '163', decayType: ['EC']},
    {nucleodeCount: '163m1', decayType: ['IT']},
    {nucleodeCount: '163m2', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['EC (61%)']},
    {nucleodeCount: '164', decayType: ['b<sup>-</sup> (39%)']},
    {nucleodeCount: '164m', decayType: ['IT']},
    {nucleodeCount: '165', decayType: ['164.93032912(84)']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166m2', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '168m1', decayType: ['IT']},
    {nucleodeCount: '168m2', decayType: ['IT']},
    {nucleodeCount: '168m3', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '170m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '173', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '173m', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '175', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '177', decayType: ['b<sup>-</sup>']},
]
