const indium = [
    {nucleodeCount: '96', decayType: ['b+', 'p']},
    {nucleodeCount: '97', decayType: ['b+', 'b+, p', 'p']},
    {nucleodeCount: '97m', decayType: ['p']},
    {nucleodeCount: '98', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '98m', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '99', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '100', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '101', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '101m', decayType: ['b+', 'IT']},
    {nucleodeCount: '102', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '103', decayType: ['b+']},
    {nucleodeCount: '103m', decayType: ['b+', 'IT']},
    {nucleodeCount: '104', decayType: ['b+']},
    {nucleodeCount: '104m', decayType: ['IT', 'b+']},
    {nucleodeCount: '105', decayType: ['b+']},
    {nucleodeCount: '105m', decayType: ['IT', 'b+']},
    {nucleodeCount: '106', decayType: ['b+']},
    {nucleodeCount: '106m', decayType: ['b+']},
    {nucleodeCount: '107', decayType: ['b+']},
    {nucleodeCount: '107m', decayType: ['IT']},
    {nucleodeCount: '108', decayType: ['b+']},
    {nucleodeCount: '108m', decayType: ['b+']},
    {nucleodeCount: '109', decayType: ['b+']},
    {nucleodeCount: '109m1', decayType: ['IT']},
    {nucleodeCount: '109m2', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b+']},
    {nucleodeCount: '110m', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['e']},
    {nucleodeCount: '111m', decayType: ['IT']},
    {nucleodeCount: '112', decayType: ['b+', 'b-']},
    {nucleodeCount: '112m1', decayType: ['IT']},
    {nucleodeCount: '112m2', decayType: ['IT']},
    {nucleodeCount: '112m3', decayType: ['IT']},
    {nucleodeCount: '113', decayType: ['Stable']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b-', 'b+']},
    {nucleodeCount: '114m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '114m2', decayType: ['IT', 'b+']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['IT', 'b-']},
    {nucleodeCount: '116', decayType: ['b-', 'e']},
    {nucleodeCount: '116m1', decayType: ['b-']},
    {nucleodeCount: '116m2', decayType: ['IT']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['b-', 'IT']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '118m1', decayType: ['b-']},
    {nucleodeCount: '118m2', decayType: ['IT', 'b-']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '119m2', decayType: ['IT']},
    {nucleodeCount: '119m3', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '120m1', decayType: ['b-']},
    {nucleodeCount: '120m2', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '121m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '121m2', decayType: ['IT']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '122m1', decayType: ['b-']},
    {nucleodeCount: '122m2', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '123m1', decayType: ['b-']},
    {nucleodeCount: '123m2', decayType: ['IT']},
    {nucleodeCount: '123m3', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '124m', decayType: ['b-']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125m1', decayType: ['b-']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '125m3', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '126m1', decayType: ['b-']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '127m1', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '127m2', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '127m3', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '128m1', decayType: ['IT']},
    {nucleodeCount: '128m2', decayType: ['b-', 'IT', 'b-, n']},
    {nucleodeCount: '128m3', decayType: ['b-', 'IT', 'b-, n']},
    {nucleodeCount: '129', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '129m1', decayType: ['b-', 'b-, n', 'IT']},
    {nucleodeCount: '129m2', decayType: ['b-', 'IT']},
    {nucleodeCount: '129m3', decayType: ['IT']},
    {nucleodeCount: '129m4', decayType: ['IT', 'b-']},
    {nucleodeCount: '130', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '130m1', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '130m2', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '130m3', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '131m1', decayType: ['b-', 'b-, n', 'IT']},
    {nucleodeCount: '131m2', decayType: ['b-', 'b-, n', 'IT']},
    {nucleodeCount: '131m3', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '133', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '133m', decayType: ['b-, n', 'b-']},
    {nucleodeCount: '134', decayType: ['b-, n', 'b-', 'b-, 2n']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '136', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '137', decayType: ['b-', 'b-, n', 'b-, 2n']}
]