const iodine = [
    {nucleodeCount: '108', decayType: ['a', 'p', 'b+', 'b+, p']},
    {nucleodeCount: '109', decayType: ['p', 'a']},
    {nucleodeCount: '110', decayType: ['b+' ,'a', 'b+, p', 'b+, a']},
    {nucleodeCount: '111', decayType: ['b+', 'a', 'b+, p']},
    {nucleodeCount: '112', decayType: ['b+', 'b+, p' ,'b+, a', 'a']},
    {nucleodeCount: '113', decayType: ['b+', 'a', 'b+, a']},
    {nucleodeCount: '114', decayType: ['b+', 'b+, p', 'a']},
    {nucleodeCount: '114m', decayType: ['b+', 'IT']},
    {nucleodeCount: '115', decayType: ['b+']},
    {nucleodeCount: '116', decayType: ['b+']},
    {nucleodeCount: '116m', decayType: ['IT']},
    {nucleodeCount: '117', decayType: ['b+', 'e']},
    {nucleodeCount: '118', decayType: ['b+']},
    {nucleodeCount: '118m', decayType: ['b+', 'IT']},
    {nucleodeCount: '119', decayType: ['b+', 'e']},
    {nucleodeCount: '120', decayType: ['b+']},
    {nucleodeCount: '120m1', decayType: ['IT']},
    {nucleodeCount: '120m2', decayType: ['b+']},
    {nucleodeCount: '121', decayType: ['b+']},
    {nucleodeCount: '121m', decayType: ['IT']},
    {nucleodeCount: '122', decayType: ['b+', 'e']},
    {nucleodeCount: '122m1', decayType: ['IT']},
    {nucleodeCount: '122m2', decayType: ['IT']},
    {nucleodeCount: '122m3', decayType: ['IT']},
    {nucleodeCount: '122m4', decayType: ['IT']},
    {nucleodeCount: '123', decayType: ['e']},
    {nucleodeCount: '124', decayType: ['b+']},
    {nucleodeCount: '125', decayType: ['e']},
    {nucleodeCount: '126', decayType: ['b+', 'b-']},
    {nucleodeCount: '126m', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['Stable']},
    {nucleodeCount: '128', decayType: ['b-', 'b+']},
    {nucleodeCount: '128m1', decayType: ['IT']},
    {nucleodeCount: '128m2', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b-']},
    {nucleodeCount: '130', decayType: ['b-']},
    {nucleodeCount: '130m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '130m2', decayType: ['IT']},
    {nucleodeCount: '130m3', decayType: ['IT']},
    {nucleodeCount: '130m4', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b-']},
    {nucleodeCount: '131m', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b-']},
    {nucleodeCount: '132m', decayType: ['IT', 'b-']},
    {nucleodeCount: '133', decayType: ['b-']},
    {nucleodeCount: '133m1', decayType: ['IT']},
    {nucleodeCount: '133m2', decayType: ['IT']},
    {nucleodeCount: '133m3', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b-']},
    {nucleodeCount: '134m', decayType: ['IT', 'b-']},
    {nucleodeCount: '135', decayType: ['b-']},
    {nucleodeCount: '136', decayType: ['b-']},
    {nucleodeCount: '136m', decayType: ['b-']},
    {nucleodeCount: '137', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '138', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '138m', decayType: ['IT']},
    {nucleodeCount: '139', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '140', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '141', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '142', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '143', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '144', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '145', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '146', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '147', decayType: ['b-', 'b-, n', 'b-, 2n']}
]