const iridium = [
    {nucleodeCount: '164', decayType: ['p']},
    {nucleodeCount: '164m', decayType: ['p', 'a']},
    {nucleodeCount: '165', decayType: ['p']},
    {nucleodeCount: '165m', decayType: ['p', 'a']},
    {nucleodeCount: '166', decayType: ['a', 'p']},
    {nucleodeCount: '166m', decayType: ['a', 'p']},
    {nucleodeCount: '167', decayType: ['a', 'p', 'b+']},
    {nucleodeCount: '167m', decayType: ['a', 'b+', 'p']},
    {nucleodeCount: '168', decayType: ['a']},
    {nucleodeCount: '168m', decayType: ['a', 'b+', 'b+, p']},
    {nucleodeCount: '169', decayType: ['a', 'b+']},
    {nucleodeCount: '169m', decayType: ['a', 'b+', 'p']},
    {nucleodeCount: '170', decayType: ['b+', 'a']},
    {nucleodeCount: '170m', decayType: ['a', 'b+', 'IT']},
    {nucleodeCount: '171', decayType: ['b+', 'a']},
    {nucleodeCount: '171m', decayType: ['a', 'b+', 'p']},
    {nucleodeCount: '172', decayType: ['b+', 'a']},
    {nucleodeCount: '172m', decayType: ['b+', 'a']},
    {nucleodeCount: '173', decayType: ['b+', 'a']},
    {nucleodeCount: '173m', decayType: ['b+', 'a']},
    {nucleodeCount: '174', decayType: ['b+', 'a']},
    {nucleodeCount: '174m', decayType: ['b+', 'a']},
    {nucleodeCount: '175', decayType: ['b+', 'a']},
    {nucleodeCount: '175m1', decayType: ['b+']},
    {nucleodeCount: '175m2', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['b+', 'a']},
    {nucleodeCount: '177', decayType: ['b+', 'a']},
    {nucleodeCount: '177m', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['b+']},
    {nucleodeCount: '179', decayType: ['b+']},
    {nucleodeCount: '180', decayType: ['b+']},
    {nucleodeCount: '181', decayType: ['b+']},
    {nucleodeCount: '181m1', decayType: ['IT']},
    {nucleodeCount: '181m2', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['b+']},
    {nucleodeCount: '182m1', decayType: ['IT']},
    {nucleodeCount: '182m2', decayType: ['IT']},
    {nucleodeCount: '183', decayType: ['b+']},
    {nucleodeCount: '184', decayType: ['b+']},
    {nucleodeCount: '184m1', decayType: ['IT']},
    {nucleodeCount: '184m2', decayType: ['IT']},
    {nucleodeCount: '185', decayType: ['b+']},
    {nucleodeCount: '185m', decayType: ['IT']},
    {nucleodeCount: '186', decayType: ['b+']},
    {nucleodeCount: '186m', decayType: ['b+', 'IT']},
    {nucleodeCount: '187', decayType: ['b+']},
    {nucleodeCount: '187m1', decayType: ['IT']},
    {nucleodeCount: '187m2', decayType: ['IT']},
    {nucleodeCount: '187m3', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['b+']},
    {nucleodeCount: '188m', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['e']},
    {nucleodeCount: '189m1', decayType: ['IT']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['e', 'b+']},
    {nucleodeCount: '190m1', decayType: ['IT']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['e', 'IT']},
    {nucleodeCount: '191', decayType: ['Stable']},
    {nucleodeCount: '191m1', decayType: ['IT']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b-', 'e']},
    {nucleodeCount: '192m1', decayType: ['IT', 'b-']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['Stable']},
    {nucleodeCount: '193m1', decayType: ['IT']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b-']},
    {nucleodeCount: '194m1', decayType: ['IT']},
    {nucleodeCount: '194m2', decayType: ['b-']},
    {nucleodeCount: '195', decayType: ['b-']},
    {nucleodeCount: '195m1', decayType: ['b-']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b-']},
    {nucleodeCount: '196m', decayType: ['b-']},
    {nucleodeCount: '197', decayType: ['b-']},
    {nucleodeCount: '197m1', decayType: ['b-']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '197m3', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b-']},
    {nucleodeCount: '199', decayType: ['b-']},
    {nucleodeCount: '200', decayType: ['b-']},
    {nucleodeCount: '201', decayType: ['b-']},
    {nucleodeCount: '202', decayType: ['b-']},
    {nucleodeCount: '202m', decayType: ['IT']},
    {nucleodeCount: '203m', decayType: ['IT']}
]