const iridium = [
    {nucleodeCount: '164', decayType: ['[[proton emission', 'p]]?']},
    {nucleodeCount: '164m', decayType: ['p (96%)']},
    {nucleodeCount: '164m', decayType: ['[[alpha decay', 'a]] (4%)']},
    {nucleodeCount: '165', decayType: ['p']},
    {nucleodeCount: '165m', decayType: ['p (88%)']},
    {nucleodeCount: '165m', decayType: ['a (12%)']},
    {nucleodeCount: '166', decayType: ['a (93%)']},
    {nucleodeCount: '166', decayType: ['p (7%)']},
    {nucleodeCount: '166m', decayType: ['a (98.2%)']},
    {nucleodeCount: '166m', decayType: ['p (1.8%)']},
    {nucleodeCount: '167', decayType: ['a (43.5%)']},
    {nucleodeCount: '167', decayType: ['p (38.6%)']},
    {nucleodeCount: '167', decayType: ['b<sup>+</sup> (17.9%)']},
    {nucleodeCount: '167m', decayType: ['a (89%)']},
    {nucleodeCount: '167m', decayType: ['b<sup>+</sup> (11%)']},
    {nucleodeCount: '167m', decayType: ['p (0.41%)']},
    {nucleodeCount: '168', decayType: ['a']},
    {nucleodeCount: '168m', decayType: ['a (77%)']},
    {nucleodeCount: '168m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '168m', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '169', decayType: ['a (53%)']},
    {nucleodeCount: '169', decayType: ['b<sup>+</sup> (47%)']},
    {nucleodeCount: '169m', decayType: ['a (79%)']},
    {nucleodeCount: '169m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '169m', decayType: ['p?']},
    {nucleodeCount: '170', decayType: ['b<sup>+</sup> (94.8%)']},
    {nucleodeCount: '170', decayType: ['a (5.2%)']},
    {nucleodeCount: '170m', decayType: ['a (38%)']},
    {nucleodeCount: '170m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '170m', decayType: ['IT?']},
    {nucleodeCount: '171', decayType: ['b<sup>+</sup> (85%)']},
    {nucleodeCount: '171', decayType: ['a (15%)']},
    {nucleodeCount: '171m', decayType: ['a (54%)']},
    {nucleodeCount: '171m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '171m', decayType: ['p?']},
    {nucleodeCount: '172', decayType: ['b<sup>+</sup> (~98%)']},
    {nucleodeCount: '172', decayType: ['a (~2%)']},
    {nucleodeCount: '172m', decayType: ['b<sup>+</sup> (90.5%)']},
    {nucleodeCount: '172m', decayType: ['a (9.5%)']},
    {nucleodeCount: '173', decayType: ['b<sup>+</sup> (96.5%)']},
    {nucleodeCount: '173', decayType: ['a (3.5%)']},
    {nucleodeCount: '173m', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '173m', decayType: ['a (12%)']},
    {nucleodeCount: '174', decayType: ['b<sup>+</sup> (99.5%)']},
    {nucleodeCount: '174', decayType: ['a (0.5%)']},
    {nucleodeCount: '174m', decayType: ['b<sup>+</sup> (97.5%)']},
    {nucleodeCount: '174m', decayType: ['a (2.5%)']},
    {nucleodeCount: '175', decayType: ['b<sup>+</sup> (99.15%)']},
    {nucleodeCount: '175', decayType: ['a (0.85%)']},
    {nucleodeCount: '175m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '175m2', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['b<sup>+</sup> (96.9%)']},
    {nucleodeCount: '176', decayType: ['a (3.1%)']},
    {nucleodeCount: '177', decayType: ['b<sup>+</sup> (99.94%)']},
    {nucleodeCount: '177', decayType: ['a (0.06%)']},
    {nucleodeCount: '177m', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '179', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '180', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '181', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '181m1', decayType: ['IT']},
    {nucleodeCount: '181m2', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '182m1', decayType: ['IT']},
    {nucleodeCount: '182m2', decayType: ['IT']},
    {nucleodeCount: '183', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '184', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '184m1', decayType: ['IT']},
    {nucleodeCount: '184m2', decayType: ['IT']},
    {nucleodeCount: '185', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '185m', decayType: ['IT']},
    {nucleodeCount: '186', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '186m', decayType: ['b<sup>+</sup> (~75%)']},
    {nucleodeCount: '186m', decayType: ['IT (~25%)']},
    {nucleodeCount: '187', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '187m1', decayType: ['IT']},
    {nucleodeCount: '187m2', decayType: ['IT']},
    {nucleodeCount: '187m3', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '188m', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['EC']},
    {nucleodeCount: '189m1', decayType: ['IT']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['rowspan=2', '189.9605434(15)']},
    {nucleodeCount: '190', decayType: ['EC']},
    {nucleodeCount: '190m1', decayType: ['IT']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['EC (91.4%)']},
    {nucleodeCount: '190m3', decayType: ['IT (8.6%)']},
    {nucleodeCount: '191', decayType: ['190.9605915(14)']},
    {nucleodeCount: '191m1', decayType: ['IT']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b<sup>-</sup> (95.24%)']},
    {nucleodeCount: '192', decayType: ['EC (4.76%)']},
    {nucleodeCount: '192m1', decayType: ['IT (99.98%)']},
    {nucleodeCount: '192m1', decayType: ['b<sup>-</sup> (0.0175%)']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['192.9629238(14)']},
    {nucleodeCount: '193m1', decayType: ['IT']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '194m1', decayType: ['IT']},
    {nucleodeCount: '194m2', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '195', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '195m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '196m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '197', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '197m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '197m3', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '199', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '200', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '201', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '202', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '202m', decayType: ['IT']},
    {nucleodeCount: '203m', decayType: ['IT']},
]
