const iron = [
    {nucleodeCount: '45', decayType: ['2p', 'b+, p', 'b+, 2p', 'b+']},
    {nucleodeCount: '46', decayType: ['b+, p', 'b+', 'b+, 2p']},
    {nucleodeCount: '47', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '48', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '49', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '50', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '51', decayType: ['b+']},
    {nucleodeCount: '52', decayType: ['b+']},
    {nucleodeCount: '52m', decayType: ['b+', 'IT']},
    {nucleodeCount: '53', decayType: ['b+']},
    {nucleodeCount: '53m', decayType: ['IT']},
    {nucleodeCount: '54', decayType: ['Stable']},
    {nucleodeCount: '54m', decayType: ['IT']},
    {nucleodeCount: '55', decayType: ['e']},
    {nucleodeCount: '56', decayType: ['Stable']},
    {nucleodeCount: '57', decayType: ['Stable']},
    {nucleodeCount: '58', decayType: ['Stable']},
    {nucleodeCount: '59', decayType: ['b-']},
    {nucleodeCount: '60', decayType: ['b-']},
    {nucleodeCount: '61', decayType: ['b-']},
    {nucleodeCount: '61m', decayType: ['IT']},
    {nucleodeCount: '62', decayType: ['b-']},
    {nucleodeCount: '63', decayType: ['b-']},
    {nucleodeCount: '64', decayType: ['b-']},
    {nucleodeCount: '65', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '65m1', decayType: ['b-']},
    {nucleodeCount: '65m2', decayType: ['IT']},
    {nucleodeCount: '66', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '67', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '67m1', decayType: ['IT']},
    {nucleodeCount: '67m2', decayType: ['IT']},
    {nucleodeCount: '68', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '69', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '70', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '71', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '72', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '73', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '74', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '75', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '76', decayType: ['b-']}
]