const krypton = [
    {nucleodeCount: '67', decayType: ['b+', '2p']},
    {nucleodeCount: '68', decayType: ['b+, p', 'b+', 'p']},
    {nucleodeCount: '69', decayType: ['b+, p', 'b+']},
    {nucleodeCount: '70', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '71', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '72', decayType: ['b+']},
    {nucleodeCount: '73', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '73m', decayType: ['IT']},
    {nucleodeCount: '74', decayType: ['b+']},
    {nucleodeCount: '75', decayType: ['b+']},
    {nucleodeCount: '76', decayType: ['b+']},
    {nucleodeCount: '77', decayType: ['b+']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '78', decayType: ['2e']},
    {nucleodeCount: '79', decayType: ['b+']},
    {nucleodeCount: '79m', decayType: ['IT']},
    {nucleodeCount: '80', decayType: ['Stable']},
    {nucleodeCount: '81', decayType: ['e']},
    {nucleodeCount: '81m', decayType: ['IT', 'e']},
    {nucleodeCount: '82', decayType: ['Stable']},
    {nucleodeCount: '83', decayType: ['Stable']},
    {nucleodeCount: '83m1', decayType: ['IT']},
    {nucleodeCount: '83m2', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['Stable']},
    {nucleodeCount: '84m', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b-']},
    {nucleodeCount: '85m1', decayType: ['b-', 'IT']},
    {nucleodeCount: '85m2', decayType: ['IT']},
    {nucleodeCount: '86', decayType: ['Stable']},
    {nucleodeCount: '87', decayType: ['b-']},
    {nucleodeCount: '88', decayType: ['b-']},
    {nucleodeCount: '89', decayType: ['b-']},
    {nucleodeCount: '90', decayType: ['b-']},
    {nucleodeCount: '91', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '92', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '93', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '94', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '95', decayType: ['b-','b-, n', 'b-, 2n']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b-', 'b-, n']},
    {nucleodeCount: '97', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '98', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '99', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '100', decayType: ['b-', 'b-, n', 'b-, 2n']},
    {nucleodeCount: '101', decayType: ['b-', 'b-, n', 'b-, 2n']}
]