const lanthanum = [
    {nucleodeCount: '116', decayType: ['p (~)']},
    {nucleodeCount: '116', decayType: ['b+ (~)']},
    {nucleodeCount: '116m', decayType: ['IT']},
    {nucleodeCount: '117', decayType: ['p']},
    {nucleodeCount: '117', decayType: ['b+']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b+']},
    {nucleodeCount: '120', decayType: ['b+, p']},
    {nucleodeCount: '121', decayType: ['b+']},
    {nucleodeCount: '122', decayType: ['b+']},
    {nucleodeCount: '122', decayType: ['b+, p']},
    {nucleodeCount: '123', decayType: ['b+']},
    {nucleodeCount: '124', decayType: ['b+']},
    {nucleodeCount: '124m', decayType: ['b+']},
    {nucleodeCount: '125', decayType: ['b+']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b+']},
    {nucleodeCount: '126m', decayType: ['b+']},
    {nucleodeCount: '127', decayType: ['b+']},
    {nucleodeCount: '127m', decayType: ['b+']},
    {nucleodeCount: '128', decayType: ['b+']},
    {nucleodeCount: '128m', decayType: ['b+']},
    {nucleodeCount: '129', decayType: ['b+']},
    {nucleodeCount: '129m', decayType: ['IT']},
    {nucleodeCount: '130', decayType: ['b+']},
    {nucleodeCount: '130m', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b+']},
    {nucleodeCount: '131m', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b+']},
    {nucleodeCount: '132m', decayType: ['IT']},
    {nucleodeCount: '132m', decayType: ['b+']},
    {nucleodeCount: '133', decayType: ['b+']},
    {nucleodeCount: '134', decayType: ['b+']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b+']},
    {nucleodeCount: '136', decayType: ['b+']},
    {nucleodeCount: '136m1', decayType: ['IT']},
    {nucleodeCount: '136m2', decayType: ['IT']},
    {nucleodeCount: '137', decayType: ['EC']},
    {nucleodeCount: '137m', decayType: ['IT']},
    {nucleodeCount: '138', decayType: ['b+']},
    {nucleodeCount: '138', decayType: ['b-']},
    {nucleodeCount: '138m1', decayType: ['IT']},
    {nucleodeCount: '138m2', decayType: ['IT']},
    {nucleodeCount: '139m', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['b-']},
    {nucleodeCount: '141', decayType: ['b-']},
    {nucleodeCount: '142', decayType: ['b-']},
    {nucleodeCount: '142m', decayType: ['IT']},
    {nucleodeCount: '143', decayType: ['b-']},
    {nucleodeCount: '144', decayType: ['b-']},
    {nucleodeCount: '145', decayType: ['b-']},
    {nucleodeCount: '146', decayType: ['b-']},
    {nucleodeCount: '146m', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-, n']},
    {nucleodeCount: '148', decayType: ['b-']},
    {nucleodeCount: '148', decayType: ['b-, n']},
    {nucleodeCount: '149', decayType: ['b-']},
    {nucleodeCount: '149', decayType: ['b-, n']},
    {nucleodeCount: '150', decayType: ['b-']},
    {nucleodeCount: '150', decayType: ['b-, n']},
    {nucleodeCount: '151', decayType: ['b-']},
    {nucleodeCount: '152', decayType: ['b-']},
    {nucleodeCount: '153', decayType: ['b-']},
    {nucleodeCount: '154', decayType: ['b-']},
    {nucleodeCount: '155', decayType: ['b-']},
    {nucleodeCount: '156', decayType: ['b-']},
]
