const lawrencium = [
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '251m', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['a (~)']},
    {nucleodeCount: 'None', decayType: ['b+']},
    {nucleodeCount: '253', decayType: ['a']},
    {nucleodeCount: '253', decayType: ['b+']},
    {nucleodeCount: '253m', decayType: ['a']},
    {nucleodeCount: '253m', decayType: ['b+']},
    {nucleodeCount: '254', decayType: ['a']},
    {nucleodeCount: '254', decayType: ['b+']},
    {nucleodeCount: '254m', decayType: ['a']},
    {nucleodeCount: '254m', decayType: ['b+']},
    {nucleodeCount: '254m', decayType: ['IT']},
    {nucleodeCount: '255', decayType: ['a']},
    {nucleodeCount: '255', decayType: ['b+<ref>{{cite journal', 'last1=Chatillon', 'first1=A.', 'last2=Theisen', 'first2=Ch.', 'last3=Greenlees', 'first3=P. T.', 'last4=Auger', 'first4=G.', 'last5=Bastin', 'first5=J. E.', 'last6=Bouchez', 'first6=E.', 'last7=Bouriquet', 'first7=B.', 'last8=Casandjian', 'first8=J. M.', 'last9=Cee', 'first9=R.', 'last10=Cl�ment', 'first10=E.', 'last11=Dayras', 'first11=R.', 'last12=de France', 'first12=G.', 'last13=de Toureil', 'first13=R.', 'last14=Eeckhaudt', 'first14=S.', 'last15=G�rgen', 'first15=A.', 'last16=Grahn', 'first16=T.', 'last17=Gr�vy', 'first17=S.', 'last18=Hauschild', 'first18=K.', 'last19=Herzberg', 'first19=R. -D.', 'last20=Ikin', 'first20=P. J. C.', 'last21=Jones', 'first21=G. D.', 'last22=Jones', 'first22=P.', 'last23=Julin', 'first23=R.', 'last24=Juutinen', 'first24=S.', 'last25=Kettunen', 'first25=H.', 'last26=Korichi', 'first26=A.', 'last27=Korten', 'first27=W.', 'last28=Le Coz', 'first28=Y.', 'last29=Leino', 'first29=M.', 'last30=Lopez-Martens', 'first30=A.', 'last31=Lukyanov', 'first31=S. M.', 'last32=Penionzhkevich', 'first32=Yu. E.', 'last33=Perkowski', 'first33=J.', 'last34=Pritchard', 'first34=A.', 'last35=Rahkila', 'first35=P.', 'last36=Rejmund', 'first36=M.', 'last37=Saren', 'first37=J.', 'last38=Scholey', 'first38=C.', 'last39=Siem', 'first39=S.', 'last40=Saint-Laurent', 'first40=M. G.', 'last41=Simenel', 'first41=C.', 'last42=Sobolev', 'first42=Yu. G.', 'last43=Stodel', 'first43=Ch.', 'last44=Uusitalo', 'first44=J.', 'last45=Villari', 'first45=A.', 'last46=Bender', 'first46=M.', 'last47=Bonche', 'first47=P.', 'last48=Heenen', 'first48=P. -H.', 'title=Spectroscopy and single-particle structure of the odd- Z heavy elements 255Lr, 251Md and 247Es', 'journal=The European Physical Journal A - Hadrons and Nuclei', 'date=1 November 2006', 'volume=30', 'issue=2', 'pages=397�411', 'doi=10.1140/epja/i2006-10134-5', 'bibcode=2006EPJA...30..397C', 's2cid=123346991', 'url=https://link.springer.com/article/10.1140/epja/i2006-10134-5', 'access-date=3 July 2023', 'language=en', 'issn=1434-601X}}</ref>']},
    {nucleodeCount: '255m1', decayType: ['IT (~)']},
    {nucleodeCount: '255m1', decayType: ['a (~)']},
    {nucleodeCount: '255m2', decayType: ['IT']},
    {nucleodeCount: '255m3', decayType: ['IT']},
    {nucleodeCount: '256', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['b+']},
    {nucleodeCount: '257', decayType: ['a']},
    {nucleodeCount: '257', decayType: ['b+ (rare)']},
    {nucleodeCount: '257m', decayType: ['a']},
    {nucleodeCount: '257m', decayType: ['IT']},
    {nucleodeCount: '258', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['b+']},
    {nucleodeCount: '259', decayType: ['a']},
    {nucleodeCount: '259', decayType: ['b+ (rare)']},
    {nucleodeCount: '260', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['b+']},
    {nucleodeCount: '261', decayType: ['a<ref name=261-262>{{cite conference', 'last1=Hulet', 'first1=E. K.', 'title=New, heavy transuranium isotopes', 'date=22 October 1990', 'url=https://www.osti.gov/biblio/6028419', 'access-date=3 July 2023', 'publisher=Lawrence Livermore National Lab., CA (USA)', 'conference=Robert A. Welch Foundation conference on chemical research: fifty years with transuranium elements', 'osti=6028419', 'language=English}}</ref>']},
    {nucleodeCount: '262', decayType: ['b+']},
    {nucleodeCount: '262', decayType: ['a<ref name=261-262/>']},
]
