const lawrencium = [
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '251m', decayType: ['a']},
    {nucleodeCount: '252', decayType: ['a']},
    {nucleodeCount: '253', decayType: ['a']},
    {nucleodeCount: '253m', decayType: ['a']},
    {nucleodeCount: '254', decayType: ['a', 'b+']},
    {nucleodeCount: '254m', decayType: ['a']},
    {nucleodeCount: '255', decayType: ['a', 'b+']},
    {nucleodeCount: '255m1', decayType: ['IT', 'a']},
    {nucleodeCount: '255m2', decayType: ['IT']},
    {nucleodeCount: '255m3', decayType: ['IT']},
    {nucleodeCount: '256', decayType: ['a', 'b+']},
    {nucleodeCount: '257', decayType: ['a']},
    {nucleodeCount: '257m', decayType: ['a', 'IT']},
    {nucleodeCount: '258', decayType: ['a', 'b+']},
    {nucleodeCount: '259', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['a', 'b+']},
    {nucleodeCount: '261', decayType: ['a']},
    {nucleodeCount: '262', decayType: ['b+', 'a']}
]