const lead = [
    {nucleodeCount: '178', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '178', decayType: ['[[beta decay', 'b<sup>+</sup>]]?']},
    {nucleodeCount: '179', decayType: ['a']},
    {nucleodeCount: '180', decayType: ['a']},
    {nucleodeCount: '181', decayType: ['a']},
    {nucleodeCount: '181', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '182', decayType: ['a']},
    {nucleodeCount: '182', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '183', decayType: ['a']},
    {nucleodeCount: '183', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '183m', decayType: ['a']},
    {nucleodeCount: '183m', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '183m', decayType: ['[[isomeric transition', 'IT]]?']},
    {nucleodeCount: '184', decayType: ['a (80%)']},
    {nucleodeCount: '184', decayType: ['b<sup>+</sup>? (20%)']},
    {nucleodeCount: '185', decayType: ['b<sup>+</sup> (66%)']},
    {nucleodeCount: '185', decayType: ['a (34%)']},
    {nucleodeCount: '185m', decayType: ['a (50%)']},
    {nucleodeCount: '185m', decayType: ['b<sup>+</sup>? (50%)']},
    {nucleodeCount: '186', decayType: ['b<sup>+</sup>? (60%)']},
    {nucleodeCount: '186', decayType: ['a (40%)']},
    {nucleodeCount: '187', decayType: ['b<sup>+</sup> (90.5%)']},
    {nucleodeCount: '187', decayType: ['a (9.5%)']},
    {nucleodeCount: '187m', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '187m', decayType: ['a (12%)']},
    {nucleodeCount: '188', decayType: ['b<sup>+</sup> (91.5%)']},
    {nucleodeCount: '188', decayType: ['a (8.5%)']},
    {nucleodeCount: '188m1', decayType: ['IT']},
    {nucleodeCount: '188m2', decayType: ['IT']},
    {nucleodeCount: '188m3', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['b<sup>+</sup> (99.58%)']},
    {nucleodeCount: '189', decayType: ['a (0.42%)']},
    {nucleodeCount: '189m1', decayType: ['b<sup>+</sup> (99.6%)']},
    {nucleodeCount: '189m1', decayType: ['a (0.4%)']},
    {nucleodeCount: '189m1', decayType: ['IT?']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['b<sup>+</sup> (99.60%)']},
    {nucleodeCount: '190', decayType: ['a (0.40%)']},
    {nucleodeCount: '190m1', decayType: ['IT']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['IT']},
    {nucleodeCount: '191', decayType: ['b<sup>+</sup> (99.49%)']},
    {nucleodeCount: '191', decayType: ['a (0.51%)']},
    {nucleodeCount: '191m1', decayType: ['b<sup>+</sup> (99.98%)']},
    {nucleodeCount: '191m1', decayType: ['a (0.02%)']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b<sup>+</sup> (99.99%)']},
    {nucleodeCount: '192', decayType: ['a (0.0059%)']},
    {nucleodeCount: '192m1', decayType: ['IT']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '192m3', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '193m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '194', decayType: ['a (7.3x10<sup>-6</sup>%)']},
    {nucleodeCount: '194m1', decayType: ['IT']},
    {nucleodeCount: '194m2', decayType: ['IT']},
    {nucleodeCount: '195', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '195m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '195m1', decayType: ['IT?']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '195m3', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '196', decayType: ['a (<3x10<sup>-5</sup>%)']},
    {nucleodeCount: '196m1', decayType: ['IT']},
    {nucleodeCount: '196m2', decayType: ['IT']},
    {nucleodeCount: '197', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '197m1', decayType: ['b<sup>+</sup> (81%)']},
    {nucleodeCount: '197m1', decayType: ['IT (19%)']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '198m1', decayType: ['IT']},
    {nucleodeCount: '198m2', decayType: ['IT']},
    {nucleodeCount: '198m3', decayType: ['IT']},
    {nucleodeCount: '199', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '199m1', decayType: ['IT']},
    {nucleodeCount: '199m1', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '199m2', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '200m1', decayType: ['IT']},
    {nucleodeCount: '200m2', decayType: ['IT']},
    {nucleodeCount: '201', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '201m1', decayType: ['IT']},
    {nucleodeCount: '201m1', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '201m2', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['EC']},
    {nucleodeCount: '202m1', decayType: ['IT (90.5%)']},
    {nucleodeCount: '202m1', decayType: ['b<sup>+</sup> (9.5%)']},
    {nucleodeCount: '202m2', decayType: ['IT']},
    {nucleodeCount: '202m3', decayType: ['IT']},
    {nucleodeCount: '203', decayType: ['EC']},
    {nucleodeCount: '203m1', decayType: ['IT']},
    {nucleodeCount: '203m2', decayType: ['IT']},
    {nucleodeCount: '203m3', decayType: ['IT']},
    {nucleodeCount: '204m1', decayType: ['IT']},
    {nucleodeCount: '204m2', decayType: ['IT']},
    {nucleodeCount: '204m3', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['EC']},
    {nucleodeCount: '205m1', decayType: ['IT']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '205m3', decayType: ['IT']},
    {nucleodeCount: '206m1', decayType: ['IT']},
    {nucleodeCount: '206m2', decayType: ['IT']},
    {nucleodeCount: '207m', decayType: ['IT']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: '209', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '209', decayType: ['9/2+']},
    {nucleodeCount: '210', decayType: ['b<sup>-</sup> (100%)']},
    {nucleodeCount: '210', decayType: ['rowspan=2', '0+']},
    {nucleodeCount: '210', decayType: ['a (1.9x10<sup>-6</sup>%)']},
    {nucleodeCount: '210m1', decayType: ['IT']},
    {nucleodeCount: '210m2', decayType: ['IT']},
    {nucleodeCount: '211', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '211', decayType: ['9/2+']},
    {nucleodeCount: '211m', decayType: ['IT']},
    {nucleodeCount: '212', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '212', decayType: ['0+']},
    {nucleodeCount: '212m', decayType: ['IT']},
    {nucleodeCount: '213', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '213m', decayType: ['IT']},
    {nucleodeCount: '214', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '214m', decayType: ['IT']},
    {nucleodeCount: '215', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '216', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '216m', decayType: ['IT']},
    {nucleodeCount: '217', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '218', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '219', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '220', decayType: ['b<sup>-</sup>?']},
]
