const lead = [
    {nucleodeCount: '178', decayType: ['a', 'b+']},
    {nucleodeCount: '179', decayType: ['a']},
    {nucleodeCount: '180', decayType: ['a']},
    {nucleodeCount: '181', decayType: ['a', 'b+']},
    {nucleodeCount: '182', decayType: ['a', 'b+']},
    {nucleodeCount: '183', decayType: ['a', 'b+']},
    {nucleodeCount: '183m', decayType: ['a', 'b+', 'IT']},
    {nucleodeCount: '184', decayType: ['a', 'b+']},
    {nucleodeCount: '185', decayType: ['b+', 'a']},
    {nucleodeCount: '185m', decayType: ['a', 'b+']},
    {nucleodeCount: '186', decayType: ['b+', 'a']},
    {nucleodeCount: '187', decayType: ['b+', 'a']},
    {nucleodeCount: '187m', decayType: ['b+', 'a']},
    {nucleodeCount: '188', decayType: ['b+', 'a']},
    {nucleodeCount: '188m1', decayType: ['IT']},
    {nucleodeCount: '188m2', decayType: ['IT']},
    {nucleodeCount: '188m3', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['b+', 'a']},
    {nucleodeCount: '189m1', decayType: ['b+', 'a', 'IT']},
    {nucleodeCount: '189m2', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['b+', 'a']},
    {nucleodeCount: '190m1', decayType: ['IT']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '190m3', decayType: ['IT']},
    {nucleodeCount: '191', decayType: ['b+', 'a']},
    {nucleodeCount: '191m1', decayType: ['b+', 'a']},
    {nucleodeCount: '191m2', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['b+', 'a']},
    {nucleodeCount: '192m1', decayType: ['IT']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '192m3', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['b+']},
    {nucleodeCount: '193m1', decayType: ['b+']},
    {nucleodeCount: '193m2', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b+', 'a']},
    {nucleodeCount: '194m1', decayType: ['IT']},
    {nucleodeCount: '194m2', decayType: ['IT']},
    {nucleodeCount: '195', decayType: ['b+']},
    {nucleodeCount: '195m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '195m2', decayType: ['IT']},
    {nucleodeCount: '195m3', decayType: ['IT']},
    {nucleodeCount: '196', decayType: ['b+', 'a']},
    {nucleodeCount: '196m1', decayType: ['IT']},
    {nucleodeCount: '196m2', decayType: ['IT']},
    {nucleodeCount: '197', decayType: ['b+']},
    {nucleodeCount: '197m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '197m2', decayType: ['IT']},
    {nucleodeCount: '198', decayType: ['b+']},
    {nucleodeCount: '198m1', decayType: ['IT']},
    {nucleodeCount: '198m2', decayType: ['IT']},
    {nucleodeCount: '198m3', decayType: ['IT']},
    {nucleodeCount: '199', decayType: ['b+']},
    {nucleodeCount: '199m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '199m2', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['e']},
    {nucleodeCount: '200m1', decayType: ['IT']},
    {nucleodeCount: '200m2', decayType: ['IT']},
    {nucleodeCount: '201', decayType: ['b+']},
    {nucleodeCount: '201m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '201m2', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['e']},
    {nucleodeCount: '202m1', decayType: ['IT', 'b+']},
    {nucleodeCount: '202m2', decayType: ['IT']},
    {nucleodeCount: '202m3', decayType: ['IT']},
    {nucleodeCount: '203', decayType: ['e']},
    {nucleodeCount: '203m1', decayType: ['IT']},
    {nucleodeCount: '203m2', decayType: ['IT']},
    {nucleodeCount: '203m3', decayType: ['IT']},
    {nucleodeCount: '204', decayType: ['Stable']},
    {nucleodeCount: '204m1', decayType: ['IT']},
    {nucleodeCount: '204m2', decayType: ['IT']},
    {nucleodeCount: '204m3', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['e']},
    {nucleodeCount: '205m1', decayType: ['IT']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '205m3', decayType: ['IT']},
    {nucleodeCount: '206', decayType: ['Stable']},
    {nucleodeCount: '206m1', decayType: ['IT']},
    {nucleodeCount: '206m2', decayType: ['IT']},
    {nucleodeCount: '207', decayType: ['Stable']},
    {nucleodeCount: '207m', decayType: ['IT']},
    {nucleodeCount: '208', decayType: ['Stable']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: '209', decayType: ['b-']},
    {nucleodeCount: '210', decayType: ['b-', 'a']},
    {nucleodeCount: '210m1', decayType: ['IT']},
    {nucleodeCount: '210m2', decayType: ['IT']},
    {nucleodeCount: '211', decayType: ['b-']},
    {nucleodeCount: '211m', decayType: ['IT']},
    {nucleodeCount: '212', decayType: ['b-']},
    {nucleodeCount: '212m', decayType: ['IT']},
    {nucleodeCount: '213', decayType: ['b-']},
    {nucleodeCount: '213m', decayType: ['IT']},
    {nucleodeCount: '214', decayType: ['b-']},
    {nucleodeCount: '214m', decayType: ['IT']},
    {nucleodeCount: '215', decayType: ['b-']},
    {nucleodeCount: '216', decayType: ['b-']},
    {nucleodeCount: '216m', decayType: ['IT']},
    {nucleodeCount: '217', decayType: ['b-']},
    {nucleodeCount: '218', decayType: ['b-']},
    {nucleodeCount: '219', decayType: ['b-']},
    {nucleodeCount: '220', decayType: ['b-']}
]