const lutetium = [
    {nucleodeCount: '149', decayType: ['p']},
    {nucleodeCount: '150', decayType: ['p']},
    {nucleodeCount: '150m', decayType: ['p']},
    {nucleodeCount: '151', decayType: ['p', 'b+']},
    {nucleodeCount: '151m', decayType: ['p']},
    {nucleodeCount: '152', decayType: ['b+', 'b+, p']},
    {nucleodeCount: '153', decayType: ['a', 'b+']},
    {nucleodeCount: '153m1', decayType: ['IT']},
    {nucleodeCount: '153m2', decayType: ['IT']},
    {nucleodeCount: '153m3', decayType: ['IT']},
    {nucleodeCount: '154m1', decayType: ['b+', 'b+, p', 'b+, a']},
    {nucleodeCount: '154m2', decayType: ['IT']},
    {nucleodeCount: '155', decayType: ['a', 'b+']},
    {nucleodeCount: '155m1', decayType: ['a', 'b+']},
    {nucleodeCount: '155m2', decayType: ['a']},
    {nucleodeCount: '156', decayType: ['a']},
    {nucleodeCount: '156m1', decayType: ['a']},
    {nucleodeCount: '156m2', decayType: ['IT']},
    {nucleodeCount: '157', decayType: ['b+', 'a']},
    {nucleodeCount: '157m', decayType: ['b+', 'a']},
    {nucleodeCount: '158', decayType: ['b+', 'a']},
    {nucleodeCount: '159', decayType: ['b+', 'a']},
    {nucleodeCount: '160', decayType: ['b+']},
    {nucleodeCount: '160m', decayType: ['b+']},
    {nucleodeCount: '161', decayType: ['b+']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b+']},
    {nucleodeCount: '162m1', decayType: ['b+']},
    {nucleodeCount: '163', decayType: ['b+']},
    {nucleodeCount: '164', decayType: ['b+']},
    {nucleodeCount: '165', decayType: ['b+']},
    {nucleodeCount: '166', decayType: ['b+']},
    {nucleodeCount: '166m1', decayType: ['b+', 'IT']},
    {nucleodeCount: '166m2', decayType: ['b+', 'IT']},
    {nucleodeCount: '167', decayType: ['b+']},
    {nucleodeCount: '168', decayType: ['b+']},
    {nucleodeCount: '168m', decayType: ['b+']},
    {nucleodeCount: '169', decayType: ['b+']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['b+']},
    {nucleodeCount: '170m', decayType: ['IT']},
    {nucleodeCount: '171', decayType: ['b+']},
    {nucleodeCount: '171m', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['b+']},
    {nucleodeCount: '172m1', decayType: ['IT']},
    {nucleodeCount: '172m2', decayType: ['IT']},
    {nucleodeCount: '172m3', decayType: ['IT']},
    {nucleodeCount: '172m4', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['e']},
    {nucleodeCount: '173m', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['b+']},
    {nucleodeCount: '174m1', decayType: ['IT', 'e']},
    {nucleodeCount: '174m2', decayType: ['IT']},
    {nucleodeCount: '174m3', decayType: ['IT']},
    {nucleodeCount: '174m4', decayType: ['IT']},
    {nucleodeCount: '174m5', decayType: ['IT']},
    {nucleodeCount: '174m6', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['Stable']},
    {nucleodeCount: '175m1', decayType: ['IT']},
    {nucleodeCount: '175m2', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['b-']},
    {nucleodeCount: '176m1', decayType: ['b-', 'e']},
    {nucleodeCount: '176m2', decayType: ['IT']},
    {nucleodeCount: '176m3', decayType: ['IT']},
    {nucleodeCount: '177', decayType: ['b-']},
    {nucleodeCount: '177m1', decayType: ['IT']},
    {nucleodeCount: '177m2', decayType: ['IT']},
    {nucleodeCount: '177m3', decayType: ['b-', 'IT']},
    {nucleodeCount: '177m4', decayType: ['IT']},
    {nucleodeCount: '177m5', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['b-']},
    {nucleodeCount: '178m', decayType: ['b-']},
    {nucleodeCount: '179', decayType: ['b-']},
    {nucleodeCount: '179m', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['b-']},
    {nucleodeCount: '180m2', decayType: ['IT']},
    {nucleodeCount: '181', decayType: ['b-']},
    {nucleodeCount: '182', decayType: ['b-']},
    {nucleodeCount: '183', decayType: ['b-']},
    {nucleodeCount: '184', decayType: ['b-']}
]