const mendelevium = [
    {nucleodeCount: '244', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '244m', decayType: ['IT']},
    {nucleodeCount: '245', decayType: ['a']},
    {nucleodeCount: '246', decayType: ['a']},
    {nucleodeCount: '246m', decayType: ['b<sup>+</sup> (~67%)']},
    {nucleodeCount: '246m', decayType: ['a (<23%)']},
    {nucleodeCount: '247', decayType: ['a (99.14%)']},
    {nucleodeCount: '247m', decayType: ['a (80%)']},
    {nucleodeCount: '248', decayType: ['b<sup>+</sup> (80%)']},
    {nucleodeCount: '248', decayType: ['a (20%)']},
    {nucleodeCount: '249', decayType: ['a (75%)']},
    {nucleodeCount: '249', decayType: ['b<sup>+</sup> (25%)']},
    {nucleodeCount: '249m', decayType: ['a']},
    {nucleodeCount: '250', decayType: ['b<sup>+</sup> (93.0%)']},
    {nucleodeCount: '250', decayType: ['a (7.0%)']},
    {nucleodeCount: '250m', decayType: ['a']},
    {nucleodeCount: '251', decayType: ['b<sup>+</sup> (90%)']},
    {nucleodeCount: '251', decayType: ['a (10%)']},
    {nucleodeCount: '252', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '253', decayType: ['b<sup>+</sup> (~99.3%)']},
    {nucleodeCount: '253', decayType: ['a (~0.7%)']},
    {nucleodeCount: '254', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '254m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '255', decayType: ['b<sup>+</sup> (93%)']},
    {nucleodeCount: '255', decayType: ['a (7%)']},
    {nucleodeCount: '256', decayType: ['b<sup>+</sup> (90.8%)']},
    {nucleodeCount: '256', decayType: ['a (9.2%)']},
    {nucleodeCount: '257', decayType: ['[[Electron capture', 'EC]] (85%)']},
    {nucleodeCount: '257', decayType: ['a (15%)']},
    {nucleodeCount: '258', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['b<sup>-</sup> (<0.0015%)']},
    {nucleodeCount: '258', decayType: ['b<sup>+</sup> (<0.0015%)']},
    {nucleodeCount: '258m', decayType: ['EC (85%)']},
    {nucleodeCount: '258m', decayType: ['a (<1.2%)']},
    {nucleodeCount: '260', decayType: ['a (<5%)']},
    {nucleodeCount: '260', decayType: ['EC (<5%)']},
    {nucleodeCount: '260', decayType: ['b<sup>-</sup> (<3.5%)']},
]
