const mendelevium = [
    {nucleodeCount: '244', decayType: ['a']},
    {nucleodeCount: '244m', decayType: ['IT']},
    {nucleodeCount: '245', decayType: ['a']},
    {nucleodeCount: '246', decayType: ['a']},
    {nucleodeCount: '246m', decayType: ['b+ (~)']},
    {nucleodeCount: '246m', decayType: ['a']},
    {nucleodeCount: '247', decayType: ['a']},
    {nucleodeCount: '247m', decayType: ['a']},
    {nucleodeCount: '248', decayType: ['b+']},
    {nucleodeCount: '248', decayType: ['a']},
    {nucleodeCount: '249', decayType: ['a']},
    {nucleodeCount: '249', decayType: ['b+']},
    {nucleodeCount: '249m', decayType: ['a']},
    {nucleodeCount: '250', decayType: ['b+']},
    {nucleodeCount: '250', decayType: ['a']},
    {nucleodeCount: '250m', decayType: ['a']},
    {nucleodeCount: '251', decayType: ['b+']},
    {nucleodeCount: '251', decayType: ['a']},
    {nucleodeCount: '252', decayType: ['b+']},
    {nucleodeCount: '253', decayType: ['b+ (~)']},
    {nucleodeCount: '253', decayType: ['a (~)']},
    {nucleodeCount: '254', decayType: ['b+']},
    {nucleodeCount: '254m', decayType: ['b+']},
    {nucleodeCount: '255', decayType: ['b+']},
    {nucleodeCount: '255', decayType: ['a']},
    {nucleodeCount: '256', decayType: ['b+']},
    {nucleodeCount: '256', decayType: ['a']},
    {nucleodeCount: '257', decayType: ['EC']},
    {nucleodeCount: '257', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['a']},
    {nucleodeCount: '258', decayType: ['b-']},
    {nucleodeCount: '258', decayType: ['b+']},
    {nucleodeCount: '258m', decayType: ['EC']},
    {nucleodeCount: '258m', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['a']},
    {nucleodeCount: '260', decayType: ['EC']},
    {nucleodeCount: '260', decayType: ['b-']},
]
