const mercury = [
    {nucleodeCount: '170', decayType: ['a']},
    {nucleodeCount: '171', decayType: ['a']},
    {nucleodeCount: '172', decayType: ['a']},
    {nucleodeCount: '173', decayType: ['a']},
    {nucleodeCount: '174', decayType: ['a']},
    {nucleodeCount: '175', decayType: ['a']},
    {nucleodeCount: '175m', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['a']},
    {nucleodeCount: '176', decayType: ['b+']},
    {nucleodeCount: '177', decayType: ['a']},
    {nucleodeCount: '177m', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['a']},
    {nucleodeCount: '178', decayType: ['b+']},
    {nucleodeCount: '179', decayType: ['a']},
    {nucleodeCount: '179', decayType: ['b+']},
    {nucleodeCount: '179', decayType: ['b+, p']},
    {nucleodeCount: '179m', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['b+']},
    {nucleodeCount: '180', decayType: ['a']},
    {nucleodeCount: '181', decayType: ['b+']},
    {nucleodeCount: '181', decayType: ['a']},
    {nucleodeCount: '181', decayType: ['b+, p']},
    {nucleodeCount: '181', decayType: ['b+, a (9x10<sup>-6</sup)']},
    {nucleodeCount: '181m', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['b+']},
    {nucleodeCount: '182', decayType: ['a']},
    {nucleodeCount: '182', decayType: ['b+, p (<1x10<sup>-5</sup)']},
    {nucleodeCount: '183', decayType: ['b+']},
    {nucleodeCount: '183', decayType: ['a']},
    {nucleodeCount: '183', decayType: ['b+, p (2.6x10<sup>-4</sup)']},
    {nucleodeCount: '184', decayType: ['b+']},
    {nucleodeCount: '184', decayType: ['a']},
    {nucleodeCount: '185', decayType: ['b+']},
    {nucleodeCount: '185', decayType: ['a']},
    {nucleodeCount: '185m', decayType: ['IT']},
    {nucleodeCount: '185m', decayType: ['b+']},
    {nucleodeCount: '185m', decayType: ['a']},
    {nucleodeCount: '186', decayType: ['b+']},
    {nucleodeCount: '186', decayType: ['a']},
    {nucleodeCount: '186m', decayType: ['IT']},
    {nucleodeCount: '187', decayType: ['b+']},
    {nucleodeCount: '187m', decayType: ['b+']},
    {nucleodeCount: '188', decayType: ['b+']},
    {nucleodeCount: '188', decayType: ['a (3.7x10<sup>-5</sup)']},
    {nucleodeCount: '188m', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['b+']},
    {nucleodeCount: '189m', decayType: ['b+']},
    {nucleodeCount: '190', decayType: ['b+']},
    {nucleodeCount: '191', decayType: ['b+']},
    {nucleodeCount: '191m', decayType: ['b+']},
    {nucleodeCount: '192', decayType: ['EC']},
    {nucleodeCount: '193', decayType: ['b+']},
    {nucleodeCount: '193m', decayType: ['b+']},
    {nucleodeCount: '193m', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['EC']},
    {nucleodeCount: '195', decayType: ['b+']},
    {nucleodeCount: '195m', decayType: ['IT']},
    {nucleodeCount: '195m', decayType: ['b+']},
    {nucleodeCount: '196', decayType: ['195.965833(3)']},
    {nucleodeCount: '197', decayType: ['EC']},
    {nucleodeCount: '197m', decayType: ['IT']},
    {nucleodeCount: '197m', decayType: ['EC']},
    {nucleodeCount: '198', decayType: ['197.9667692(5)']},
    {nucleodeCount: '199', decayType: ['198.9682810(6)']},
    {nucleodeCount: '199m', decayType: ['IT']},
    {nucleodeCount: '200', decayType: ['199.9683269(6)']},
    {nucleodeCount: '201', decayType: ['200.9703031(8)']},
    {nucleodeCount: '201m', decayType: ['IT']},
    {nucleodeCount: '202', decayType: ['201.9706436(8)']},
    {nucleodeCount: '203', decayType: ['b-']},
    {nucleodeCount: '203m1', decayType: ['IT']},
    {nucleodeCount: '203m2', decayType: ['IT']},
    {nucleodeCount: '204', decayType: ['203.9734940(5)']},
    {nucleodeCount: '204m', decayType: ['IT']},
    {nucleodeCount: '205', decayType: ['b-']},
    {nucleodeCount: '205m1', decayType: ['IT']},
    {nucleodeCount: '205m2', decayType: ['IT']},
    {nucleodeCount: '206', decayType: ['b-']},
    {nucleodeCount: '206', decayType: ['0+']},
    {nucleodeCount: '206m1', decayType: ['IT']},
    {nucleodeCount: '206m2', decayType: ['IT']},
    {nucleodeCount: '207', decayType: ['b-']},
    {nucleodeCount: '208', decayType: ['b-']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: '209', decayType: ['b-']},
    {nucleodeCount: '210', decayType: ['b-']},
    {nucleodeCount: '210', decayType: ['b-, n']},
    {nucleodeCount: '210m1', decayType: ['IT']},
    {nucleodeCount: '210m2', decayType: ['IT']},
    {nucleodeCount: '211', decayType: ['b-']},
    {nucleodeCount: '211', decayType: ['b-, n']},
]
