const molybdenum = [
    {nucleodeCount: '81', decayType: ['[[beta decay', 'b<sup>+</sup>]]?']},
    {nucleodeCount: '81', decayType: ['b<sup>+</sup>, [[proton emission', 'p]]?']},
    {nucleodeCount: '82', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '82', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '83', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '83', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '84', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '84', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '85', decayType: ['b<sup>+</sup> (99.86%)']},
    {nucleodeCount: '85', decayType: ['b<sup>+</sup>, p (0.14%)']},
    {nucleodeCount: '86', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '87', decayType: ['b<sup>+</sup> (85%)']},
    {nucleodeCount: '87', decayType: ['b<sup>+</sup>, p (15%)']},
    {nucleodeCount: '88', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '89', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '89m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '90', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '90m', decayType: ['IT']},
    {nucleodeCount: '91', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '91m', decayType: ['IT (50.0%)']},
    {nucleodeCount: '91m', decayType: ['b<sup>+</sup> (50.0%)']},
    {nucleodeCount: '92', decayType: ['91.90680715(17)']},
    {nucleodeCount: '92m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['[[electron capture', 'EC]] (95.7%)']},
    {nucleodeCount: '93', decayType: ['EC (4.3%)']},
    {nucleodeCount: '93m1', decayType: ['IT (99.88%)']},
    {nucleodeCount: '93m1', decayType: ['b<sup>+</sup> (0.12%)']},
    {nucleodeCount: '93m2', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['97.90540361(19)']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '99m1', decayType: ['IT']},
    {nucleodeCount: '99m2', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>b<sup>-</sup>']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '101m1', decayType: ['IT']},
    {nucleodeCount: '101m2', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '107m', decayType: ['IT']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup> (>99.5%)']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (<0.5%)']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup> (98.7%)']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>, n (1.3%)']},
    {nucleodeCount: '109m', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b<sup>-</sup> (98.0%)']},
    {nucleodeCount: '110', decayType: ['b<sup>-</sup>, n (2.0%)']},
    {nucleodeCount: '111', decayType: ['b<sup>-</sup> (>88%)']},
    {nucleodeCount: '111', decayType: ['b<sup>-</sup>, n (<12%)']},
    {nucleodeCount: '111m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '111m', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '112', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '112', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '113', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '113', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '114', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '114', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '115', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '115', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '115', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '116', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '116', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '116', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '117', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '117', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '117', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '118', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '118', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '118', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '119', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '119', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '119', decayType: ['b<sup>-</sup>, 2n?']},
]
