const neodymium = [
    {nucleodeCount: '125', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '125', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (?%)']},
    {nucleodeCount: '127', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '127', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '129', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '129', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '129m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '129m1', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '129m2', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '129m2', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '129m3', decayType: ['[[isomeric transition', 'IT]] (?%)']},
    {nucleodeCount: '129m3', decayType: ['IT (?%)']},
    {nucleodeCount: '129m4', decayType: ['IT']},
    {nucleodeCount: '129m5', decayType: ['IT']},
    {nucleodeCount: '129m6', decayType: ['IT']},
    {nucleodeCount: '130', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '131', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '131', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '132', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '133', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '133m1', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '133m1', decayType: ['IT (?%)']},
    {nucleodeCount: '133m2', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '135m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '136', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '137', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '137m', decayType: ['IT']},
    {nucleodeCount: '138', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '138m', decayType: ['IT']},
    {nucleodeCount: '139', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139m1', decayType: ['b<sup>+</sup> (87.0%)']},
    {nucleodeCount: '139m1', decayType: ['IT (13.0%)']},
    {nucleodeCount: '139m2', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '140m1', decayType: ['IT']},
    {nucleodeCount: '140m2', decayType: ['IT']},
    {nucleodeCount: '141', decayType: ['EC (97.28%)']},
    {nucleodeCount: '141m', decayType: ['IT (99.97%)']},
    {nucleodeCount: '141m', decayType: ['b<sup>+</sup> (0.032%)']},
    {nucleodeCount: '143', decayType: ['142.9098198(13)']},
    {nucleodeCount: '144', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '145', decayType: ['144.9125792(14)']},
    {nucleodeCount: '146', decayType: ['145.9131225(14)']},
    {nucleodeCount: '147', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '148', decayType: ['147.9168990(22)']},
    {nucleodeCount: '149', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '150', decayType: ['b<sup>-</sup>b<sup>-</sup>']},
    {nucleodeCount: '151', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '152', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '153', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '153m', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '154m', decayType: ['IT']},
    {nucleodeCount: '155', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '156', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '156m', decayType: ['IT']},
    {nucleodeCount: '157', decayType: ['156.9393511(23)']},
    {nucleodeCount: '157', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '158', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '158m', decayType: ['IT']},
    {nucleodeCount: '159', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '160', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '160m', decayType: ['IT']},
    {nucleodeCount: '161', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '162', decayType: ['b<sup>-</sup>']},
]
