const neon = [
    {nucleodeCount: '15', decayType: ['2p']},
    {nucleodeCount: '16', decayType: ['2p']},
    {nucleodeCount: '17', decayType: ['[[Proton emission', 'b+p]] ({{val', '94.4', '(2.9)', 'u=}})']},
    {nucleodeCount: '17', decayType: ['b+a ({{val', '3.51', '(1)', 'u=}})']},
    {nucleodeCount: '17', decayType: ['b+ ({{val', '2.1', '(2.9)', 'u=}})']},
    {nucleodeCount: '17', decayType: ['b+pa ({{val', '0.014', '(4)', 'u=}})']},
    {nucleodeCount: '18', decayType: ['b+']},
    {nucleodeCount: '19', decayType: ['b+']},
    {nucleodeCount: '23', decayType: ['b-']},
    {nucleodeCount: '24', decayType: ['b-']},
    {nucleodeCount: '25', decayType: ['b-']},
    {nucleodeCount: '26', decayType: ['b- ({{val', '99.87', '(3)', 'u=}})']},
    {nucleodeCount: '26', decayType: ['[[Neutron emission', 'b-n]] ({{val', '0.13', '(3)', 'u=}})']},
    {nucleodeCount: '27', decayType: ['b- ({{val', '98.0', '(5)', 'u=}})']},
    {nucleodeCount: '27', decayType: ['b-n ({{val', '2.0', '(5)', 'u=}})']},
    {nucleodeCount: '27', decayType: ['b-2n <ref group="n" name="decay mode 1">Decay mode shown is energetically allowed, but has not been experimentally observed to occur in this nuclide.</ref>']},
    {nucleodeCount: '28', decayType: ['b- ({{val', '84.3', '(1.1)', 'u=}})']},
    {nucleodeCount: '28', decayType: ['b-n ({{val', '12', '(1)', 'u=}})']},
    {nucleodeCount: '28', decayType: ['b-2n ({{val', '3.7', '(5)', 'u=}})']},
    {nucleodeCount: '29', decayType: ['b- ({{val', '68.0', '(5.1)', 'u=}})']},
    {nucleodeCount: '29', decayType: ['b-n ({{val', '28', '(5)', 'u=}})']},
    {nucleodeCount: '29', decayType: ['b-2n ({{val', '4', '(1)', 'u=}})']},
    {nucleodeCount: '30', decayType: ['b- ({{val', '78.1', '(4.6)', 'u=}})']},
    {nucleodeCount: '30', decayType: ['b-n ({{val', '13', '(4)', 'u=}})']},
    {nucleodeCount: '30', decayType: ['b-2n ({{val', '8.9', '(2.3)', 'u=}})']},
    {nucleodeCount: '31', decayType: ['b-']},
    {nucleodeCount: '31', decayType: ['b-n <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '31', decayType: ['b-2n <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '32', decayType: ['b-']},
    {nucleodeCount: '32', decayType: ['b-n <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '32', decayType: ['b-2n <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '34', decayType: ['b- <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '34', decayType: ['b-2n <ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '34', decayType: ['b-n <ref group="n" name="decay mode 1" />']},
]
