const nickel = [
    {nucleodeCount: '48', decayType: ['2p']},
    {nucleodeCount: '48', decayType: ['b+']},
    {nucleodeCount: '48', decayType: ['b+, p']},
    {nucleodeCount: '49', decayType: ['b+, p']},
    {nucleodeCount: '49', decayType: ['b+']},
    {nucleodeCount: '50', decayType: ['b+, p']},
    {nucleodeCount: '50', decayType: ['b+, 2p']},
    {nucleodeCount: '50', decayType: ['b+']},
    {nucleodeCount: '51', decayType: ['b+, p']},
    {nucleodeCount: '51', decayType: ['b+']},
    {nucleodeCount: '51', decayType: ['b+, 2p']},
    {nucleodeCount: '52', decayType: ['b+']},
    {nucleodeCount: '52', decayType: ['b+, p']},
    {nucleodeCount: '53', decayType: ['b+']},
    {nucleodeCount: '53', decayType: ['b+, p']},
    {nucleodeCount: '54', decayType: ['b+']},
    {nucleodeCount: '54', decayType: ['b+, p']},
    {nucleodeCount: '54', decayType: ['IT']},
    {nucleodeCount: '54', decayType: ['p']},
    {nucleodeCount: '55', decayType: ['b+']},
    {nucleodeCount: '56', decayType: ['EC']},
    {nucleodeCount: '56', decayType: ['b+ (<{{val', '5.8e-5}})<ref>{{cite journal', 'last1=Sur', 'first1=Bhaskar', 'last2=Norman', 'first2=Eric B.', 'last3=Lesko', 'first3=K. T.', 'last4=Browne', 'first4=Edgardo', 'last5=Larimer', 'first5=Ruth-Mary', 'title=Reinvestigation of Ni 56 decay', 'journal=Physical Review C', 'date=1 August 1990', 'volume=42', 'issue=2', 'pages=573�580', 'doi=10.1103/PhysRevC.42.573}}</ref>']},
    {nucleodeCount: '57', decayType: ['b+']},
    {nucleodeCount: '59', decayType: ['EC']},
    {nucleodeCount: '63', decayType: ['b-']},
    {nucleodeCount: '63', decayType: ['IT']},
    {nucleodeCount: '65', decayType: ['b-']},
    {nucleodeCount: '65', decayType: ['IT']},
    {nucleodeCount: '66', decayType: ['b-']},
    {nucleodeCount: '67', decayType: ['b-']},
    {nucleodeCount: '67', decayType: ['IT']},
    {nucleodeCount: '67', decayType: ['IT']},
    {nucleodeCount: '68', decayType: ['b-']},
    {nucleodeCount: '68', decayType: ['IT']},
    {nucleodeCount: '68', decayType: ['IT']},
    {nucleodeCount: '69', decayType: ['b-']},
    {nucleodeCount: '69', decayType: ['b-']},
    {nucleodeCount: '69', decayType: ['IT']},
    {nucleodeCount: '69', decayType: ['IT']},
    {nucleodeCount: '70', decayType: ['b-']},
    {nucleodeCount: '70', decayType: ['IT']},
    {nucleodeCount: '71', decayType: ['b-']},
    {nucleodeCount: '71', decayType: ['b-']},
    {nucleodeCount: '72', decayType: ['b-']},
    {nucleodeCount: '72', decayType: ['b-, n']},
    {nucleodeCount: '73', decayType: ['b-']},
    {nucleodeCount: '73', decayType: ['b-, n']},
    {nucleodeCount: '74', decayType: ['b-']},
    {nucleodeCount: '74', decayType: ['b-, n']},
    {nucleodeCount: '75', decayType: ['b-']},
    {nucleodeCount: '75', decayType: ['b-, n']},
    {nucleodeCount: '76', decayType: ['b-']},
    {nucleodeCount: '76', decayType: ['b-, n']},
    {nucleodeCount: '76', decayType: ['IT']},
    {nucleodeCount: '77', decayType: ['b-']},
    {nucleodeCount: '77', decayType: ['b-, n']},
    {nucleodeCount: '77', decayType: ['b-, 2n']},
    {nucleodeCount: '78', decayType: ['b-']},
    {nucleodeCount: '78', decayType: ['b-, n']},
    {nucleodeCount: '78', decayType: ['b-, 2n']},
    {nucleodeCount: '79', decayType: ['b-']},
    {nucleodeCount: '79', decayType: ['b-, n']},
    {nucleodeCount: '79', decayType: ['b-, 2n']},
    {nucleodeCount: '80', decayType: ['b-']},
    {nucleodeCount: '80', decayType: ['b-, n']},
    {nucleodeCount: '80', decayType: ['b-, 2n']},
    {nucleodeCount: '81', decayType: ['b-']},
    {nucleodeCount: '82', decayType: ['b-']},
]
