const niobium = [
    {nucleodeCount: '82', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '82m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '83', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '84', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '84m1', decayType: ['IT']},
    {nucleodeCount: '84m2', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '85m', decayType: ['IT (?%)']},
    {nucleodeCount: '85m', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '86', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '86m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '87', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '87m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '88', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '88m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '89', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '89m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '90', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '90m1', decayType: ['IT']},
    {nucleodeCount: '90m2', decayType: ['IT']},
    {nucleodeCount: '90m3', decayType: ['IT']},
    {nucleodeCount: '90m4', decayType: ['IT']},
    {nucleodeCount: '90m5', decayType: ['IT']},
    {nucleodeCount: '91', decayType: ['[[Electron capture', 'EC]] (99.99%)']},
    {nucleodeCount: '91m1', decayType: ['IT (96.6%)']},
    {nucleodeCount: '91m1', decayType: ['EC (3.4%)']},
    {nucleodeCount: '91m2', decayType: ['IT']},
    {nucleodeCount: '92', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '92m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '92m2', decayType: ['IT']},
    {nucleodeCount: '92m3', decayType: ['IT']},
    {nucleodeCount: '93m1', decayType: ['IT']},
    {nucleodeCount: '93m2', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '94m', decayType: ['IT (99.50%)']},
    {nucleodeCount: '94m', decayType: ['b<sup>-</sup> (0.50%)']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '95m', decayType: ['IT (94.4%)']},
    {nucleodeCount: '95m', decayType: ['b<sup>-</sup> (5.6%)']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '98m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '99m', decayType: ['b<sup>-</sup> (?%)']},
    {nucleodeCount: '99m', decayType: ['IT (?%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '100m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '100m2', decayType: ['IT']},
    {nucleodeCount: '100m3', decayType: ['IT']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '102m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup> (99.95%)']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (0.05%)']},
    {nucleodeCount: '104m', decayType: ['b<sup>-</sup> (99.94%)']},
    {nucleodeCount: '104m', decayType: ['b<sup>-</sup>, n (0.06%)']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup> (98.3%)']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>, n (1.7%)']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup> (95.5%)']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>, n (4.5%)']},
    {nucleodeCount: '106m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '106m2', decayType: ['IT']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup> (92.6%)']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>, n (7.4%)']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup> (93.7%)']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup>, n (6.3%)']},
    {nucleodeCount: '108m', decayType: ['IT']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup> (69%)']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>, n (31%)']},
    {nucleodeCount: '109m', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b<sup>-</sup> (60%)']},
    {nucleodeCount: '110', decayType: ['b<sup>-</sup>, n (40%)']},
    {nucleodeCount: '110m', decayType: ['b<sup>-</sup> (60%)']},
    {nucleodeCount: '110m', decayType: ['b<sup>-</sup>, n (40%)']},
    {nucleodeCount: '111', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '112', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '113', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '114', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '115', decayType: ['b<sup>-</sup>']},
]
