const nobelium = [
    {nucleodeCount: '249', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '250', decayType: ['a (rare)']},
    {nucleodeCount: '250m1', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '250m2', decayType: ['IT']},
    {nucleodeCount: '251', decayType: ['a (91%)<ref name=Hes01/>']},
    {nucleodeCount: '251', decayType: ['[[beta decay', 'b<sup>+</sup>]] (9%)']},
    {nucleodeCount: '251m1', decayType: ['a']},
    {nucleodeCount: '251m1', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '251m2', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['a (70.1%)']},
    {nucleodeCount: 'None', decayType: ['b<sup>+</sup> (0.8%)']},
    {nucleodeCount: '252m1', decayType: ['IT']},
    {nucleodeCount: '252m2', decayType: ['IT']},
    {nucleodeCount: '253', decayType: ['a (55%)']},
    {nucleodeCount: '253', decayType: ['b<sup>+</sup> (45%)']},
    {nucleodeCount: '253m1', decayType: ['IT']},
    {nucleodeCount: '253m2', decayType: ['IT']},
    {nucleodeCount: '253m3', decayType: ['IT']},
    {nucleodeCount: '254', decayType: ['a (90%)']},
    {nucleodeCount: '254', decayType: ['b<sup>+</sup> (10%)']},
    {nucleodeCount: '254m1', decayType: ['IT (98.0%)']},
    {nucleodeCount: '254m1', decayType: ['a (<1%)']},
    {nucleodeCount: '254m2', decayType: ['IT']},
    {nucleodeCount: '255', decayType: ['a (61.4%)']},
    {nucleodeCount: '255', decayType: ['b<sup>+</sup> (38.6%)']},
    {nucleodeCount: '255m1', decayType: ['IT']},
    {nucleodeCount: '255m2', decayType: ['IT']},
    {nucleodeCount: '255m3', decayType: ['IT']},
    {nucleodeCount: '256', decayType: ['a (99.47%)']},
    {nucleodeCount: '256', decayType: ['[[Electron capture', 'EC]] (rare)']},
    {nucleodeCount: '256m', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['b<sup>+</sup> (rare)']},
    {nucleodeCount: '258', decayType: ['a (rare)']},
    {nucleodeCount: '259', decayType: ['a (75%)']},
    {nucleodeCount: '259', decayType: ['EC (25%)']},
    {nucleodeCount: '260', decayType: ['<!--', '-']},
    {nucleodeCount: 'None', decayType: ['<!--', '-']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: '264', decayType: ['a']},
]
