const osmium = [
    {nucleodeCount: 'None', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '160m', decayType: ['a']},
    {nucleodeCount: '161', decayType: ['a']},
    {nucleodeCount: '162', decayType: ['a']},
    {nucleodeCount: '163', decayType: ['a']},
    {nucleodeCount: '163', decayType: ['b<sup>+</sup> ?']},
    {nucleodeCount: '164', decayType: ['a (96%)']},
    {nucleodeCount: '164', decayType: ['b<sup>+</sup> (4%)']},
    {nucleodeCount: '165', decayType: ['a (90%)']},
    {nucleodeCount: '165', decayType: ['b<sup>+</sup> (10%)']},
    {nucleodeCount: '166', decayType: ['a (83%)']},
    {nucleodeCount: '166', decayType: ['b<sup>+</sup> (17%)']},
    {nucleodeCount: '167', decayType: ['a (51%)']},
    {nucleodeCount: '167', decayType: ['b<sup>+</sup> (49%)']},
    {nucleodeCount: '167m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '168', decayType: ['b<sup>+</sup> (57%)']},
    {nucleodeCount: '168', decayType: ['a (43%)']},
    {nucleodeCount: '169', decayType: ['b<sup>+</sup> (86.3%)']},
    {nucleodeCount: '169', decayType: ['a (13.7%)']},
    {nucleodeCount: '170', decayType: ['b<sup>+</sup> (90.5%)']},
    {nucleodeCount: '170', decayType: ['a (9.5%)']},
    {nucleodeCount: '171', decayType: ['b<sup>+</sup> (98.20%)']},
    {nucleodeCount: '171', decayType: ['a (1.80%)']},
    {nucleodeCount: '172', decayType: ['b<sup>+</sup> (98.81%)']},
    {nucleodeCount: '172', decayType: ['a (1.19%)']},
    {nucleodeCount: '173', decayType: ['b<sup>+</sup> (99.6%)']},
    {nucleodeCount: '173', decayType: ['a (0.4%)']},
    {nucleodeCount: '174', decayType: ['b<sup>+</sup> (99.98%)']},
    {nucleodeCount: '174', decayType: ['a (.024%)']},
    {nucleodeCount: '175', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '176', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '177', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '178', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '179', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '179m1', decayType: ['IT']},
    {nucleodeCount: '179m2', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '181', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '181m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '181m2', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['[[electron capture', 'EC]]']},
    {nucleodeCount: '182m1', decayType: ['IT']},
    {nucleodeCount: '182m2', decayType: ['IT']},
    {nucleodeCount: '183', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '183m', decayType: ['b<sup>+</sup> (85%)']},
    {nucleodeCount: '183m', decayType: ['[[Isomeric transition', 'IT]] (15%)']},
    {nucleodeCount: '184', decayType: ["'''1.12(23)x10<sup>13</sup>&nbsp;y'''"]},
    {nucleodeCount: '184', decayType: ['a<ref group="n">Theorized to also undergo b<sup>+</sup>b<sup>+</sup> decay to \'\'\'<sup>184</sup>W\'\'\'</ref>']},
    {nucleodeCount: '185', decayType: ['EC']},
    {nucleodeCount: '185m1', decayType: ['IT']},
    {nucleodeCount: '185m2', decayType: ['IT']},
    {nucleodeCount: '186', decayType: ['a']},
    {nucleodeCount: '187', decayType: ['186.95574957(79)']},
    {nucleodeCount: '187m1', decayType: ['IT']},
    {nucleodeCount: '187m2', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['187.95583729(79)']},
    {nucleodeCount: '189', decayType: ['188.95814595(72)']},
    {nucleodeCount: '189m', decayType: ['IT']},
    {nucleodeCount: '190', decayType: ['189.95844544(70)']},
    {nucleodeCount: '190m', decayType: ['IT']},
    {nucleodeCount: '191', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '191m', decayType: ['IT']},
    {nucleodeCount: '192', decayType: ['191.9614788(25)']},
    {nucleodeCount: '192m1', decayType: ['IT']},
    {nucleodeCount: '192m1', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '192m2', decayType: ['IT']},
    {nucleodeCount: '193', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '193m', decayType: ['IT']},
    {nucleodeCount: '194', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '195', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '195m', decayType: ['IT']},
    {nucleodeCount: '195m', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '196', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '197', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '198', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '199', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '200', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '201', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '202', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '203', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '203', decayType: ['b<sup>-</sup> n?']},
]
