const oxygen = [
    {nucleodeCount: 'None', decayType: ['[[proton emission', '2p]]']},
    {nucleodeCount: '12', decayType: ['2p']},
    {nucleodeCount: '13', decayType: ['b<sup>+</sup> ({{val', '89.1', '(2)', 'u=%}})']},
    {nucleodeCount: '13', decayType: ['b<sup>+</sup>p ({{val', '10.9', '(2)', 'u=%}})']},
    {nucleodeCount: '13', decayType: ['b<sup>+</sup>p,a (<{{val', '0.1', 'u=%}})']},
    {nucleodeCount: '14', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '15', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '19', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '20', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '21', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '21', decayType: ['b<sup>-</sup>n ?<ref group="n" name="decay mode 1">Decay mode shown is energetically allowed, but has not been experimentally observed to occur in this nuclide.</ref>']},
    {nucleodeCount: '22', decayType: ['b<sup>-</sup> (> {{val', '78', 'u=%}})']},
    {nucleodeCount: '22', decayType: ['b<sup>-</sup>n (< {{val', '22', 'u=%}})']},
    {nucleodeCount: '23', decayType: ['b<sup>-</sup> ({{val', '93', '(2)', 'u=%}})']},
    {nucleodeCount: '23', decayType: ['b<sup>-</sup>n ({{val', '7', '(2)', 'u=%}})']},
    {nucleodeCount: '24', decayType: ['b<sup>-</sup> ({{val', '57', '(4)', 'u=%}})']},
    {nucleodeCount: '24', decayType: ['b<sup>-</sup>n ({{val', '43', '(4)', 'u=%}})']},
    {nucleodeCount: '25', decayType: ['n']},
    {nucleodeCount: '26', decayType: ['2n']},
    {nucleodeCount: '27', decayType: ['n']},
    {nucleodeCount: '28', decayType: ['2n']},
]
