const palladium = [
    {nucleodeCount: '90', decayType: ['b+']},
    {nucleodeCount: '90', decayType: ['b+, p']},
    {nucleodeCount: '90', decayType: ['2p']},
    {nucleodeCount: '91', decayType: ['b+']},
    {nucleodeCount: '91', decayType: ['b+, p']},
    {nucleodeCount: '92', decayType: ['b+']},
    {nucleodeCount: '92', decayType: ['b+, p']},
    {nucleodeCount: '93', decayType: ['b+']},
    {nucleodeCount: '93', decayType: ['b+, p']},
    {nucleodeCount: '94', decayType: ['b+']},
    {nucleodeCount: '94', decayType: ['b+, p']},
    {nucleodeCount: '94m1', decayType: ['IT']},
    {nucleodeCount: '94m2', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b+']},
    {nucleodeCount: '95', decayType: ['b+, p']},
    {nucleodeCount: '95m', decayType: ['b+']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '95m', decayType: ['b+, p']},
    {nucleodeCount: '96', decayType: ['b+']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b+']},
    {nucleodeCount: '98', decayType: ['b+']},
    {nucleodeCount: '99', decayType: ['b+']},
    {nucleodeCount: '100', decayType: ['EC']},
    {nucleodeCount: '101', decayType: ['b+']},
    {nucleodeCount: '102', decayType: ['101.90563229(45)']},
    {nucleodeCount: '103', decayType: ['EC']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '107m1', decayType: ['IT']},
    {nucleodeCount: '107m2', decayType: ['IT']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '109m1', decayType: ['IT']},
    {nucleodeCount: '109m2', decayType: ['IT']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '111m', decayType: ['IT']},
    {nucleodeCount: '111m', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b-']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['IT']},
    {nucleodeCount: '116', decayType: ['b-']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-, n']},
    {nucleodeCount: '119m', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-, n']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-, n']},
    {nucleodeCount: '121m1', decayType: ['IT']},
    {nucleodeCount: '121m2', decayType: ['IT']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '122', decayType: ['b-, n']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-, n']},
    {nucleodeCount: '123m', decayType: ['b-']},
    {nucleodeCount: '123m', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '124', decayType: ['b-, n']},
    {nucleodeCount: '124m', decayType: ['IT']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125', decayType: ['b-, n']},
    {nucleodeCount: '125m1', decayType: ['b-']},
    {nucleodeCount: '125m1', decayType: ['IT']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '126', decayType: ['b-, n']},
    {nucleodeCount: '126m1', decayType: ['IT']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '126m3', decayType: ['b-']},
    {nucleodeCount: '126m3', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127', decayType: ['b-, n']},
    {nucleodeCount: '127', decayType: ['b-, 2n']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b-']},
    {nucleodeCount: '128', decayType: ['b-, n']},
    {nucleodeCount: '128m', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b-']},
    {nucleodeCount: '129', decayType: ['b-, n']},
    {nucleodeCount: '129', decayType: ['b-, 2n']},
    {nucleodeCount: '130', decayType: ['b-']},
    {nucleodeCount: '130', decayType: ['b-, n']},
    {nucleodeCount: '130', decayType: ['b-, 2n']},
    {nucleodeCount: '131', decayType: ['b-']},
    {nucleodeCount: '131', decayType: ['b-, n']},
    {nucleodeCount: '131', decayType: ['b-, 2n']},
]
