const palladium = [
    {nucleodeCount: '90', decayType: ['[[beta decay', 'b<sup>+</sup>]]?']},
    {nucleodeCount: '90', decayType: ['b<sup>+</sup>, [[proton emission', 'p]]?']},
    {nucleodeCount: '90', decayType: ['2p?']},
    {nucleodeCount: '91', decayType: ['b<sup>+</sup> (96.9%)']},
    {nucleodeCount: '91', decayType: ['b<sup>+</sup>, p (3.1%)']},
    {nucleodeCount: '92', decayType: ['b<sup>+</sup> (98.4%)']},
    {nucleodeCount: '92', decayType: ['b<sup>+</sup>, p (1.6%)']},
    {nucleodeCount: '93', decayType: ['b<sup>+</sup> (92.6%)']},
    {nucleodeCount: '93', decayType: ['b<sup>+</sup>, p (7.4%)']},
    {nucleodeCount: '94', decayType: ['b<sup>+</sup> (>99.87%)']},
    {nucleodeCount: '94', decayType: ['b<sup>+</sup>, p (<0.13%)']},
    {nucleodeCount: '94m1', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '94m2', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b<sup>+</sup> (99.77%)']},
    {nucleodeCount: '95', decayType: ['b<sup>+</sup>, p (0.23%)']},
    {nucleodeCount: '95m', decayType: ['b<sup>+</sup> (88%)']},
    {nucleodeCount: '95m', decayType: ['[[Isomeric transition', 'IT]] (11%)']},
    {nucleodeCount: '95m', decayType: ['b<sup>+</sup>, p (0.71%)']},
    {nucleodeCount: '96', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '98', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '99', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '100', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '101', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '102', decayType: ['101.90563229(45)']},
    {nucleodeCount: '103', decayType: ['EC']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '107m1', decayType: ['IT']},
    {nucleodeCount: '107m2', decayType: ['IT']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '109m1', decayType: ['IT']},
    {nucleodeCount: '109m2', decayType: ['IT']},
    {nucleodeCount: '111', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '111m', decayType: ['IT (76.8%)']},
    {nucleodeCount: '111m', decayType: ['b<sup>-</sup> (23.2%)']},
    {nucleodeCount: '112', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '113', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '115', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '115m', decayType: ['b<sup>-</sup> (92.0%)']},
    {nucleodeCount: '115m', decayType: ['IT (8.0%)']},
    {nucleodeCount: '116', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '117', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '119', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '119', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '119m', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b<sup>-</sup> (>99.3%)']},
    {nucleodeCount: '120', decayType: ['b<sup>-</sup>, n (<0.7%)']},
    {nucleodeCount: '121', decayType: ['b<sup>-</sup> (>99.2%)']},
    {nucleodeCount: '121', decayType: ['b<sup>-</sup>, n (<0.8%)']},
    {nucleodeCount: '121m1', decayType: ['IT']},
    {nucleodeCount: '121m2', decayType: ['IT']},
    {nucleodeCount: '122', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '122', decayType: ['b<sup>-</sup>, n (<2.5%)']},
    {nucleodeCount: '123', decayType: ['b<sup>-</sup> (90%)']},
    {nucleodeCount: '123', decayType: ['b<sup>-</sup>, n (10%)']},
    {nucleodeCount: '123m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '123m', decayType: ['IT?']},
    {nucleodeCount: '124', decayType: ['b<sup>-</sup> (83%)']},
    {nucleodeCount: '124', decayType: ['b<sup>-</sup>, n (17%)']},
    {nucleodeCount: '124m', decayType: ['IT']},
    {nucleodeCount: '125', decayType: ['b<sup>-</sup> (88%)']},
    {nucleodeCount: '125', decayType: ['b<sup>-</sup>, n (12%)']},
    {nucleodeCount: '125m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '125m1', decayType: ['IT?']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b<sup>-</sup> (78%)']},
    {nucleodeCount: '126', decayType: ['b<sup>-</sup>, n (22%)']},
    {nucleodeCount: '126m1', decayType: ['IT']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '126m3', decayType: ['b<sup>-</sup> (72%)']},
    {nucleodeCount: '126m3', decayType: ['IT (28%)']},
    {nucleodeCount: '127', decayType: ['b<sup>-</sup> (>81%)']},
    {nucleodeCount: '127', decayType: ['b<sup>-</sup>, n (<19%)']},
    {nucleodeCount: '127', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '128', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '128m', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '129', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '129', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '130', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '130', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '130', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '131', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '131', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '131', decayType: ['b<sup>-</sup>, 2n?']},
]
