const praseodymium = [
    {nucleodeCount: '121', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '124', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '124', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '125', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '126', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '126', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '127', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '128', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '128', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '129', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '129m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '130', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '131', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '131m', decayType: ['[[Isomeric transition', 'IT]] (96.4%)']},
    {nucleodeCount: '131m', decayType: ['b<sup>+</sup> (3.6%)']},
    {nucleodeCount: '132', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '132m2', decayType: ['IT']},
    {nucleodeCount: '132m3', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '133m', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '134m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '135', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '137', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '137m', decayType: ['IT']},
    {nucleodeCount: '138', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '138m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '140', decayType: ['[[Electron capture', 'EC]] (51.3%)']},
    {nucleodeCount: '140m1', decayType: ['IT']},
    {nucleodeCount: '140m2', decayType: ['IT']},
    {nucleodeCount: '142', decayType: ['b<sup>-</sup> (99.98%)']},
    {nucleodeCount: '142', decayType: ['EC (0.0164%)']},
    {nucleodeCount: '142m', decayType: ['IT']},
    {nucleodeCount: '143', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '144', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '144m', decayType: ['IT (~99.93%)']},
    {nucleodeCount: '144m', decayType: ['b<sup>-</sup> (~0.07%)']},
    {nucleodeCount: '145', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '146', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '147', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '148', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '148m', decayType: ['b<sup>-</sup> (64%)']},
    {nucleodeCount: '148m', decayType: ['IT (36%)']},
    {nucleodeCount: '149', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '150', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '151', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '151m', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '152m', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '154', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '155', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '156', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '157', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '158', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '159', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '160', decayType: ['b<sup>-</sup>']},
]
