const promethium = [
    {nucleodeCount: '128', decayType: ['[[beta decay', 'b<sup>+</sup>]] (?%)']},
    {nucleodeCount: '128', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (?%)']},
    {nucleodeCount: '129', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '130', decayType: ['b<sup>+</sup> (?%)']},
    {nucleodeCount: '130', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '131', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '132', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '132', decayType: ['b<sup>+</sup>, p (5x10<sup>-5</sup>%)']},
    {nucleodeCount: '133', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '134', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '134m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '134m2', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '135', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '135m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '136', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '136m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '136m2', decayType: ['IT']},
    {nucleodeCount: '137m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '138', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '139m', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '140m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '141', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '141m1', decayType: ['IT']},
    {nucleodeCount: '141m2', decayType: ['IT']},
    {nucleodeCount: '142', decayType: ['b<sup>+</sup> (77.1%)']},
    {nucleodeCount: '142m1', decayType: ['IT']},
    {nucleodeCount: '142m2', decayType: ['IT']},
    {nucleodeCount: '143', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '144', decayType: ['EC']},
    {nucleodeCount: '144m1', decayType: ['IT']},
    {nucleodeCount: '144m2', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['EC']},
    {nucleodeCount: '145', decayType: ['[[alpha decay', 'a]] (2.8x10<sup>-7</sup>%)']},
    {nucleodeCount: '146', decayType: ['EC (66.0%)<ref name="Pm146-no-beta-plus"/>']},
    {nucleodeCount: '146', decayType: ['b<sup>-</sup> (34.0%)']},
    {nucleodeCount: '147', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '147', decayType: ['7/2+']},
    {nucleodeCount: '148', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '148m', decayType: ['b<sup>-</sup> (95.8%)']},
    {nucleodeCount: '148m', decayType: ['IT (4.2%)']},
    {nucleodeCount: '149', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '149m', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '151', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '152', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '152m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '153', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '154', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '154m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '155', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '156', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '156m', decayType: ['IT (98%)']},
    {nucleodeCount: '156m', decayType: ['b<sup>-</sup> (2%)']},
    {nucleodeCount: '157', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '158', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '158m', decayType: ['IT']},
    {nucleodeCount: '159', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '159m', decayType: ['IT']},
    {nucleodeCount: '159m', decayType: ['b<sup>-</sup>, n (<0.6%)<ref name=Ln922/>']},
    {nucleodeCount: '160', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '160', decayType: ['b<sup>-</sup>, n (<0.1%)<ref name=Ln922/>']},
    {nucleodeCount: '161', decayType: ['b<sup>-</sup> (98.91%)']},
    {nucleodeCount: '161', decayType: ['b<sup>-</sup>, n (1.09%)<ref name=Ln922/>']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b<sup>-</sup> (98.21%)']},
    {nucleodeCount: '162', decayType: ['b<sup>-</sup>, n (1.79%)<ref name=Ln922/>']},
    {nucleodeCount: '163', decayType: ['b<sup>-</sup> (95%)']},
    {nucleodeCount: '163', decayType: ['b<sup>-</sup>, n (5.00%)<ref name=Ln922/>']},
    {nucleodeCount: '164', decayType: ['b<sup>-</sup> (93.82%)']},
    {nucleodeCount: '164', decayType: ['b<sup>-</sup>, n (6.18%)<ref name=Ln922/>']},
    {nucleodeCount: '165', decayType: ['b<sup>-</sup> (86.74%)']},
    {nucleodeCount: '165', decayType: ['b<sup>-</sup>, n (13.26%)<ref name=Ln922/>']},
    {nucleodeCount: '166', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166', decayType: ['b<sup>-</sup>, n (<52%)<ref name=Ln922/>']},
]
