const promethium = [
    {nucleodeCount: '128', decayType: ['b+']},
    {nucleodeCount: '128', decayType: ['b+, p']},
    {nucleodeCount: '129', decayType: ['b+']},
    {nucleodeCount: '130', decayType: ['b+']},
    {nucleodeCount: '130', decayType: ['b+, p']},
    {nucleodeCount: '131', decayType: ['b+']},
    {nucleodeCount: '132', decayType: ['b+']},
    {nucleodeCount: '132', decayType: ['b+, p (5x10<sup>-5</sup)']},
    {nucleodeCount: '133', decayType: ['b+']},
    {nucleodeCount: '134', decayType: ['b+']},
    {nucleodeCount: '134m1', decayType: ['b+']},
    {nucleodeCount: '134m2', decayType: ['IT']},
    {nucleodeCount: '135', decayType: ['b+']},
    {nucleodeCount: '135m', decayType: ['b+']},
    {nucleodeCount: '136', decayType: ['b+']},
    {nucleodeCount: '136m1', decayType: ['b+']},
    {nucleodeCount: '136m2', decayType: ['IT']},
    {nucleodeCount: '137m', decayType: ['b+']},
    {nucleodeCount: '138', decayType: ['b+']},
    {nucleodeCount: '139', decayType: ['b+']},
    {nucleodeCount: '139m', decayType: ['IT']},
    {nucleodeCount: '140', decayType: ['b+']},
    {nucleodeCount: '140m', decayType: ['b+']},
    {nucleodeCount: '141', decayType: ['b+']},
    {nucleodeCount: '141m1', decayType: ['IT']},
    {nucleodeCount: '141m2', decayType: ['IT']},
    {nucleodeCount: '142', decayType: ['b+']},
    {nucleodeCount: '142m1', decayType: ['IT']},
    {nucleodeCount: '142m2', decayType: ['IT']},
    {nucleodeCount: '143', decayType: ['EC']},
    {nucleodeCount: '144', decayType: ['EC']},
    {nucleodeCount: '144m1', decayType: ['IT']},
    {nucleodeCount: '144m2', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['EC']},
    {nucleodeCount: '145', decayType: ['a (2.8x10<sup>-7</sup)']},
    {nucleodeCount: '146', decayType: ['EC<ref name="Pm146-no-beta-plus"/>']},
    {nucleodeCount: '146', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['7/2+']},
    {nucleodeCount: '148', decayType: ['b-']},
    {nucleodeCount: '148m', decayType: ['b-']},
    {nucleodeCount: '148m', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b-']},
    {nucleodeCount: '149m', decayType: ['IT']},
    {nucleodeCount: '150', decayType: ['b-']},
    {nucleodeCount: '151', decayType: ['b-']},
    {nucleodeCount: '152', decayType: ['b-']},
    {nucleodeCount: '152m', decayType: ['b-']},
    {nucleodeCount: '153', decayType: ['b-']},
    {nucleodeCount: '154', decayType: ['b-']},
    {nucleodeCount: '154m', decayType: ['b-']},
    {nucleodeCount: '155', decayType: ['b-']},
    {nucleodeCount: '156', decayType: ['b-']},
    {nucleodeCount: '156m', decayType: ['IT']},
    {nucleodeCount: '156m', decayType: ['b-']},
    {nucleodeCount: '157', decayType: ['b-']},
    {nucleodeCount: '158', decayType: ['b-']},
    {nucleodeCount: '158m', decayType: ['IT']},
    {nucleodeCount: '159', decayType: ['b-']},
    {nucleodeCount: '159m', decayType: ['IT']},
    {nucleodeCount: '159m', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '160', decayType: ['b-']},
    {nucleodeCount: '160', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '161', decayType: ['b-']},
    {nucleodeCount: '161', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '161m', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b-']},
    {nucleodeCount: '162', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '163', decayType: ['b-']},
    {nucleodeCount: '163', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '164', decayType: ['b-']},
    {nucleodeCount: '164', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '165', decayType: ['b-']},
    {nucleodeCount: '165', decayType: ['b-, n<ref name=Ln922/>']},
    {nucleodeCount: '166', decayType: ['b-']},
    {nucleodeCount: '166', decayType: ['b-, n<ref name=Ln922/>']},
]
