const protactinium = [
    {nucleodeCount: '211', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '212', decayType: ['a']},
    {nucleodeCount: '213', decayType: ['a']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '217m', decayType: ['a (73%)']},
    {nucleodeCount: '217m', decayType: ['[[Isomeric transition', 'IT]] (27%)']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a']},
    {nucleodeCount: '220m1', decayType: ['a']},
    {nucleodeCount: '220m2', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['a']},
    {nucleodeCount: '223', decayType: ['a']},
    {nucleodeCount: '224', decayType: ['a (99.9%)']},
    {nucleodeCount: '225', decayType: ['a']},
    {nucleodeCount: '226', decayType: ['a (74%)']},
    {nucleodeCount: '226', decayType: ['b<sup>+</sup> (26%)']},
    {nucleodeCount: '227', decayType: ['a (85%)']},
    {nucleodeCount: '227', decayType: ['[[Electron capture', 'EC]] (15%)']},
    {nucleodeCount: '228', decayType: ['b<sup>+</sup> (98.15%)']},
    {nucleodeCount: '228', decayType: ['a (1.85%)']},
    {nucleodeCount: '229', decayType: ['EC (99.51%)']},
    {nucleodeCount: '229', decayType: ['a (0.49%)']},
    {nucleodeCount: '229m', decayType: ['IT']},
    {nucleodeCount: '230', decayType: ['b<sup>+</sup> (92.2%)']},
    {nucleodeCount: '230', decayType: ['b<sup>-</sup> (7.8%)']},
    {nucleodeCount: '230', decayType: ['a (0.0032%)']},
    {nucleodeCount: '231', decayType: ['a']},
    {nucleodeCount: '231', decayType: ['rowspan=4', '3/2-']},
    {nucleodeCount: '231', decayType: ['[[Cluster decay', 'CD]] (1.34x10<sup>-10</sup>%)']},
    {nucleodeCount: '231', decayType: ['CD (9.9x10<sup>-13</sup>%)']},
    {nucleodeCount: '232', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '233', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '233', decayType: ['3/2-']},
    {nucleodeCount: '234', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '234', decayType: ['rowspan=2', '4+']},
    {nucleodeCount: '234m', decayType: ['b<sup>-</sup> (99.84%)']},
    {nucleodeCount: '234m', decayType: ['IT (0.16%)']},
    {nucleodeCount: '235', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '236', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '237', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '238', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '239', decayType: ['b<sup>-</sup>']},
]
