const radium = [
    {nucleodeCount: '201', decayType: ['a']},
    {nucleodeCount: '201m', decayType: ['a']},
    {nucleodeCount: '202', decayType: ['a']},
    {nucleodeCount: '203', decayType: ['a']},
    {nucleodeCount: '203m', decayType: ['a']},
    {nucleodeCount: '204', decayType: ['a']},
    {nucleodeCount: '205', decayType: ['a']},
    {nucleodeCount: '205m', decayType: ['a']},
    {nucleodeCount: '206', decayType: ['a']},
    {nucleodeCount: '207', decayType: ['a']},
    {nucleodeCount: '207', decayType: ['b+']},
    {nucleodeCount: '207m', decayType: ['IT (85#)']},
    {nucleodeCount: '207m', decayType: ['a']},
    {nucleodeCount: '208', decayType: ['a']},
    {nucleodeCount: '208', decayType: ['b+']},
    {nucleodeCount: '208m', decayType: ['IT']},
    {nucleodeCount: '209', decayType: ['a']},
    {nucleodeCount: '209m', decayType: ['a']},
    {nucleodeCount: '209m', decayType: ['b+']},
    {nucleodeCount: '210', decayType: ['a']},
    {nucleodeCount: '210m', decayType: ['IT']},
    {nucleodeCount: '211', decayType: ['a']},
    {nucleodeCount: '211m', decayType: ['IT']},
    {nucleodeCount: '212', decayType: ['a']},
    {nucleodeCount: '212', decayType: ['b+']},
    {nucleodeCount: '212m1', decayType: ['IT']},
    {nucleodeCount: '212m2', decayType: ['IT']},
    {nucleodeCount: '213', decayType: ['a']},
    {nucleodeCount: '213', decayType: ['b+']},
    {nucleodeCount: '213m', decayType: ['IT']},
    {nucleodeCount: '213m', decayType: ['a']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214', decayType: ['b+']},
    {nucleodeCount: '214m1', decayType: ['IT']},
    {nucleodeCount: '214m2', decayType: ['IT']},
    {nucleodeCount: '214m2', decayType: ['a']},
    {nucleodeCount: '214m3', decayType: ['IT']},
    {nucleodeCount: '214m4', decayType: ['IT']},
    {nucleodeCount: '214m5', decayType: ['IT']},
    {nucleodeCount: '214m6', decayType: ['IT']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '215m1', decayType: ['IT']},
    {nucleodeCount: '215m2', decayType: ['IT']},
    {nucleodeCount: '215m3', decayType: ['IT']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216', decayType: ['EC (<1x10<sup>-8</sup)']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '219m', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['rowspan=2', '5/2+']},
    {nucleodeCount: '221', decayType: ['[[Cluster decay', 'CD]] (1.2x10<sup>-10</sup)<ref group="n">Lightest known nuclide to undergo [[cluster decay]]</ref>']},
    {nucleodeCount: '222', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['CD (3.0x10<sup>-8</sup)']},
    {nucleodeCount: '223', decayType: ['a']},
    {nucleodeCount: '223', decayType: ['rowspan=2', '3/2+']},
    {nucleodeCount: '223', decayType: ['CD (8.9x10<sup>-8</sup)']},
    {nucleodeCount: '224', decayType: ['a']},
    {nucleodeCount: '224', decayType: ['rowspan=2', '0+']},
    {nucleodeCount: '224', decayType: ['CD (4.0x10<sup>-9</sup)']},
    {nucleodeCount: '225', decayType: ['b-']},
    {nucleodeCount: '225', decayType: ['rowspan=2', '1/2+']},
    {nucleodeCount: '225', decayType: ['a ((2.0�0.5)x10<sup>-3</sup)<ref name="Ra-225"/>']},
    {nucleodeCount: '226', decayType: ['rowspan=2', '1600(7)&nbsp;y']},
    {nucleodeCount: '226', decayType: ['a{{refn', 'group=n', 'Theoretically capable of b-b- decay to <sup>226</sup>Th}}']},
    {nucleodeCount: '226', decayType: ['rowspan=2', '0+']},
    {nucleodeCount: '226', decayType: ['CD (2.6x10<sup>-9</sup)']},
    {nucleodeCount: '227', decayType: ['b-']},
    {nucleodeCount: '228', decayType: ['b-']},
    {nucleodeCount: '229', decayType: ['b-']},
    {nucleodeCount: '230', decayType: ['b-']},
    {nucleodeCount: '231', decayType: ['b-']},
    {nucleodeCount: '231m', decayType: ['IT']},
    {nucleodeCount: '232', decayType: ['b-']},
    {nucleodeCount: '233', decayType: ['b-']},
    {nucleodeCount: '234', decayType: ['b-']},
]
