const rhodium = [
    {nucleodeCount: '90', decayType: ['b+']},
    {nucleodeCount: '90', decayType: ['b+, p']},
    {nucleodeCount: '90m', decayType: ['b+']},
    {nucleodeCount: '90m', decayType: ['b+, p']},
    {nucleodeCount: '91', decayType: ['b+']},
    {nucleodeCount: '91', decayType: ['b+, p']},
    {nucleodeCount: '91m', decayType: ['b+']},
    {nucleodeCount: '91m', decayType: ['b+, p']},
    {nucleodeCount: '91m', decayType: ['IT']},
    {nucleodeCount: '92', decayType: ['b+']},
    {nucleodeCount: '92', decayType: ['b+, p']},
    {nucleodeCount: '92m1', decayType: ['b+']},
    {nucleodeCount: '92m1', decayType: ['b+, p']},
    {nucleodeCount: '92m2', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b+']},
    {nucleodeCount: '94', decayType: ['b+']},
    {nucleodeCount: '94', decayType: ['b+, p']},
    {nucleodeCount: '94m1', decayType: ['IT']},
    {nucleodeCount: '94m2', decayType: ['b+']},
    {nucleodeCount: '95', decayType: ['b+']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '95m', decayType: ['b+']},
    {nucleodeCount: '96', decayType: ['b+']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '96m', decayType: ['b+']},
    {nucleodeCount: '97', decayType: ['b+']},
    {nucleodeCount: '97m', decayType: ['b+']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b+']},
    {nucleodeCount: '98m', decayType: ['IT']},
    {nucleodeCount: '98m', decayType: ['b+']},
    {nucleodeCount: '99', decayType: ['b+']},
    {nucleodeCount: '99m', decayType: ['b+']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['EC']},
    {nucleodeCount: '100', decayType: ['b+']},
    {nucleodeCount: '100m1', decayType: ['IT']},
    {nucleodeCount: '100m2', decayType: ['IT']},
    {nucleodeCount: '100m2', decayType: ['b+']},
    {nucleodeCount: '100m3', decayType: ['IT']},
    {nucleodeCount: '101', decayType: ['EC']},
    {nucleodeCount: '101m', decayType: ['EC']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b+']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '102m', decayType: ['b+']},
    {nucleodeCount: '102m', decayType: ['IT']},
    {nucleodeCount: '103m', decayType: ['IT']},
    {nucleodeCount: '104', decayType: ['b-']},
    {nucleodeCount: '104', decayType: ['b+']},
    {nucleodeCount: '104m', decayType: ['IT']},
    {nucleodeCount: '104m', decayType: ['b-']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '106m', decayType: ['b-']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '107m', decayType: ['IT']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '108m', decayType: ['b-']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '109m', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b-']},
    {nucleodeCount: '110m', decayType: ['b-']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-']},
    {nucleodeCount: '112m', decayType: ['b-']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '114', decayType: ['b-']},
    {nucleodeCount: '114m', decayType: ['b-']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115', decayType: ['b-, n']},
    {nucleodeCount: '116', decayType: ['b-']},
    {nucleodeCount: '116', decayType: ['b-, n']},
    {nucleodeCount: '116m', decayType: ['b-']},
    {nucleodeCount: '116m', decayType: ['b-, n']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117', decayType: ['b-, n']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '118', decayType: ['b-, n']},
    {nucleodeCount: '118m', decayType: ['b-']},
    {nucleodeCount: '118m', decayType: ['b-, n']},
    {nucleodeCount: '118m', decayType: ['IT']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-, n']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-, n']},
    {nucleodeCount: '120', decayType: ['b-, 2n']},
    {nucleodeCount: '120m', decayType: ['IT']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-, n']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '122', decayType: ['b-, n']},
    {nucleodeCount: '122', decayType: ['b-, 2n']},
    {nucleodeCount: '122m', decayType: ['IT']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-, n']},
    {nucleodeCount: '123', decayType: ['b-, 2n']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '124', decayType: ['b-, n']},
    {nucleodeCount: '124', decayType: ['b-, 2n']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125', decayType: ['b-, n']},
    {nucleodeCount: '125', decayType: ['b-, 2n']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '126', decayType: ['b-, n']},
    {nucleodeCount: '126', decayType: ['b-, 2n']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127', decayType: ['b-, n']},
    {nucleodeCount: '127', decayType: ['b-, 2n']},
    {nucleodeCount: '128', decayType: ['b-']},
    {nucleodeCount: '128', decayType: ['b-, n']},
    {nucleodeCount: '128', decayType: ['b-, 2n']},
]
