const rubidium = [
    {nucleodeCount: '72', decayType: ['p']},
    {nucleodeCount: '73', decayType: ['p']},
    {nucleodeCount: '74', decayType: ['b+']},
    {nucleodeCount: '75', decayType: ['b+']},
    {nucleodeCount: '76', decayType: ['b+']},
    {nucleodeCount: '76', decayType: ['b+, a (3.8x10<sup>-7</sup)']},
    {nucleodeCount: '76m', decayType: ['IT']},
    {nucleodeCount: '77', decayType: ['b+']},
    {nucleodeCount: '78', decayType: ['b+']},
    {nucleodeCount: '78m1', decayType: ['IT']},
    {nucleodeCount: '78m2', decayType: ['b+']},
    {nucleodeCount: '78m2', decayType: ['IT']},
    {nucleodeCount: '79', decayType: ['b+']},
    {nucleodeCount: '80', decayType: ['b+']},
    {nucleodeCount: '80m', decayType: ['IT']},
    {nucleodeCount: '81', decayType: ['b+']},
    {nucleodeCount: '81m', decayType: ['IT']},
    {nucleodeCount: '81m', decayType: ['b+']},
    {nucleodeCount: '81m', decayType: ['b+']},
    {nucleodeCount: '82m', decayType: ['b+']},
    {nucleodeCount: '82m', decayType: ['IT']},
    {nucleodeCount: '83', decayType: ['EC']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b+']},
    {nucleodeCount: '84', decayType: ['b-']},
    {nucleodeCount: '84m', decayType: ['IT']},
    {nucleodeCount: '84m', decayType: ['b+']},
    {nucleodeCount: '85m', decayType: ['IT']},
    {nucleodeCount: '86', decayType: ['b-']},
    {nucleodeCount: '86', decayType: ['EC']},
    {nucleodeCount: '86m', decayType: ['IT']},
    {nucleodeCount: '86m', decayType: ['b-']},
    {nucleodeCount: '87', decayType: ['b-']},
    {nucleodeCount: '88', decayType: ['b-']},
    {nucleodeCount: '88m', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b-']},
    {nucleodeCount: '90', decayType: ['b-']},
    {nucleodeCount: '90m', decayType: ['b-']},
    {nucleodeCount: '90m', decayType: ['IT']},
    {nucleodeCount: '91', decayType: ['b-']},
    {nucleodeCount: '92', decayType: ['b-']},
    {nucleodeCount: '92', decayType: ['b-, n']},
    {nucleodeCount: '93', decayType: ['b-']},
    {nucleodeCount: '93', decayType: ['b-, n']},
    {nucleodeCount: '93m', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b-']},
    {nucleodeCount: '94', decayType: ['b-, n']},
    {nucleodeCount: '94m1', decayType: ['IT']},
    {nucleodeCount: '94m2', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b-']},
    {nucleodeCount: '95', decayType: ['b-, n']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b-']},
    {nucleodeCount: '96', decayType: ['b-, n']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b-']},
    {nucleodeCount: '97', decayType: ['b-, n']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b-()']},
    {nucleodeCount: '98', decayType: ['b-, n']},
    {nucleodeCount: '98', decayType: ['b-, 2n']},
    {nucleodeCount: '98m1', decayType: ['b-']},
    {nucleodeCount: '98m2', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b-']},
    {nucleodeCount: '99', decayType: ['b-, n']},
    {nucleodeCount: '100', decayType: ['b-']},
    {nucleodeCount: '100', decayType: ['b-, n']},
    {nucleodeCount: '100', decayType: ['b-, 2n']},
    {nucleodeCount: '101', decayType: ['b-']},
    {nucleodeCount: '101', decayType: ['b-, n']},
    {nucleodeCount: '102', decayType: ['b-, n']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '103', decayType: ['b-']},
]
