const rubidium = [
    {nucleodeCount: '72', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '73', decayType: ['p']},
    {nucleodeCount: '74', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '75', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup>, [[alpha decay', 'a]] (3.8x10<sup>-7</sup>%)']},
    {nucleodeCount: '76m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '78', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '78m1', decayType: ['IT']},
    {nucleodeCount: '78m2', decayType: ['b<sup>+</sup> (91%)']},
    {nucleodeCount: '78m2', decayType: ['IT (9%)']},
    {nucleodeCount: '79', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '80', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '80m', decayType: ['IT']},
    {nucleodeCount: '81', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '81m', decayType: ['IT (97.6%)']},
    {nucleodeCount: '81m', decayType: ['b<sup>+</sup> (2.4%)']},
    {nucleodeCount: '81m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '82m', decayType: ['b<sup>+</sup> (>99.67%)']},
    {nucleodeCount: '82m', decayType: ['IT (<0.33%)']},
    {nucleodeCount: '83', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b<sup>+</sup> (96.1%)']},
    {nucleodeCount: '84', decayType: ['b<sup>-</sup> (3.9%)']},
    {nucleodeCount: '84m', decayType: ['IT']},
    {nucleodeCount: '84m', decayType: ['b<sup>+</sup> (<0.0012%)']},
    {nucleodeCount: '85m', decayType: ['IT']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup> (99.99%)']},
    {nucleodeCount: '86', decayType: ['EC (.0052%)']},
    {nucleodeCount: '86m', decayType: ['IT (>99.7%)']},
    {nucleodeCount: '86m', decayType: ['b<sup>-</sup> (<0.3%)']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '88m', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '90m', decayType: ['b<sup>-</sup> (97.4%)']},
    {nucleodeCount: '90m', decayType: ['IT (2.6%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup> (99.99%)']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (0.0107%)']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup> (98.61%)']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>, n (1.39%)']},
    {nucleodeCount: '93m', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup> (89.7%)']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>, n (10.3%)']},
    {nucleodeCount: '94m1', decayType: ['IT']},
    {nucleodeCount: '94m2', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup> (91.3%)']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>, n (8.7%)']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup> (86.3%)']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>, n (13.7%)']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup> (74.5%)']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>, n (25.5%)']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>(85.65%)']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, n (14.3%)']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, 2n (0.054%)']},
    {nucleodeCount: '98m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '98m2', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup> (82.7%)']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup>, n (17.3%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup> (94.3%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>, n (5.6%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>, 2n (0.15%)']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup> (72%)']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup>, n (28%)']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup>, n (65%)']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup> (35%)']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup>']},
]
