const ruthenium = [
    {nucleodeCount: '88', decayType: ['b+']},
    {nucleodeCount: '88', decayType: ['b+, p']},
    {nucleodeCount: '89', decayType: ['b+']},
    {nucleodeCount: '89', decayType: ['b+, p']},
    {nucleodeCount: '90', decayType: ['b+']},
    {nucleodeCount: '91', decayType: ['b+']},
    {nucleodeCount: '91m', decayType: ['b+']},
    {nucleodeCount: '91m', decayType: ['b+, p']},
    {nucleodeCount: '92', decayType: ['b+']},
    {nucleodeCount: '92m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b+']},
    {nucleodeCount: '93m1', decayType: ['b+']},
    {nucleodeCount: '93m1', decayType: ['IT']},
    {nucleodeCount: '93m1', decayType: ['b+, p']},
    {nucleodeCount: '93m2', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b+']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b+']},
    {nucleodeCount: '96', decayType: ['95.90758891(18)']},
    {nucleodeCount: '97', decayType: ['b+']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '103', decayType: ['b-']},
    {nucleodeCount: '103m', decayType: ['IT']},
    {nucleodeCount: '104', decayType: ['103.9054253(27)']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '109m', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b-']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '113m', decayType: ['b-']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b-']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['IT']},
    {nucleodeCount: '116', decayType: ['b-']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119m', decayType: ['IT']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '124', decayType: ['b-']},
]
