const scandium = [
    {nucleodeCount: 'None', decayType: ['p']},
    {nucleodeCount: '38', decayType: ['p']},
    {nucleodeCount: '39', decayType: ['p']},
    {nucleodeCount: '40', decayType: ['b+']},
    {nucleodeCount: '40', decayType: ['b+, p']},
    {nucleodeCount: '40', decayType: ['b+, a']},
    {nucleodeCount: '41', decayType: ['b+']},
    {nucleodeCount: '42', decayType: ['b+']},
    {nucleodeCount: '42m', decayType: ['b+']},
    {nucleodeCount: '43', decayType: ['b+']},
    {nucleodeCount: '43m1', decayType: ['IT']},
    {nucleodeCount: '43m2', decayType: ['IT']},
    {nucleodeCount: '44', decayType: ['b+']},
    {nucleodeCount: '44m1', decayType: ['IT']},
    {nucleodeCount: '44m2', decayType: ['IT']},
    {nucleodeCount: '44m3', decayType: ['IT']},
    {nucleodeCount: '44m3', decayType: ['b+']},
    {nucleodeCount: '45m', decayType: ['IT']},
    {nucleodeCount: '46', decayType: ['b-']},
    {nucleodeCount: '46m1', decayType: ['IT']},
    {nucleodeCount: '46m2', decayType: ['IT']},
    {nucleodeCount: '47', decayType: ['b-']},
    {nucleodeCount: '47m', decayType: ['IT']},
    {nucleodeCount: '48', decayType: ['b-']},
    {nucleodeCount: '49', decayType: ['b-']},
    {nucleodeCount: '50', decayType: ['b-']},
    {nucleodeCount: '50m', decayType: ['IT']},
    {nucleodeCount: '50m', decayType: ['b-']},
    {nucleodeCount: '51', decayType: ['b-']},
    {nucleodeCount: '51', decayType: ['b-, n']},
    {nucleodeCount: '52', decayType: ['b-']},
    {nucleodeCount: '52', decayType: ['b-, n']},
    {nucleodeCount: '53', decayType: ['b-']},
    {nucleodeCount: '53', decayType: ['b-, n']},
    {nucleodeCount: '54', decayType: ['b-']},
    {nucleodeCount: '54', decayType: ['b-, n']},
    {nucleodeCount: '54m', decayType: ['IT']},
    {nucleodeCount: '55', decayType: ['b-']},
    {nucleodeCount: '55', decayType: ['b-, n']},
    {nucleodeCount: '55', decayType: ['b-, 2n']},
    {nucleodeCount: '56', decayType: ['b-']},
    {nucleodeCount: '56', decayType: ['b-, n']},
    {nucleodeCount: '56', decayType: ['b-, 2n']},
    {nucleodeCount: '56m1', decayType: ['b-']},
    {nucleodeCount: '56m1', decayType: ['b-, n']},
    {nucleodeCount: '56m1', decayType: ['b-, 2n']},
    {nucleodeCount: '56m2', decayType: ['IT']},
    {nucleodeCount: '57', decayType: ['b-']},
    {nucleodeCount: '57', decayType: ['b-, n']},
    {nucleodeCount: '57', decayType: ['b-, 2n']},
    {nucleodeCount: '58', decayType: ['b-']},
    {nucleodeCount: '58', decayType: ['b-, n']},
    {nucleodeCount: '58', decayType: ['b-, 2n']},
    {nucleodeCount: '58m', decayType: ['IT']},
    {nucleodeCount: '59', decayType: ['b-']},
    {nucleodeCount: '59', decayType: ['b-, n']},
    {nucleodeCount: '59', decayType: ['b-, 2n']},
    {nucleodeCount: '60', decayType: ['b-']},
    {nucleodeCount: '60', decayType: ['b-, n']},
    {nucleodeCount: '60', decayType: ['b-, 2n']},
    {nucleodeCount: '61', decayType: ['b-']},
    {nucleodeCount: '61', decayType: ['b-, n']},
    {nucleodeCount: '61', decayType: ['b-, 2n']},
    {nucleodeCount: '62', decayType: ['b-']},
    {nucleodeCount: '62', decayType: ['b-, n']},
    {nucleodeCount: '62', decayType: ['b-, 2n']},
]
