const seaborgium = [
    {nucleodeCount: '259', decayType: ['a']},
    {nucleodeCount: '259', decayType: ['b+']},
    {nucleodeCount: '259m', decayType: ['a']},
    {nucleodeCount: '259m', decayType: ['b+']},
    {nucleodeCount: '260', decayType: ['a']},
    {nucleodeCount: '261', decayType: ['a']},
    {nucleodeCount: '261', decayType: ['b+']},
    {nucleodeCount: '261m', decayType: ['IT']},
    {nucleodeCount: '262', decayType: ['a']},
    {nucleodeCount: '263', decayType: ['a']},
    {nucleodeCount: '263m', decayType: ['a']},
    {nucleodeCount: '265', decayType: ['a']},
    {nucleodeCount: '265m', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['a']},
    {nucleodeCount: 'None', decayType: ['a']},
]
