const selenium = [
    {nucleodeCount: '63', decayType: ['[[beta decay', 'b<sup>+</sup>]], [[proton emission', 'p]] (89%)']},
    {nucleodeCount: '63', decayType: ['b<sup>+</sup> (11%)']},
    {nucleodeCount: '63', decayType: ['2p? (<0.5%)']},
    {nucleodeCount: '64', decayType: ['b<sup>+</sup>?']},
    {nucleodeCount: '64', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '65', decayType: ['b<sup>+</sup>, p (87%)']},
    {nucleodeCount: '65', decayType: ['b<sup>+</sup> (13%)']},
    {nucleodeCount: '66', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '66', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '67', decayType: ['b<sup>+</sup> (99.5%)']},
    {nucleodeCount: '67', decayType: ['b<sup>+</sup>, p (0.5%)']},
    {nucleodeCount: '68', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '69', decayType: ['b<sup>+</sup> (99.95%)']},
    {nucleodeCount: '69', decayType: ['b<sup>+</sup>, p (.052%)']},
    {nucleodeCount: '69m1', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '69m2', decayType: ['IT']},
    {nucleodeCount: '70', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '71', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '71m1', decayType: ['IT']},
    {nucleodeCount: '71m2', decayType: ['IT']},
    {nucleodeCount: '72', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '73', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '73m', decayType: ['IT (72.6%)']},
    {nucleodeCount: '73m', decayType: ['b<sup>+</sup> (27.4%)']},
    {nucleodeCount: '74', decayType: ['73.922475933(15)']},
    {nucleodeCount: '75', decayType: ['EC']},
    {nucleodeCount: '77m', decayType: ['IT']},
    {nucleodeCount: '79', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '79m', decayType: ['IT (99.94%)']},
    {nucleodeCount: '79m', decayType: ['b<sup>-</sup> (0.056%)']},
    {nucleodeCount: '80', decayType: ['79.9165218(10)']},
    {nucleodeCount: '81', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '81m', decayType: ['IT (99.95%)']},
    {nucleodeCount: '81m', decayType: ['b<sup>-</sup> (.051%)']},
    {nucleodeCount: '82', decayType: ['[[double beta decay', 'b<sup>-</sup>b<sup>-</sup>]]']},
    {nucleodeCount: '83', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '83m', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '84', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '85', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '86', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]]?']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup> (99.50%)']},
    {nucleodeCount: '87', decayType: ['b<sup>-</sup>, n (0.60%)']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup> (99.01%)']},
    {nucleodeCount: '88', decayType: ['b<sup>-</sup>, n (0.99%)']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup> (92.2%)']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup>, n (7.8%)']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup> (79%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>, n (21%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '92m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '93m', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>, 2n?']},
]
