const silicon = [
    {nucleodeCount: '22', decayType: ['[[Beta decay', 'b<sup>+</sup>]], [[proton emission', 'p]] (62%)']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup> (37%)']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup>, 2p (0.7%)']},
    {nucleodeCount: '23', decayType: ['b<sup>+</sup>, p (88%)']},
    {nucleodeCount: '23', decayType: ['b<sup>+</sup> (8%)']},
    {nucleodeCount: '23', decayType: ['b<sup>+</sup>, 2p (3.6%)']},
    {nucleodeCount: '24', decayType: ['b<sup>+</sup> (65.5%)']},
    {nucleodeCount: '24', decayType: ['b<sup>+</sup>, p (34.5%)']},
    {nucleodeCount: '25', decayType: ['b<sup>+</sup> (65%)']},
    {nucleodeCount: '25', decayType: ['b<sup>+</sup>, p (35%)']},
    {nucleodeCount: '26', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '27', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '34m', decayType: ['IT']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]]?']},
    {nucleodeCount: '36', decayType: ['b<sup>-</sup> (88%)']},
    {nucleodeCount: '36', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (12%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup> (83%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>, n (17%)']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '38', decayType: ['b<sup>-</sup> (75%)']},
    {nucleodeCount: '38', decayType: ['b<sup>-</sup>, n (25%)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup> (67%)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>, n (33%)']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup> (62%)']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup>, n (38%)']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>, n (>55%)']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup> (<45%)']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup> (51%)']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup>, n (48%)']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup>, 2n (1%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup>, n (52%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup> (27%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup>, 2n (21%)']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup>, 2n?']},
]
