const silicon = [
    {nucleodeCount: '22', decayType: ['b+, p']},
    {nucleodeCount: '22', decayType: ['b+']},
    {nucleodeCount: '22', decayType: ['b+, 2p']},
    {nucleodeCount: '23', decayType: ['b+, p']},
    {nucleodeCount: '23', decayType: ['b+']},
    {nucleodeCount: '23', decayType: ['b+, 2p']},
    {nucleodeCount: '24', decayType: ['b+']},
    {nucleodeCount: '24', decayType: ['b+, p']},
    {nucleodeCount: '25', decayType: ['b+']},
    {nucleodeCount: '25', decayType: ['b+, p']},
    {nucleodeCount: '26', decayType: ['b+']},
    {nucleodeCount: '27', decayType: ['b+']},
    {nucleodeCount: '31', decayType: ['b-']},
    {nucleodeCount: '32', decayType: ['b-']},
    {nucleodeCount: '33', decayType: ['b-']},
    {nucleodeCount: '34', decayType: ['b-']},
    {nucleodeCount: '34m', decayType: ['IT']},
    {nucleodeCount: '35', decayType: ['b-']},
    {nucleodeCount: '35', decayType: ['b-, n']},
    {nucleodeCount: '36', decayType: ['b-']},
    {nucleodeCount: '36', decayType: ['b-, n']},
    {nucleodeCount: '37', decayType: ['b-']},
    {nucleodeCount: '37', decayType: ['b-, n']},
    {nucleodeCount: '37', decayType: ['b-, 2n']},
    {nucleodeCount: '38', decayType: ['b-']},
    {nucleodeCount: '38', decayType: ['b-, n']},
    {nucleodeCount: '39', decayType: ['b-']},
    {nucleodeCount: '39', decayType: ['b-, n']},
    {nucleodeCount: '39', decayType: ['b-, 2n']},
    {nucleodeCount: '40', decayType: ['b-']},
    {nucleodeCount: '40', decayType: ['b-, n']},
    {nucleodeCount: '40', decayType: ['b-, 2n']},
    {nucleodeCount: '41', decayType: ['b-, n']},
    {nucleodeCount: '41', decayType: ['b-']},
    {nucleodeCount: '41', decayType: ['b-, 2n']},
    {nucleodeCount: '42', decayType: ['b-']},
    {nucleodeCount: '42', decayType: ['b-, n']},
    {nucleodeCount: '42', decayType: ['b-, 2n']},
    {nucleodeCount: '43', decayType: ['b-, n']},
    {nucleodeCount: '43', decayType: ['b-']},
    {nucleodeCount: '43', decayType: ['b-, 2n']},
    {nucleodeCount: '44', decayType: ['b-']},
    {nucleodeCount: '44', decayType: ['b-, n']},
    {nucleodeCount: '44', decayType: ['b-, 2n']},
]
