const silver = [
    {nucleodeCount: '92', decayType: ['b+']},
    {nucleodeCount: '92', decayType: ['p']},
    {nucleodeCount: '93', decayType: ['b+']},
    {nucleodeCount: '93', decayType: ['p']},
    {nucleodeCount: '93', decayType: ['b+, p']},
    {nucleodeCount: '94', decayType: ['b+']},
    {nucleodeCount: '94', decayType: ['b+, p']},
    {nucleodeCount: '94m1', decayType: ['b+']},
    {nucleodeCount: '94m1', decayType: ['b+, p']},
    {nucleodeCount: '94m2', decayType: ['b+']},
    {nucleodeCount: '94m2', decayType: ['b+, p']},
    {nucleodeCount: '94m2', decayType: ['p']},
    {nucleodeCount: '94m2', decayType: ['2p']},
    {nucleodeCount: '95', decayType: ['b+']},
    {nucleodeCount: '95', decayType: ['b+, p']},
    {nucleodeCount: '95m1', decayType: ['IT']},
    {nucleodeCount: '95m2', decayType: ['IT']},
    {nucleodeCount: '95m3', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b+']},
    {nucleodeCount: '96', decayType: ['b+, p']},
    {nucleodeCount: '96m1', decayType: ['b+']},
    {nucleodeCount: '96m1', decayType: ['b+, p']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '96m3', decayType: ['IT']},
    {nucleodeCount: '96m4', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b+']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b+']},
    {nucleodeCount: '98', decayType: ['b+, p']},
    {nucleodeCount: '98m', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b+']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['b+']},
    {nucleodeCount: '100m', decayType: ['IT']},
    {nucleodeCount: '100m', decayType: ['b+']},
    {nucleodeCount: '101', decayType: ['b+']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b+']},
    {nucleodeCount: '102m', decayType: ['b+']},
    {nucleodeCount: '102m', decayType: ['IT']},
    {nucleodeCount: '103', decayType: ['b+']},
    {nucleodeCount: '103m', decayType: ['IT']},
    {nucleodeCount: '104', decayType: ['b+']},
    {nucleodeCount: '104m', decayType: ['b+']},
    {nucleodeCount: '104m', decayType: ['IT']},
    {nucleodeCount: '105', decayType: ['b+']},
    {nucleodeCount: '105m', decayType: ['IT']},
    {nucleodeCount: '105m', decayType: ['b+']},
    {nucleodeCount: '106', decayType: ['b+']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '106m', decayType: ['b+']},
    {nucleodeCount: '106m', decayType: ['IT']},
    {nucleodeCount: '107m', decayType: ['IT']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '108', decayType: ['EC']},
    {nucleodeCount: '108', decayType: ['b+']},
    {nucleodeCount: '108m', decayType: ['EC']},
    {nucleodeCount: '108m', decayType: ['IT']},
    {nucleodeCount: '109m', decayType: ['IT']},
    {nucleodeCount: '110', decayType: ['b-']},
    {nucleodeCount: '110', decayType: ['EC']},
    {nucleodeCount: '110m1', decayType: ['IT']},
    {nucleodeCount: '110m2', decayType: ['b-']},
    {nucleodeCount: '110m2', decayType: ['IT']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '111m', decayType: ['IT']},
    {nucleodeCount: '111m', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '113m', decayType: ['b-']},
    {nucleodeCount: '114', decayType: ['b-']},
    {nucleodeCount: '114m', decayType: ['IT']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['b-']},
    {nucleodeCount: '115m', decayType: ['IT']},
    {nucleodeCount: '116', decayType: ['b-']},
    {nucleodeCount: '116m1', decayType: ['b-']},
    {nucleodeCount: '116m1', decayType: ['IT']},
    {nucleodeCount: '116m2', decayType: ['b-']},
    {nucleodeCount: '116m2', decayType: ['IT']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['b-']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '118m1', decayType: ['IT']},
    {nucleodeCount: '118m2', decayType: ['b-']},
    {nucleodeCount: '118m2', decayType: ['IT']},
    {nucleodeCount: '118m3', decayType: ['IT']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '119m', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-, n']},
    {nucleodeCount: '120m1', decayType: ['b-']},
    {nucleodeCount: '120m1', decayType: ['IT']},
    {nucleodeCount: '120m1', decayType: ['b-, n']},
    {nucleodeCount: '120m2', decayType: ['IT']},
    {nucleodeCount: '120m2', decayType: ['b-']},
    {nucleodeCount: '120m2', decayType: ['b-, n']},
    {nucleodeCount: '121', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-, n']},
    {nucleodeCount: '122', decayType: ['b-']},
    {nucleodeCount: '122', decayType: ['b-, n']},
    {nucleodeCount: '122m1', decayType: ['b-']},
    {nucleodeCount: '122m1', decayType: ['b-, n']},
    {nucleodeCount: '122m1', decayType: ['IT']},
    {nucleodeCount: '122m2', decayType: ['IT']},
    {nucleodeCount: '123', decayType: ['b-']},
    {nucleodeCount: '123', decayType: ['b-, n']},
    {nucleodeCount: '123m1', decayType: ['b-']},
    {nucleodeCount: '123m1', decayType: ['b-, n']},
    {nucleodeCount: '123m2', decayType: ['IT']},
    {nucleodeCount: '123m3', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['b-']},
    {nucleodeCount: '124', decayType: ['b-, n']},
    {nucleodeCount: '124m1', decayType: ['b-']},
    {nucleodeCount: '124m1', decayType: ['b-, n']},
    {nucleodeCount: '124m2', decayType: ['IT']},
    {nucleodeCount: '124m3', decayType: ['IT']},
    {nucleodeCount: '125', decayType: ['b-']},
    {nucleodeCount: '125', decayType: ['b-, n']},
    {nucleodeCount: '125m1', decayType: ['b-']},
    {nucleodeCount: '125m1', decayType: ['IT']},
    {nucleodeCount: '125m1', decayType: ['b-, n']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['b-']},
    {nucleodeCount: '126', decayType: ['b-, n']},
    {nucleodeCount: '126m1', decayType: ['b-']},
    {nucleodeCount: '126m1', decayType: ['IT']},
    {nucleodeCount: '126m1', decayType: ['b-, n']},
    {nucleodeCount: '126m2', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127', decayType: ['b-, n']},
    {nucleodeCount: '127m', decayType: ['b-']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128', decayType: ['b-']},
    {nucleodeCount: '128', decayType: ['b-, n']},
    {nucleodeCount: '128', decayType: ['b-, 2n']},
    {nucleodeCount: '129', decayType: ['b-']},
    {nucleodeCount: '129', decayType: ['b-, n']},
    {nucleodeCount: '130', decayType: ['b-']},
    {nucleodeCount: '130', decayType: ['b-, n']},
    {nucleodeCount: '130', decayType: ['b-, 2n']},
    {nucleodeCount: '131', decayType: ['b-']},
    {nucleodeCount: '131', decayType: ['b-, 2n']},
    {nucleodeCount: '131', decayType: ['b-, n']},
    {nucleodeCount: '132', decayType: ['b-']},
    {nucleodeCount: '132', decayType: ['b-, n']},
    {nucleodeCount: '132', decayType: ['b-, 2n']},
]
