const sodium = [
    {nucleodeCount: '17', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '18', decayType: ['p ?<ref group="n" name="decay mode 2">Decay mode shown has been observed, but its intensity is not known experimentally.</ref>']},
    {nucleodeCount: '19', decayType: ['p']},
    {nucleodeCount: '20', decayType: ['b<sup>+</sup> ({{val', '75.0', '(4)', 'u=%}})']},
    {nucleodeCount: '20', decayType: ['b<sup>+</sup>a ({{val', '25.0', '(4)', 'u=%}})']},
    {nucleodeCount: '21', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '22', decayType: ['b<sup>+</sup> ({{val', '90.57', '(8)', 'u=%}})']},
    {nucleodeCount: '22', decayType: ['[[Electron capture', 'e]] ({{val', '9.43', '(6)', 'u=%}})']},
    {nucleodeCount: '22m1', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '22m2', decayType: ['IT']},
    {nucleodeCount: '24', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '24m', decayType: ['IT ({{val', '99.95', 'u=%}})']},
    {nucleodeCount: '24m', decayType: ['b<sup>-</sup> ({{val', '0.05', 'u=%}})']},
    {nucleodeCount: '25', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '26', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '26m', decayType: ['IT']},
    {nucleodeCount: '27', decayType: ['b<sup>-</sup> ({{val', '99.902', '(24)', 'u=%}})']},
    {nucleodeCount: '27', decayType: ['[[Neutron emission#Beta-delayed neutron emission', 'b<sup>-</sup>n]] ({{val', '0.098', '(24)', 'u=%}})']},
    {nucleodeCount: '28', decayType: ['b<sup>-</sup> ({{val', '99.42', '(12)', 'u=%}})']},
    {nucleodeCount: '28', decayType: ['b<sup>-</sup>n ({{val', '0.58', '(12)', 'u=%}})']},
    {nucleodeCount: '29', decayType: ['b<sup>-</sup> ({{val', '78', 'u=%}})']},
    {nucleodeCount: '29', decayType: ['b<sup>-</sup>n ({{val', '22', '(3)', 'u=%}})']},
    {nucleodeCount: '29', decayType: ['b<sup>-</sup>2n ?<ref group="n" name="decay mode 1">Decay mode shown is energetically allowed, but has not been experimentally observed to occur in this nuclide.</ref>']},
    {nucleodeCount: '30', decayType: ['b<sup>-</sup> ({{val', '70.2', '(2.2)', 'u=%}})']},
    {nucleodeCount: '30', decayType: ['b<sup>-</sup>n ({{val', '28.6', '(2.2)', 'u=%}})']},
    {nucleodeCount: '30', decayType: ['b<sup>-</sup>2n ({{val', '1.24', '(19)', 'u=%}})']},
    {nucleodeCount: '30', decayType: ['b<sup>-</sup>a ({{val', '5.5e-5', '(2)', 'u=%}})']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup> (> {{val', '63.2', '(3.5)', 'u=%}})']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup>n ({{val', '36.0', '(3.5)', 'u=%}})']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup>2n ({{val', '0.73', '(9)', 'u=%}})']},
    {nucleodeCount: '31', decayType: ['b<sup>-</sup>3n (< {{val', '0.05', 'u=%}})']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup> ({{val', '66.4', '(6.2)', 'u=%}})']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup>n ({{val', '26', '(6)', 'u=%}})']},
    {nucleodeCount: '32', decayType: ['b<sup>-</sup>2n ({{val', '7.6', '(1.5)', 'u=%}})']},
    {nucleodeCount: '32m', decayType: ['IT']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup>n ({{val', '47', '(6)', 'u=%}})']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup> ({{val', '40.0', '(6.7)', 'u=%}})']},
    {nucleodeCount: '33', decayType: ['b<sup>-</sup>2n ({{val', '13', '(3)', 'u=%}})']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup>2n (~{{val', '50', 'u=%}})']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup> (~{{val', '35', 'u=%}})']},
    {nucleodeCount: '34', decayType: ['b<sup>-</sup>n (~{{val', '15', 'u=%}})']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>n ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>2n ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup> ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>n ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>2n ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup> ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>n ?<ref group="n" name="decay mode 1" />']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>2n ?<ref group="n" name="decay mode 1" />']},
]
