const strontium = [
    {nucleodeCount: '73', decayType: ['[[beta decay', 'b<sup>+</sup>]], [[proton emission', 'p]] (63%)']},
    {nucleodeCount: '73', decayType: ['b<sup>+</sup> (37%)']},
    {nucleodeCount: '74', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '75', decayType: ['b<sup>+</sup> (94.8%)']},
    {nucleodeCount: '75', decayType: ['b<sup>+</sup>, p (5.2%)']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup>, p (0.0034%)']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup> (99.92%)']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup>, p (0.08%)']},
    {nucleodeCount: '78', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '79', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '80', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '81', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '81m1', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '82', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '83', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['83.9134191(13)']},
    {nucleodeCount: '85', decayType: ['EC']},
    {nucleodeCount: '85m', decayType: ['IT (86.6%)']},
    {nucleodeCount: '85m', decayType: ['b<sup>+</sup> (13.4%)']},
    {nucleodeCount: '86m', decayType: ['IT']},
    {nucleodeCount: '87m', decayType: ['IT (99.70%)']},
    {nucleodeCount: '87m', decayType: ['EC (0.30%)']},
    {nucleodeCount: '89', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup> (99.98%)']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (0.02%)']},
    {nucleodeCount: '97m1', decayType: ['IT']},
    {nucleodeCount: '97m2', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup> (99.77%)']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, n (0.23%)']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup> (99.90%)']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup>, n (0.100%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup> (98.89%)']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>, n (1.11%)']},
    {nucleodeCount: '100m', decayType: ['IT']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup> (97.25%)']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup>, n (2.75%)']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup> (94.5%)']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup>, n (5.5%)']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>']},
]
