const strontium = [
    {nucleodeCount: '73', decayType: ['b+, p']},
    {nucleodeCount: '73', decayType: ['b+']},
    {nucleodeCount: '74', decayType: ['b+']},
    {nucleodeCount: '75', decayType: ['b+']},
    {nucleodeCount: '75', decayType: ['b+, p']},
    {nucleodeCount: '76', decayType: ['b+']},
    {nucleodeCount: '76', decayType: ['b+, p']},
    {nucleodeCount: '77', decayType: ['b+']},
    {nucleodeCount: '77', decayType: ['b+, p']},
    {nucleodeCount: '78', decayType: ['b+']},
    {nucleodeCount: '79', decayType: ['b+']},
    {nucleodeCount: '80', decayType: ['b+']},
    {nucleodeCount: '81', decayType: ['b+']},
    {nucleodeCount: '81m1', decayType: ['IT']},
    {nucleodeCount: '82', decayType: ['EC']},
    {nucleodeCount: '83', decayType: ['b+']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['83.9134191(13)']},
    {nucleodeCount: '85', decayType: ['EC']},
    {nucleodeCount: '85m', decayType: ['IT']},
    {nucleodeCount: '85m', decayType: ['b+']},
    {nucleodeCount: '86m', decayType: ['IT']},
    {nucleodeCount: '87m', decayType: ['IT']},
    {nucleodeCount: '87m', decayType: ['EC']},
    {nucleodeCount: '89', decayType: ['b-']},
    {nucleodeCount: '90', decayType: ['b-']},
    {nucleodeCount: '91', decayType: ['b-']},
    {nucleodeCount: '92', decayType: ['b-']},
    {nucleodeCount: '93', decayType: ['b-']},
    {nucleodeCount: '94', decayType: ['b-']},
    {nucleodeCount: '95', decayType: ['b-']},
    {nucleodeCount: '96', decayType: ['b-']},
    {nucleodeCount: '97', decayType: ['b-']},
    {nucleodeCount: '97', decayType: ['b-, n']},
    {nucleodeCount: '97m1', decayType: ['IT']},
    {nucleodeCount: '97m2', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b-']},
    {nucleodeCount: '98', decayType: ['b-, n']},
    {nucleodeCount: '99', decayType: ['b-']},
    {nucleodeCount: '99', decayType: ['b-, n']},
    {nucleodeCount: '100', decayType: ['b-']},
    {nucleodeCount: '100', decayType: ['b-, n']},
    {nucleodeCount: '100m', decayType: ['IT']},
    {nucleodeCount: '101', decayType: ['b-']},
    {nucleodeCount: '101', decayType: ['b-, n']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '102', decayType: ['b-, n']},
    {nucleodeCount: '103', decayType: ['b-']},
    {nucleodeCount: '104', decayType: ['b-']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '106', decayType: ['b-']},
]
