const sulfur = [
    {nucleodeCount: '27', decayType: ['[[Beta decay', 'b<sup>+</sup>, p]] (61%)']},
    {nucleodeCount: '27', decayType: ['b<sup>+</sup> (36%)']},
    {nucleodeCount: '27', decayType: ['b<sup>+</sup>, 2p (3.0%)']},
    {nucleodeCount: '28', decayType: ['b<sup>+</sup> (79.3%)']},
    {nucleodeCount: '28', decayType: ['b<sup>+</sup>, p (20.7%)']},
    {nucleodeCount: '29', decayType: ['b<sup>+</sup> (53.6%)']},
    {nucleodeCount: '29', decayType: ['b<sup>+</sup>, p (46.4%)']},
    {nucleodeCount: '30', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '31', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '35', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '37', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '38', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '39', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '40', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '41', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup> (>96%)']},
    {nucleodeCount: '42', decayType: ['b<sup>-</sup>, n (<1%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup> (60%)']},
    {nucleodeCount: '43', decayType: ['b<sup>-</sup>, n (40%)']},
    {nucleodeCount: '43m', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup> (82%)']},
    {nucleodeCount: '44', decayType: ['b<sup>-</sup>, n (18%)']},
    {nucleodeCount: '44m', decayType: ['IT']},
    {nucleodeCount: '45', decayType: ['b<sup>-</sup>, n (54%)']},
    {nucleodeCount: '45', decayType: ['b<sup>-</sup> (46%)']},
    {nucleodeCount: '46', decayType: ['b<sup>-</sup>']},
]
