const sulfur = [
    {nucleodeCount: '27', decayType: ['[[Beta decay', 'b+, p]]']},
    {nucleodeCount: '27', decayType: ['b+']},
    {nucleodeCount: '27', decayType: ['b+, 2p']},
    {nucleodeCount: '28', decayType: ['b+']},
    {nucleodeCount: '28', decayType: ['b+, p']},
    {nucleodeCount: '29', decayType: ['b+']},
    {nucleodeCount: '29', decayType: ['b+, p']},
    {nucleodeCount: '30', decayType: ['b+']},
    {nucleodeCount: '31', decayType: ['b+']},
    {nucleodeCount: '35', decayType: ['b-']},
    {nucleodeCount: '37', decayType: ['b-']},
    {nucleodeCount: '38', decayType: ['b-']},
    {nucleodeCount: '39', decayType: ['b-']},
    {nucleodeCount: '40', decayType: ['b-']},
    {nucleodeCount: '41', decayType: ['b-']},
    {nucleodeCount: '42', decayType: ['b-']},
    {nucleodeCount: '42', decayType: ['b-, n']},
    {nucleodeCount: '43', decayType: ['b-']},
    {nucleodeCount: '43', decayType: ['b-, n']},
    {nucleodeCount: '43m', decayType: ['IT']},
    {nucleodeCount: '44', decayType: ['b-']},
    {nucleodeCount: '44', decayType: ['b-, n']},
    {nucleodeCount: '44m', decayType: ['IT']},
    {nucleodeCount: '45', decayType: ['b-, n']},
    {nucleodeCount: '45', decayType: ['b-']},
    {nucleodeCount: '46', decayType: ['b-']},
]
