const technetium = [
    {nucleodeCount: '86', decayType: ['b+']},
    {nucleodeCount: '86m', decayType: ['IT']},
    {nucleodeCount: '87', decayType: ['b+']},
    {nucleodeCount: '87', decayType: ['b+, p']},
    {nucleodeCount: '87m', decayType: ['IT']},
    {nucleodeCount: '88', decayType: ['b+']},
    {nucleodeCount: '88m1', decayType: ['b+']},
    {nucleodeCount: '88m2', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b+']},
    {nucleodeCount: '89m', decayType: ['b+']},
    {nucleodeCount: '90', decayType: ['b+']},
    {nucleodeCount: '90m', decayType: ['b+']},
    {nucleodeCount: '91', decayType: ['b+']},
    {nucleodeCount: '91m', decayType: ['b+']},
    {nucleodeCount: '92', decayType: ['b+']},
    {nucleodeCount: '92m1', decayType: ['IT']},
    {nucleodeCount: '92m2', decayType: ['IT']},
    {nucleodeCount: '92m3', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b+']},
    {nucleodeCount: '93m1', decayType: ['IT']},
    {nucleodeCount: '93m1', decayType: ['b+']},
    {nucleodeCount: '93m2', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b+']},
    {nucleodeCount: '94m', decayType: ['b+']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b+']},
    {nucleodeCount: '95m', decayType: ['b+']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b+']},
    {nucleodeCount: '96m', decayType: ['IT']},
    {nucleodeCount: '96m', decayType: ['b+']},
    {nucleodeCount: '97', decayType: ['EC']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '97m', decayType: ['EC']},
    {nucleodeCount: '98', decayType: ['b-']},
    {nucleodeCount: '98m', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b-']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '99m', decayType: ['b-']},
    {nucleodeCount: '100', decayType: ['b-']},
    {nucleodeCount: '100', decayType: ['EC']},
    {nucleodeCount: '100m1', decayType: ['IT']},
    {nucleodeCount: '100m2', decayType: ['IT']},
    {nucleodeCount: '101', decayType: ['b-']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '102m', decayType: ['b-']},
    {nucleodeCount: '103', decayType: ['b-']},
    {nucleodeCount: '104', decayType: ['b-']},
    {nucleodeCount: '104m1', decayType: ['IT']},
    {nucleodeCount: '104m2', decayType: ['IT']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '107m1', decayType: ['IT']},
    {nucleodeCount: '107m2', decayType: ['IT']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '109', decayType: ['b-, n']},
    {nucleodeCount: '110', decayType: ['b-']},
    {nucleodeCount: '110', decayType: ['b-, n']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '111', decayType: ['b-, n']},
    {nucleodeCount: '112', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-, n']},
    {nucleodeCount: '112m', decayType: ['IT']},
    {nucleodeCount: '113', decayType: ['b-']},
    {nucleodeCount: '113', decayType: ['b-, n']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b-']},
    {nucleodeCount: '114', decayType: ['b-, n']},
    {nucleodeCount: '114m', decayType: ['b-']},
    {nucleodeCount: '114m', decayType: ['b-, n']},
    {nucleodeCount: '115', decayType: ['b-']},
    {nucleodeCount: '116', decayType: ['b-']},
    {nucleodeCount: '117', decayType: ['b-']},
    {nucleodeCount: '118', decayType: ['b-']},
    {nucleodeCount: '119', decayType: ['b-']},
    {nucleodeCount: '120', decayType: ['b-']},
    {nucleodeCount: '121', decayType: ['b-']},
]
