const tellurium = [
    {nucleodeCount: '104', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '105', decayType: ['a']},
    {nucleodeCount: '106', decayType: ['a']},
    {nucleodeCount: '107', decayType: ['a (70%)']},
    {nucleodeCount: '107', decayType: ['[[beta decay', 'b<sup>+</sup>]] (30%)']},
    {nucleodeCount: '108', decayType: ['a (49%)']},
    {nucleodeCount: '108', decayType: ['b<sup>+</sup> (48.6%)']},
    {nucleodeCount: '108', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (2.4%)']},
    {nucleodeCount: '108', decayType: ['b<sup>+</sup>, a (<0.065%)']},
    {nucleodeCount: '109', decayType: ['b<sup>+</sup> (86.7%)']},
    {nucleodeCount: '109', decayType: ['b<sup>+</sup>, p (9.4%)']},
    {nucleodeCount: '109', decayType: ['a (3.9%)']},
    {nucleodeCount: '109', decayType: ['b<sup>+</sup>, a (<0.0049%)']},
    {nucleodeCount: '110', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '111', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '111', decayType: ['b<sup>+</sup>, p (?%)']},
    {nucleodeCount: '112', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '113', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '114', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '115', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '115m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '115m2', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '116', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '117', decayType: ['[[electron capture', 'EC]] (75%)']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['EC']},
    {nucleodeCount: '119', decayType: ['EC (97.94%)']},
    {nucleodeCount: '119m', decayType: ['EC (99.59%)']},
    {nucleodeCount: '121', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '121m', decayType: ['IT (88.6%)']},
    {nucleodeCount: '121m', decayType: ['b<sup>+</sup> (11.4%)']},
    {nucleodeCount: '123m', decayType: ['IT']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '127m', decayType: ['IT (97.86%)']},
    {nucleodeCount: '127m', decayType: ['b<sup>-</sup> (2.14%)']},
    {nucleodeCount: '128', decayType: ['b<sup>-</sup>b<sup>-</sup>']},
    {nucleodeCount: '128m', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '129m', decayType: ['IT (64%)']},
    {nucleodeCount: '129m', decayType: ['b<sup>-</sup> (36%)']},
    {nucleodeCount: '130', decayType: ['b<sup>-</sup>b<sup>-</sup>']},
    {nucleodeCount: '130m1', decayType: ['IT']},
    {nucleodeCount: '130m2', decayType: ['IT']},
    {nucleodeCount: '130m3', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '131m1', decayType: ['b<sup>-</sup> (74.1%)']},
    {nucleodeCount: '131m1', decayType: ['IT (25.9%)']},
    {nucleodeCount: '131m2', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '132m1', decayType: ['IT']},
    {nucleodeCount: '132m2', decayType: ['IT']},
    {nucleodeCount: '132m3', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '133m1', decayType: ['b<sup>-</sup> (83.5%)']},
    {nucleodeCount: '133m1', decayType: ['IT (16.5%)']},
    {nucleodeCount: '133m2', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['b<sup>-</sup> (98.63%)']},
    {nucleodeCount: '136', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (1.37%)']},
    {nucleodeCount: '137', decayType: ['b<sup>-</sup> (97.06%)']},
    {nucleodeCount: '137', decayType: ['b<sup>-</sup>, n (2.94%)']},
    {nucleodeCount: '138', decayType: ['b<sup>-</sup> (95.20%)']},
    {nucleodeCount: '138', decayType: ['b<sup>-</sup>, n (4.80%)']},
    {nucleodeCount: '139', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '140', decayType: ['b<sup>-</sup> (?%)']},
    {nucleodeCount: '140', decayType: ['b<sup>-</sup>, n (?%)']},
    {nucleodeCount: '141', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '142', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '143', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '144', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '145', decayType: ['b<sup>-</sup>']},
]
