const tellurium = [
    {nucleodeCount: '104', decayType: ['a']},
    {nucleodeCount: '105', decayType: ['a']},
    {nucleodeCount: '106', decayType: ['a']},
    {nucleodeCount: '107', decayType: ['a']},
    {nucleodeCount: '107', decayType: ['b+']},
    {nucleodeCount: '108', decayType: ['a']},
    {nucleodeCount: '108', decayType: ['b+']},
    {nucleodeCount: '108', decayType: ['b+, p']},
    {nucleodeCount: '108', decayType: ['b+, a']},
    {nucleodeCount: '109', decayType: ['b+']},
    {nucleodeCount: '109', decayType: ['b+, p']},
    {nucleodeCount: '109', decayType: ['a']},
    {nucleodeCount: '109', decayType: ['b+, a']},
    {nucleodeCount: '110', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['b+, p']},
    {nucleodeCount: '112', decayType: ['b+']},
    {nucleodeCount: '113', decayType: ['b+']},
    {nucleodeCount: '114', decayType: ['b+']},
    {nucleodeCount: '115', decayType: ['b+']},
    {nucleodeCount: '115m1', decayType: ['b+']},
    {nucleodeCount: '115m2', decayType: ['IT']},
    {nucleodeCount: '116', decayType: ['b+']},
    {nucleodeCount: '117', decayType: ['EC']},
    {nucleodeCount: '117m', decayType: ['IT']},
    {nucleodeCount: '118', decayType: ['EC']},
    {nucleodeCount: '119', decayType: ['EC']},
    {nucleodeCount: '119m', decayType: ['EC']},
    {nucleodeCount: '121', decayType: ['b+']},
    {nucleodeCount: '121m', decayType: ['IT']},
    {nucleodeCount: '121m', decayType: ['b+']},
    {nucleodeCount: '123m', decayType: ['IT']},
    {nucleodeCount: '125m', decayType: ['IT']},
    {nucleodeCount: '127', decayType: ['b-']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '127m', decayType: ['b-']},
    {nucleodeCount: '128', decayType: ['b-b-']},
    {nucleodeCount: '128m', decayType: ['IT']},
    {nucleodeCount: '129', decayType: ['b-']},
    {nucleodeCount: '129m', decayType: ['IT']},
    {nucleodeCount: '129m', decayType: ['b-']},
    {nucleodeCount: '130', decayType: ['b-b-']},
    {nucleodeCount: '130m1', decayType: ['IT']},
    {nucleodeCount: '130m2', decayType: ['IT']},
    {nucleodeCount: '130m3', decayType: ['IT']},
    {nucleodeCount: '131', decayType: ['b-']},
    {nucleodeCount: '131m1', decayType: ['b-']},
    {nucleodeCount: '131m1', decayType: ['IT']},
    {nucleodeCount: '131m2', decayType: ['IT']},
    {nucleodeCount: '132', decayType: ['b-']},
    {nucleodeCount: '132m1', decayType: ['IT']},
    {nucleodeCount: '132m2', decayType: ['IT']},
    {nucleodeCount: '132m3', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b-']},
    {nucleodeCount: '133m1', decayType: ['b-']},
    {nucleodeCount: '133m1', decayType: ['IT']},
    {nucleodeCount: '133m2', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['b-']},
    {nucleodeCount: '134m', decayType: ['IT']},
    {nucleodeCount: 'None', decayType: ['b-']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['b-']},
    {nucleodeCount: '136', decayType: ['b-, n']},
    {nucleodeCount: '137', decayType: ['b-']},
    {nucleodeCount: '137', decayType: ['b-, n']},
    {nucleodeCount: '138', decayType: ['b-']},
    {nucleodeCount: '138', decayType: ['b-, n']},
    {nucleodeCount: '139', decayType: ['b-']},
    {nucleodeCount: '140', decayType: ['b-']},
    {nucleodeCount: '140', decayType: ['b-, n']},
    {nucleodeCount: '141', decayType: ['b-']},
    {nucleodeCount: '142', decayType: ['b-']},
    {nucleodeCount: '143', decayType: ['b-']},
    {nucleodeCount: '144', decayType: ['b-']},
    {nucleodeCount: '145', decayType: ['b-']},
]
