const terbium = [
    {nucleodeCount: '135', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '139', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: '140', decayType: ['b<sup>+</sup> (99.74%)']},
    {nucleodeCount: '140', decayType: ['[[electron capture', 'EC]] (<3%)']},
    {nucleodeCount: '140', decayType: ['b<sup>+</sup>, p (0.26%)']},
    {nucleodeCount: '141', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '141m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '142', decayType: ['b<sup>+</sup> (96.8%)']},
    {nucleodeCount: '142', decayType: ['EC (3.2%)']},
    {nucleodeCount: '142', decayType: ['b<sup>+</sup>, p (0.0022%)']},
    {nucleodeCount: '142m1', decayType: ['[[Isomeric transition', 'IT]]']},
    {nucleodeCount: '142m2', decayType: ['IT']},
    {nucleodeCount: '143', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '144', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '144m1', decayType: ['IT (66%)']},
    {nucleodeCount: '144m1', decayType: ['b<sup>+</sup> (34%)']},
    {nucleodeCount: '144m2', decayType: ['IT']},
    {nucleodeCount: '144m3', decayType: ['IT']},
    {nucleodeCount: '144m4', decayType: ['IT']},
    {nucleodeCount: '145', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '146m2', decayType: ['IT']},
    {nucleodeCount: '147', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '147m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '148', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '148m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '148m2', decayType: ['IT']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup> (83.3%)']},
    {nucleodeCount: '149', decayType: ['[[alpha decay', 'a]] (16.7%)']},
    {nucleodeCount: '149m', decayType: ['b<sup>+</sup> (99.98%)']},
    {nucleodeCount: '149m', decayType: ['a (0.022%)']},
    {nucleodeCount: '150', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '151', decayType: ['b<sup>+</sup> (99.99%)']},
    {nucleodeCount: '151', decayType: ['a (.0095%)']},
    {nucleodeCount: '151m', decayType: ['IT (93.4%)']},
    {nucleodeCount: '151m', decayType: ['b<sup>+</sup> (6.6%)']},
    {nucleodeCount: '152', decayType: ['EC (83%)<ref name="152tb"/>']},
    {nucleodeCount: '152', decayType: ['a (<7x10<sup>-7</sup>%)<ref>{{cite web', 'url=https://www.nndc.bnl.gov/nudat3/getdataset.jsp?nucleus=152Tb&unc=NDS', 'title=Adopted Levels for <sup>152</sup>Tb', 'publisher=NNDC Chart of Nuclides}}</ref>']},
    {nucleodeCount: '152m1', decayType: ['IT']},
    {nucleodeCount: '152m2', decayType: ['IT (78.9%)']},
    {nucleodeCount: '152m2', decayType: ['b<sup>+</sup> (21.1%)']},
    {nucleodeCount: '153', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '153m', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '154m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '154m2', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '154m3', decayType: ['IT']},
    {nucleodeCount: '155', decayType: ['EC']},
    {nucleodeCount: '156', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '156m1', decayType: ['IT']},
    {nucleodeCount: '156m2', decayType: ['IT']},
    {nucleodeCount: '157', decayType: ['EC']},
    {nucleodeCount: '158', decayType: ['b<sup>+</sup> (83.4%)']},
    {nucleodeCount: '158', decayType: ['b<sup>-</sup> (16.6%)']},
    {nucleodeCount: '158m1', decayType: ['IT']},
    {nucleodeCount: '158m2', decayType: ['IT']},
    {nucleodeCount: '160', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '161', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '162', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '163', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '164', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '165', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '165m', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '166m', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '168m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '170', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>']},
]
