const thorium = [
    {nucleodeCount: '207', decayType: ['a']},
    {nucleodeCount: '208', decayType: ['a']},
    {nucleodeCount: '209', decayType: ['a']},
    {nucleodeCount: '210', decayType: ['a']},
    {nucleodeCount: '211', decayType: ['a']},
    {nucleodeCount: '212', decayType: ['a']},
    {nucleodeCount: '213', decayType: ['a']},
    {nucleodeCount: '213m', decayType: ['IT']},
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '214m', decayType: ['IT']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '215m', decayType: ['IT']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m1', decayType: ['IT']},
    {nucleodeCount: '216m1', decayType: ['a']},
    {nucleodeCount: '216m2', decayType: ['IT']},
    {nucleodeCount: '216m3', decayType: ['IT']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '217m1', decayType: ['IT']},
    {nucleodeCount: '217m2', decayType: ['IT']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '220', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['a']},
    {nucleodeCount: '223', decayType: ['a']},
    {nucleodeCount: '224', decayType: ['1.04(2)&nbsp;s']},
    {nucleodeCount: '224', decayType: ['a<ref group="n">Theorized to also undergo b+b+ decay to <sup>224</sup>Ra</ref>']},
    {nucleodeCount: '225', decayType: ['a']},
    {nucleodeCount: '225', decayType: ['EC']},
    {nucleodeCount: '226', decayType: ['a']},
    {nucleodeCount: '226', decayType: ['[[cluster decay', 'CD]] (<{{val', '3.2e-12}})']},
    {nucleodeCount: '227', decayType: ['a']},
    {nucleodeCount: '227', decayType: ['(1/2+)']},
    {nucleodeCount: '228', decayType: ['a']},
    {nucleodeCount: '228', decayType: ['rowspan=2', '0+']},
    {nucleodeCount: '228', decayType: ['[[Cluster decay', 'CD]] (1.13x10<sup>-11</sup)']},
    {nucleodeCount: '229', decayType: ['a']},
    {nucleodeCount: '229', decayType: ['5/2+']},
    {nucleodeCount: '229m', decayType: ['7(1)&nbsp;MUs<ref name="Seiferle2017" />']},
    {nucleodeCount: '229m', decayType: ['IT<ref group="n" name=229m>Neutral <sup>229m</sup>Th decays rapidly by [[internal conversion]], ejecting an electron.  There is not enough energy to eject a second electron, so <sup>229m</sup>Th<sup>+</sup> ions live much longer, decaying by gamma emission.  See {{alink', 'Thorium-229m}}.</ref>']},
    {nucleodeCount: '229m', decayType: ['[[Gamma decay', 'g]]<ref group="n" name=229m/>']},
    {nucleodeCount: '230', decayType: ['a']},
    {nucleodeCount: '230', decayType: ['rowspan=3', '0+']},
    {nucleodeCount: '230', decayType: ['CD (5.8x10<sup>-11</sup)']},
    {nucleodeCount: '231', decayType: ['b-']},
    {nucleodeCount: '232', decayType: ['rowspan=4', "'''1.40(1)x10<sup>10</sup>&nbsp;y'''"]},
    {nucleodeCount: '232', decayType: ['a<ref group="n">Theorized to also undergo b-b- decay to <sup>232</sup>U</ref>']},
    {nucleodeCount: '232', decayType: ['CD (<2.78x10<sup>-10</sup)']},
    {nucleodeCount: '232', decayType: ['CD (<2.78x10<sup>-10</sup)']},
    {nucleodeCount: '233', decayType: ['b-']},
    {nucleodeCount: '233', decayType: ['1/2+']},
    {nucleodeCount: '234', decayType: ['b-']},
    {nucleodeCount: '235', decayType: ['b-']},
    {nucleodeCount: '236', decayType: ['b-']},
    {nucleodeCount: '237', decayType: ['b-']},
    {nucleodeCount: '238', decayType: ['b-']},
]
