const thulium = [
    {nucleodeCount: '144', decayType: ['[[proton emission', 'p]]']},
    {nucleodeCount: '145', decayType: ['p']},
    {nucleodeCount: '146', decayType: ['p']},
    {nucleodeCount: '146m1', decayType: ['p']},
    {nucleodeCount: '146m2', decayType: ['p']},
    {nucleodeCount: '147', decayType: ['[[beta decay', 'b<sup>+</sup>]] (85%)']},
    {nucleodeCount: '147', decayType: ['p (15%)']},
    {nucleodeCount: '147m', decayType: ['p']},
    {nucleodeCount: '148', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup> (99.74%)']},
    {nucleodeCount: '149', decayType: ['b<sup>+</sup>, p (0.26%)']},
    {nucleodeCount: '150', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '150m1', decayType: ['b<sup>+</sup> (98.9%)']},
    {nucleodeCount: '150m1', decayType: ['b<sup>+</sup>, p (1.1%)']},
    {nucleodeCount: '150m2', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '151', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '151m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '151m2', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '152m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '152m2', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['[[alpha decay', 'a]] (91%)']},
    {nucleodeCount: '153', decayType: ['b<sup>+</sup> (9%)']},
    {nucleodeCount: '153m', decayType: ['a (92%)']},
    {nucleodeCount: '153m', decayType: ['b<sup>+</sup> (8%)']},
    {nucleodeCount: '154', decayType: ['b<sup>+</sup> (54%)']},
    {nucleodeCount: '154', decayType: ['a (46%)']},
    {nucleodeCount: '154m', decayType: ['a (58%)']},
    {nucleodeCount: '154m', decayType: ['b<sup>+</sup> (42%)']},
    {nucleodeCount: '155', decayType: ['b<sup>+</sup> (99.17%)']},
    {nucleodeCount: '155', decayType: ['a (0.83%)']},
    {nucleodeCount: '155m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '156', decayType: ['b<sup>+</sup> (99.94%)']},
    {nucleodeCount: '156', decayType: ['a (0.064%)']},
    {nucleodeCount: '156m', decayType: ['IT']},
    {nucleodeCount: '157', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '157', decayType: ['a (7.5{{e', '-4}}%)']},
    {nucleodeCount: '158', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '159', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '160', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '160m1', decayType: ['IT (85%)']},
    {nucleodeCount: '160m1', decayType: ['b<sup>+</sup> (15%)']},
    {nucleodeCount: '160m2', decayType: ['IT']},
    {nucleodeCount: '161', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '161m2', decayType: ['IT']},
    {nucleodeCount: '162', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '162m', decayType: ['IT (81%)']},
    {nucleodeCount: '162m', decayType: ['b<sup>+</sup> (19%)']},
    {nucleodeCount: '163', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['[[electron capture', 'EC]] (61%)']},
    {nucleodeCount: '164m', decayType: ['IT (~80%)']},
    {nucleodeCount: '164m', decayType: ['b<sup>+</sup> (~20%)']},
    {nucleodeCount: '165', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '165m1', decayType: ['IT']},
    {nucleodeCount: '165m2', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '166m1', decayType: ['IT']},
    {nucleodeCount: '166m2', decayType: ['IT']},
    {nucleodeCount: '167', decayType: ['EC']},
    {nucleodeCount: '167m1', decayType: ['IT']},
    {nucleodeCount: '167m2', decayType: ['IT']},
    {nucleodeCount: '168', decayType: ['b<sup>+</sup> (99.99%)']},
    {nucleodeCount: '168', decayType: ['b<sup>-</sup> (0.010%)']},
    {nucleodeCount: '169', decayType: ['168.93421896(79)']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['b<sup>-</sup> (99.87%)']},
    {nucleodeCount: '170', decayType: ['EC (0.131%)']},
    {nucleodeCount: '170m', decayType: ['IT']},
    {nucleodeCount: '171', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '171m1', decayType: ['IT']},
    {nucleodeCount: '171m2', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '173m1', decayType: ['IT']},
    {nucleodeCount: '173m2', decayType: ['IT']},
    {nucleodeCount: '173m3', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '174m1', decayType: ['IT (>98.5%)']},
    {nucleodeCount: '174m1', decayType: ['b<sup>-</sup> (<1.5%)']},
    {nucleodeCount: '174m2', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '175m1', decayType: ['IT']},
    {nucleodeCount: '175m2', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '177', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '177m', decayType: ['b<sup>-</sup>']},
]
