const titanium = [
    {nucleodeCount: '39', decayType: ['b+, p']},
    {nucleodeCount: '39', decayType: ['b+ (~)']},
    {nucleodeCount: '39', decayType: ['b+, 2p']},
    {nucleodeCount: '40', decayType: ['b+, p']},
    {nucleodeCount: '40', decayType: ['b+']},
    {nucleodeCount: '41', decayType: ['b+, p']},
    {nucleodeCount: '41', decayType: ['b+']},
    {nucleodeCount: '42', decayType: ['b+']},
    {nucleodeCount: '43', decayType: ['b+']},
    {nucleodeCount: '43m1', decayType: ['IT']},
    {nucleodeCount: '43m2', decayType: ['IT']},
    {nucleodeCount: '44', decayType: ['EC']},
    {nucleodeCount: '45', decayType: ['b+']},
    {nucleodeCount: '45m', decayType: ['IT']},
    {nucleodeCount: '51', decayType: ['b-']},
    {nucleodeCount: '52', decayType: ['b-']},
    {nucleodeCount: '53', decayType: ['b-']},
    {nucleodeCount: '54', decayType: ['b-']},
    {nucleodeCount: '55', decayType: ['b-']},
    {nucleodeCount: '56', decayType: ['b-']},
    {nucleodeCount: '57', decayType: ['b-']},
    {nucleodeCount: '58', decayType: ['b-']},
    {nucleodeCount: '59', decayType: ['b-']},
    {nucleodeCount: '59m', decayType: ['IT']},
    {nucleodeCount: '60', decayType: ['b-']},
    {nucleodeCount: '61', decayType: ['b-']},
    {nucleodeCount: '61m1', decayType: ['IT']},
    {nucleodeCount: '61m2', decayType: ['IT']},
]
