const tungsten = [
    {nucleodeCount: '156', decayType: ['[[beta decay', 'b<sup>+</sup>]]']},
    {nucleodeCount: 'None', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '158', decayType: ['[[alpha decay', 'a]]']},
    {nucleodeCount: '158m', decayType: ['a']},
    {nucleodeCount: '159', decayType: ['a (82%)']},
    {nucleodeCount: '160', decayType: ['a (87%)']},
    {nucleodeCount: '160', decayType: ['b<sup>+</sup> (13%)']},
    {nucleodeCount: '161', decayType: ['a (73%)']},
    {nucleodeCount: '161', decayType: ['b<sup>+</sup> (27%)']},
    {nucleodeCount: '162', decayType: ['b<sup>+</sup> (54.8%)']},
    {nucleodeCount: '162', decayType: ['a (45.2%)']},
    {nucleodeCount: '163', decayType: ['b<sup>+</sup> (86%)']},
    {nucleodeCount: '163', decayType: ['a (14%)']},
    {nucleodeCount: '163m', decayType: ['IT']},
    {nucleodeCount: '164', decayType: ['b<sup>+</sup> (96.2%)']},
    {nucleodeCount: '164', decayType: ['a (3.8%)']},
    {nucleodeCount: '165', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '166', decayType: ['b<sup>+</sup> (99.97%)']},
    {nucleodeCount: '166', decayType: ['a (0.035%)']},
    {nucleodeCount: '167', decayType: ['b<sup>+</sup> (99.96%)']},
    {nucleodeCount: '167', decayType: ['a (0.04%)']},
    {nucleodeCount: '168', decayType: ['b<sup>+</sup> (99.97%)']},
    {nucleodeCount: '168', decayType: ['a (0.032%)']},
    {nucleodeCount: '169', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '170', decayType: ['b<sup>+</sup>(99%)']},
    {nucleodeCount: '171', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '172', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '173', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '174', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '174m1', decayType: ['IT']},
    {nucleodeCount: '174m2', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '175m', decayType: ['IT']},
    {nucleodeCount: '176', decayType: ['[[Electron capture', 'EC]]']},
    {nucleodeCount: '177', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '178', decayType: ['EC']},
    {nucleodeCount: '178m', decayType: ['IT']},
    {nucleodeCount: '179', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '179m1', decayType: ['[[Isomeric transition', 'IT]] (99.71%)']},
    {nucleodeCount: '179m1', decayType: ['b<sup>+</sup> (0.29%)']},
    {nucleodeCount: '179m2', decayType: ['IT']},
    {nucleodeCount: '179m3', decayType: ['IT']},
    {nucleodeCount: '180', decayType: ['a']},
    {nucleodeCount: '180m1', decayType: ['IT']},
    {nucleodeCount: '180m2', decayType: ['IT']},
    {nucleodeCount: '181', decayType: ['EC']},
    {nucleodeCount: '181m1', decayType: ['IT']},
    {nucleodeCount: '181m2', decayType: ['IT']},
    {nucleodeCount: '182', decayType: ['181.94820564(80)']},
    {nucleodeCount: '182m', decayType: ['IT']},
    {nucleodeCount: '183', decayType: ['182.95022442(80)']},
    {nucleodeCount: '183m', decayType: ['IT']},
    {nucleodeCount: '184', decayType: ['183.95093318(79)']},
    {nucleodeCount: '184m1', decayType: ['IT']},
    {nucleodeCount: '184m2', decayType: ['IT']},
    {nucleodeCount: '185', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '185m', decayType: ['IT']},
    {nucleodeCount: '186', decayType: ['185.9543651(13)']},
    {nucleodeCount: '186m1', decayType: ['IT']},
    {nucleodeCount: '186m2', decayType: ['IT']},
    {nucleodeCount: '187', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '187m', decayType: ['colspan="3" style="text-indent:2em"', '410.06(4)&nbsp;keV']},
    {nucleodeCount: '187m', decayType: ['IT']},
    {nucleodeCount: '188', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '188m', decayType: ['IT']},
    {nucleodeCount: '189', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '190', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '190m1', decayType: ['IT']},
    {nucleodeCount: '190m2', decayType: ['IT']},
    {nucleodeCount: '191m', decayType: ['IT']},
]
