const uranium = [
    {nucleodeCount: '214', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['a']},
    {nucleodeCount: '215', decayType: ['[[Beta plus decay', 'b+]]']},
    {nucleodeCount: '216', decayType: ['a']},
    {nucleodeCount: '216m', decayType: ['a']},
    {nucleodeCount: '217', decayType: ['a']},
    {nucleodeCount: '217', decayType: ['b+']},
    {nucleodeCount: '218', decayType: ['a']},
    {nucleodeCount: '218m', decayType: ['a']},
    {nucleodeCount: '218m', decayType: ['IT']},
    {nucleodeCount: '219', decayType: ['a']},
    {nucleodeCount: '219', decayType: ['b+']},
    {nucleodeCount: '221', decayType: ['a']},
    {nucleodeCount: '221', decayType: ['b+']},
    {nucleodeCount: '222', decayType: ['a']},
    {nucleodeCount: '222', decayType: ['b+']},
    {nucleodeCount: '223', decayType: ['a']},
    {nucleodeCount: '223', decayType: ['b+']},
    {nucleodeCount: '224', decayType: ['a']},
    {nucleodeCount: '224', decayType: ['b+']},
    {nucleodeCount: '225', decayType: ['a']},
    {nucleodeCount: '226', decayType: ['a']},
    {nucleodeCount: '227', decayType: ['a']},
    {nucleodeCount: '227', decayType: ['b+']},
    {nucleodeCount: '228', decayType: ['a']},
    {nucleodeCount: '228', decayType: ['EC']},
    {nucleodeCount: '229', decayType: ['b+']},
    {nucleodeCount: '229', decayType: ['a']},
    {nucleodeCount: '230', decayType: ['a']},
    {nucleodeCount: '231', decayType: ['EC']},
    {nucleodeCount: '231', decayType: ['a']},
    {nucleodeCount: '232', decayType: ['a']},
    {nucleodeCount: '232', decayType: ['[[Cluster decay', 'CD]] (8.9x10{{sup', '-10}})']},
    {nucleodeCount: '232', decayType: ['CD']},
    {nucleodeCount: '233', decayType: ['a']},
    {nucleodeCount: '233', decayType: ['rowspan=4', '5/2+']},
    {nucleodeCount: '233', decayType: ['CD (<==7.2x10{{sup', '-11}})']},
    {nucleodeCount: '233', decayType: ['CD ']},
    {nucleodeCount: '234', decayType: ['a']},
    {nucleodeCount: '234', decayType: ['rowspan=5', '0+']},
    {nucleodeCount: '234', decayType: ['CD (1.4x10{{sup', '-11}})']},
    {nucleodeCount: '234', decayType: ['CD (<==9x10{{sup', '-12}})']},
    {nucleodeCount: '234', decayType: ['CD (<==9x10{{sup', '-12}})']},
    {nucleodeCount: '234m', decayType: ['IT']},
    {nucleodeCount: '235', decayType: ['a']},
    {nucleodeCount: '235', decayType: ['CD (8x10{{sup', '-10}})']},
    {nucleodeCount: '235', decayType: ['CD (8x10{{sup', '-10}})']},
    {nucleodeCount: '235', decayType: ['CD (8x10{{sup', '-10}})']},
    {nucleodeCount: '235m1', decayType: ['IT']},
    {nucleodeCount: '236', decayType: ['a']},
    {nucleodeCount: '236', decayType: ['rowspan=4', '0+']},
    {nucleodeCount: '236', decayType: ['CD (<==2.0x10{{sup', '-11}})<ref name="CD">{{cite journal', 'last1=Bonetti', 'first1=R.', 'last2=Guglielmetti', 'first2=A.', 'year=2007', 'title=Cluster radioactivity: an overview after twenty years', 'url=http://www.rrp.infim.ro/2007_59_2/10_bonetti.pdf', 'archive-url=https://web.archive.org/web/20160919014152/http://www.rrp.infim.ro/2007_59_2/10_bonetti.pdf', 'archive-date=19 September 2016', 'journal=Romanian Reports in Physics', 'volume=59', 'pages=301�310}}</ref>']},
    {nucleodeCount: '236', decayType: ['CD (<==2.0x10{{sup', '-11}})<ref name="CD"/>']},
    {nucleodeCount: '236m1', decayType: ['IT']},
    {nucleodeCount: '236m2', decayType: ['IT']},
    {nucleodeCount: '237', decayType: ['[[Beta minus decay', 'b-]]']},
    {nucleodeCount: '237', decayType: ['1/2+']},
    {nucleodeCount: '237m', decayType: ['IT']},
    {nucleodeCount: '238', decayType: ['a']},
    {nucleodeCount: '238', decayType: ['[[Double beta decay', 'b-b-]] (2.2x10{{sup', '-10}})']},
    {nucleodeCount: '238m', decayType: ['IT']},
    {nucleodeCount: '239', decayType: ['b-']},
    {nucleodeCount: '239', decayType: ['5/2+']},
    {nucleodeCount: '239m1', decayType: ['IT']},
    {nucleodeCount: '239m2', decayType: ['IT']},
    {nucleodeCount: '240', decayType: ['b-']},
    {nucleodeCount: '240', decayType: ['rowspan=2', '0+']},
    {nucleodeCount: '240', decayType: ['a']},
    {nucleodeCount: '241', decayType: ['b-']},
    {nucleodeCount: '242', decayType: ['b-']},
]
