const vanadium = [
    {nucleodeCount: '43', decayType: ['[[beta decay', 'b<sup>+</sup>]] (>97.5%)']},
    {nucleodeCount: '43', decayType: ['b<sup>+</sup>, [[proton emission', 'p]] (<2.5%)']},
    {nucleodeCount: '44', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '44', decayType: ['b<sup>+</sup>, [[alpha decay', 'a]] (?%)']},
    {nucleodeCount: '44m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '45', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '45m', decayType: ['[[isomeric transition', 'IT]]']},
    {nucleodeCount: '46', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '46m', decayType: ['IT']},
    {nucleodeCount: '47', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '48', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '49', decayType: ['[[electron capture', 'EC]]']},
    {nucleodeCount: '50', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '52', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '53', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '54', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '54m', decayType: ['IT']},
    {nucleodeCount: '55', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '56', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '57', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '58', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '59', decayType: ['b<sup>-</sup> (<97%)']},
    {nucleodeCount: '59', decayType: ['b<sup>-</sup>, n (>3%)']},
    {nucleodeCount: '60', decayType: ['b<sup>-</sup> (>99.9%)']},
    {nucleodeCount: '60m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '60m2', decayType: ['IT']},
    {nucleodeCount: '61', decayType: ['b<sup>-</sup> (85.5%)']},
    {nucleodeCount: '61', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (14.5%)']},
    {nucleodeCount: '62', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '63', decayType: ['b<sup>-</sup> (<65%)']},
    {nucleodeCount: '63', decayType: ['b<sup>-</sup>, n (>35%)']},
    {nucleodeCount: '64', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '64m', decayType: ['IT']},
]
