const vanadium = [
    {nucleodeCount: '43', decayType: ['b+']},
    {nucleodeCount: '43', decayType: ['b+, p']},
    {nucleodeCount: '44', decayType: ['b+']},
    {nucleodeCount: '44', decayType: ['b+, a']},
    {nucleodeCount: '44m', decayType: ['b+']},
    {nucleodeCount: '45', decayType: ['b+']},
    {nucleodeCount: '45m', decayType: ['IT']},
    {nucleodeCount: '46', decayType: ['b+']},
    {nucleodeCount: '46m', decayType: ['IT']},
    {nucleodeCount: '47', decayType: ['b+']},
    {nucleodeCount: '48', decayType: ['b+']},
    {nucleodeCount: '49', decayType: ['EC']},
    {nucleodeCount: '50', decayType: ['b+']},
    {nucleodeCount: '52', decayType: ['b-']},
    {nucleodeCount: '53', decayType: ['b-']},
    {nucleodeCount: '54', decayType: ['b-']},
    {nucleodeCount: '54m', decayType: ['IT']},
    {nucleodeCount: '55', decayType: ['b-']},
    {nucleodeCount: '56', decayType: ['b-']},
    {nucleodeCount: '57', decayType: ['b-']},
    {nucleodeCount: '58', decayType: ['b-']},
    {nucleodeCount: '59', decayType: ['b-']},
    {nucleodeCount: '59', decayType: ['b-, n']},
    {nucleodeCount: '60', decayType: ['b-']},
    {nucleodeCount: '60m1', decayType: ['b-']},
    {nucleodeCount: '60m2', decayType: ['IT']},
    {nucleodeCount: '61', decayType: ['b-']},
    {nucleodeCount: '61', decayType: ['b-, n']},
    {nucleodeCount: '62', decayType: ['b-']},
    {nucleodeCount: '63', decayType: ['b-']},
    {nucleodeCount: '63', decayType: ['b-, n']},
    {nucleodeCount: '64', decayType: ['b-']},
    {nucleodeCount: '64m', decayType: ['IT']},
]
