const xenon = [
    {nucleodeCount: '108', decayType: ['a']},
    {nucleodeCount: '109', decayType: ['a']},
    {nucleodeCount: '110', decayType: ['a']},
    {nucleodeCount: '110', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['b+']},
    {nucleodeCount: '111', decayType: ['a']},
    {nucleodeCount: '112', decayType: ['b+']},
    {nucleodeCount: '112', decayType: ['a']},
    {nucleodeCount: '113', decayType: ['b+']},
    {nucleodeCount: '113', decayType: ['b+, p']},
    {nucleodeCount: '113', decayType: ['a']},
    {nucleodeCount: '113', decayType: ['b+, a']},
    {nucleodeCount: '113m', decayType: ['IT']},
    {nucleodeCount: '114', decayType: ['b+']},
    {nucleodeCount: '115', decayType: ['b+']},
    {nucleodeCount: '115', decayType: ['b+, p']},
    {nucleodeCount: '116', decayType: ['b+']},
    {nucleodeCount: '117', decayType: ['b+']},
    {nucleodeCount: '117', decayType: ['b+, p']},
    {nucleodeCount: '118', decayType: ['b+']},
    {nucleodeCount: '119', decayType: ['b+']},
    {nucleodeCount: '119', decayType: ['EC']},
    {nucleodeCount: '120', decayType: ['b+']},
    {nucleodeCount: '121', decayType: ['b+']},
    {nucleodeCount: '122', decayType: ['EC']},
    {nucleodeCount: '123', decayType: ['b+']},
    {nucleodeCount: '123m', decayType: ['IT']},
    {nucleodeCount: '124', decayType: ['2EC']},
    {nucleodeCount: '125', decayType: ['EC / b+']},
    {nucleodeCount: '125m1', decayType: ['IT']},
    {nucleodeCount: '125m2', decayType: ['IT']},
    {nucleodeCount: '126', decayType: ['125.904297422(6)']},
    {nucleodeCount: '127', decayType: ['EC']},
    {nucleodeCount: '127m', decayType: ['IT']},
    {nucleodeCount: '128m', decayType: ['IT']},
    {nucleodeCount: '129m', decayType: ['IT']},
    {nucleodeCount: '131m', decayType: ['IT']},
    {nucleodeCount: '132m', decayType: ['IT']},
    {nucleodeCount: '133', decayType: ['b-']},
    {nucleodeCount: '133m1', decayType: ['IT']},
    {nucleodeCount: '133m2', decayType: ['IT']},
    {nucleodeCount: '134', decayType: ['133.905393030(6)']},
    {nucleodeCount: '134m1', decayType: ['IT']},
    {nucleodeCount: '134m2', decayType: ['IT']},
    {nucleodeCount: '136', decayType: ['b-']},
    {nucleodeCount: '135m', decayType: ['IT']},
    {nucleodeCount: '135m', decayType: ['b-']},
    {nucleodeCount: '136', decayType: ['b-b-']},
    {nucleodeCount: '136m', decayType: ['IT']},
    {nucleodeCount: '137', decayType: ['b-']},
    {nucleodeCount: '138', decayType: ['b-']},
    {nucleodeCount: '139', decayType: ['b-']},
    {nucleodeCount: '140', decayType: ['b-']},
    {nucleodeCount: '141', decayType: ['b-']},
    {nucleodeCount: '141', decayType: ['b-, n']},
    {nucleodeCount: '142', decayType: ['b-']},
    {nucleodeCount: '142', decayType: ['b-, n']},
    {nucleodeCount: '143', decayType: ['b-']},
    {nucleodeCount: '143', decayType: ['b-, n']},
    {nucleodeCount: '144', decayType: ['b-']},
    {nucleodeCount: '144', decayType: ['b-, n']},
    {nucleodeCount: '145', decayType: ['b-']},
    {nucleodeCount: '145', decayType: ['b-, n']},
    {nucleodeCount: '146', decayType: ['b-']},
    {nucleodeCount: '146', decayType: ['b-, n']},
    {nucleodeCount: '147', decayType: ['b-']},
    {nucleodeCount: '147', decayType: ['b-, n']},
    {nucleodeCount: '148', decayType: ['b-']},
]
