const ytterbium = [
    {nucleodeCount: '149', decayType: ['b+, p']},
    {nucleodeCount: '149', decayType: ['b+ (rare)']},
    {nucleodeCount: '150', decayType: ['b+']},
    {nucleodeCount: '151', decayType: ['b+']},
    {nucleodeCount: '151', decayType: ['b+, p (rare)']},
    {nucleodeCount: '151m1', decayType: ['b+']},
    {nucleodeCount: '151m1', decayType: ['b+, p (rare)']},
    {nucleodeCount: '151m2', decayType: ['IT']},
    {nucleodeCount: '151m3', decayType: ['IT']},
    {nucleodeCount: '152', decayType: ['b+']},
    {nucleodeCount: '152m', decayType: ['IT']},
    {nucleodeCount: '153', decayType: ['b+']},
    {nucleodeCount: '153', decayType: ['b+, p']},
    {nucleodeCount: '153m', decayType: ['IT']},
    {nucleodeCount: '154', decayType: ['a']},
    {nucleodeCount: '154', decayType: ['b+']},
    {nucleodeCount: '155', decayType: ['a']},
    {nucleodeCount: '155', decayType: ['b+']},
    {nucleodeCount: '156', decayType: ['b+']},
    {nucleodeCount: '156', decayType: ['a']},
    {nucleodeCount: '157', decayType: ['b+']},
    {nucleodeCount: '157', decayType: ['a (rare)']},
    {nucleodeCount: '158', decayType: ['b+']},
    {nucleodeCount: '158', decayType: ['a']},
    {nucleodeCount: '159', decayType: ['b+']},
    {nucleodeCount: '160', decayType: ['b+']},
    {nucleodeCount: '161', decayType: ['b+']},
    {nucleodeCount: '162', decayType: ['b+']},
    {nucleodeCount: '163', decayType: ['b+']},
    {nucleodeCount: '164', decayType: ['EC']},
    {nucleodeCount: '165', decayType: ['b+']},
    {nucleodeCount: '165m', decayType: ['IT']},
    {nucleodeCount: '166', decayType: ['EC']},
    {nucleodeCount: '167', decayType: ['b+']},
    {nucleodeCount: '167m', decayType: ['IT']},
    {nucleodeCount: '169', decayType: ['EC']},
    {nucleodeCount: '169m', decayType: ['IT']},
    {nucleodeCount: '170', decayType: ['169.934767243(11)']},
    {nucleodeCount: '170m', decayType: ['IT']},
    {nucleodeCount: '171', decayType: ['170.936331515(14)']},
    {nucleodeCount: '171m1', decayType: ['IT']},
    {nucleodeCount: '171m2', decayType: ['IT']},
    {nucleodeCount: '172', decayType: ['171.936386654(15)']},
    {nucleodeCount: '172m', decayType: ['IT']},
    {nucleodeCount: '173', decayType: ['172.938216212(12)']},
    {nucleodeCount: '173m', decayType: ['IT']},
    {nucleodeCount: '174', decayType: ['173.938867546(12)']},
    {nucleodeCount: '174m1', decayType: ['IT']},
    {nucleodeCount: '174m2', decayType: ['IT']},
    {nucleodeCount: '175', decayType: ['b-']},
    {nucleodeCount: '175m', decayType: ['IT']},
    {nucleodeCount: '176m', decayType: ['IT']},
    {nucleodeCount: '176m', decayType: ['b- (<10#)']},
    {nucleodeCount: '177', decayType: ['b-']},
    {nucleodeCount: '177m', decayType: ['IT']},
    {nucleodeCount: '178', decayType: ['b-']},
    {nucleodeCount: '179', decayType: ['b-']},
    {nucleodeCount: '180', decayType: ['b-']},
    {nucleodeCount: '181', decayType: ['b-']},
    {nucleodeCount: 'None', decayType: ['b-']},
    {nucleodeCount: '183', decayType: ['b-']},
    {nucleodeCount: '184', decayType: ['b-']},
    {nucleodeCount: '185', decayType: ['b-']},
]
