const yttrium = [
    {nucleodeCount: '76', decayType: ['b+']},
    {nucleodeCount: '76', decayType: ['p']},
    {nucleodeCount: '76', decayType: ['b+, p']},
    {nucleodeCount: '77', decayType: ['b+']},
    {nucleodeCount: '77', decayType: ['p']},
    {nucleodeCount: '77', decayType: ['b+, p']},
    {nucleodeCount: '78', decayType: ['b+']},
    {nucleodeCount: '78', decayType: ['b+, p']},
    {nucleodeCount: '78m', decayType: ['b+']},
    {nucleodeCount: '78m', decayType: ['b+, p']},
    {nucleodeCount: '79', decayType: ['b+']},
    {nucleodeCount: '80', decayType: ['b+']},
    {nucleodeCount: '80m1', decayType: ['IT']},
    {nucleodeCount: '80m1', decayType: ['b+']},
    {nucleodeCount: '80m2', decayType: ['IT']},
    {nucleodeCount: '81', decayType: ['b+']},
    {nucleodeCount: '82', decayType: ['b+']},
    {nucleodeCount: '82m1', decayType: ['IT']},
    {nucleodeCount: '82m2', decayType: ['IT']},
    {nucleodeCount: '83', decayType: ['b+']},
    {nucleodeCount: '83m', decayType: ['b+']},
    {nucleodeCount: '83m', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b+']},
    {nucleodeCount: '84m1', decayType: ['b+']},
    {nucleodeCount: '84m2', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b+']},
    {nucleodeCount: '85m1', decayType: ['b+']},
    {nucleodeCount: '85m1', decayType: ['IT']},
    {nucleodeCount: '85m2', decayType: ['IT']},
    {nucleodeCount: '86', decayType: ['b+']},
    {nucleodeCount: '86m1', decayType: ['IT']},
    {nucleodeCount: '86m1', decayType: ['b+']},
    {nucleodeCount: '86m2', decayType: ['IT']},
    {nucleodeCount: '87', decayType: ['b+']},
    {nucleodeCount: '87m', decayType: ['IT']},
    {nucleodeCount: '87m', decayType: ['b+']},
    {nucleodeCount: '88', decayType: ['b+']},
    {nucleodeCount: '88m1', decayType: ['IT']},
    {nucleodeCount: '88m2', decayType: ['IT']},
    {nucleodeCount: '89m', decayType: ['IT']},
    {nucleodeCount: '90', decayType: ['b-']},
    {nucleodeCount: '90m', decayType: ['IT']},
    {nucleodeCount: '90m', decayType: ['b-']},
    {nucleodeCount: '91', decayType: ['b-']},
    {nucleodeCount: '91m', decayType: ['IT']},
    {nucleodeCount: '91m', decayType: ['b-']},
    {nucleodeCount: '92', decayType: ['b-']},
    {nucleodeCount: '92m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b-']},
    {nucleodeCount: '93m', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b-']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b-']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b-']},
    {nucleodeCount: '96m1', decayType: ['b-']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b-']},
    {nucleodeCount: '97', decayType: ['b-, n']},
    {nucleodeCount: '97m1', decayType: ['b-']},
    {nucleodeCount: '97m1', decayType: ['IT']},
    {nucleodeCount: '97m1', decayType: ['b-, n']},
    {nucleodeCount: '97m2', decayType: ['IT']},
    {nucleodeCount: '97m2', decayType: ['b-']},
    {nucleodeCount: '98', decayType: ['b-']},
    {nucleodeCount: '98', decayType: ['b-, n']},
    {nucleodeCount: '98m1', decayType: ['IT']},
    {nucleodeCount: '98m2', decayType: ['b-']},
    {nucleodeCount: '98m2', decayType: ['b-, n']},
    {nucleodeCount: '98m2', decayType: ['IT']},
    {nucleodeCount: '98m3', decayType: ['IT']},
    {nucleodeCount: '98m4', decayType: ['IT']},
    {nucleodeCount: '98m5', decayType: ['IT']},
    {nucleodeCount: '98m6', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b-']},
    {nucleodeCount: '99', decayType: ['b-, n']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['b-']},
    {nucleodeCount: '100', decayType: ['b-, n']},
    {nucleodeCount: '100m', decayType: ['b-']},
    {nucleodeCount: '100m', decayType: ['b-, n']},
    {nucleodeCount: '101', decayType: ['b-']},
    {nucleodeCount: '101', decayType: ['b-, n']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '102', decayType: ['b-, n']},
    {nucleodeCount: '102m', decayType: ['b-']},
    {nucleodeCount: '102m', decayType: ['b-, n']},
    {nucleodeCount: '102m', decayType: ['IT']},
    {nucleodeCount: '103', decayType: ['b-']},
    {nucleodeCount: '103', decayType: ['b-, n']},
    {nucleodeCount: '104', decayType: ['b-']},
    {nucleodeCount: '104', decayType: ['b-, n']},
    {nucleodeCount: '104', decayType: ['b-, 2n']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '105', decayType: ['b-, n']},
    {nucleodeCount: '105', decayType: ['b-, 2n']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '106', decayType: ['b-, n']},
    {nucleodeCount: '106', decayType: ['b-, 2n']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '107', decayType: ['b-, n']},
    {nucleodeCount: '107', decayType: ['b-, 2n']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '108', decayType: ['b-, n']},
    {nucleodeCount: '108', decayType: ['b-, 2n']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '109', decayType: ['b-, n']},
    {nucleodeCount: '109', decayType: ['b-, 2n']},
]
