const yttrium = [
    {nucleodeCount: '76', decayType: ['[[beta decay', 'b<sup>+</sup>]]?']},
    {nucleodeCount: '76', decayType: ['[[proton emission', 'p]]?']},
    {nucleodeCount: '76', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '77', decayType: ['p?']},
    {nucleodeCount: '77', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '78', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '78', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '78m', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '78m', decayType: ['b<sup>+</sup>, p?']},
    {nucleodeCount: '79', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '80', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '80m1', decayType: ['[[isomeric transition', 'IT]] (81%)']},
    {nucleodeCount: '80m1', decayType: ['b<sup>+</sup> (19%)']},
    {nucleodeCount: '80m2', decayType: ['IT']},
    {nucleodeCount: '81', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '82', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '82m1', decayType: ['IT']},
    {nucleodeCount: '82m2', decayType: ['IT']},
    {nucleodeCount: '83', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '83m', decayType: ['b<sup>+</sup> (60%)']},
    {nucleodeCount: '83m', decayType: ['IT (40%)']},
    {nucleodeCount: '84', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '84m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '84m2', decayType: ['IT']},
    {nucleodeCount: '85', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '85m1', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '85m1', decayType: ['IT?']},
    {nucleodeCount: '85m2', decayType: ['IT']},
    {nucleodeCount: '86', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '86m1', decayType: ['IT (99.31%)']},
    {nucleodeCount: '86m1', decayType: ['b<sup>+</sup> (0.69%)']},
    {nucleodeCount: '86m2', decayType: ['IT']},
    {nucleodeCount: '87', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '87m', decayType: ['IT (98.43%)']},
    {nucleodeCount: '87m', decayType: ['b<sup>+</sup> (1.57%)']},
    {nucleodeCount: '88', decayType: ['b<sup>+</sup>']},
    {nucleodeCount: '88m1', decayType: ['IT']},
    {nucleodeCount: '88m2', decayType: ['IT']},
    {nucleodeCount: '89m', decayType: ['IT']},
    {nucleodeCount: '90', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '90m', decayType: ['IT']},
    {nucleodeCount: '90m', decayType: ['b<sup>-</sup> (0.0018%)']},
    {nucleodeCount: '91', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '91m', decayType: ['IT']},
    {nucleodeCount: '91m', decayType: ['b<sup>-</sup>?']},
    {nucleodeCount: '92', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '92m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '93m', decayType: ['IT']},
    {nucleodeCount: '94', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '94m', decayType: ['IT']},
    {nucleodeCount: '95', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '95m', decayType: ['IT']},
    {nucleodeCount: '96', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '96m1', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '96m2', decayType: ['IT']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup> (99.945%)']},
    {nucleodeCount: '97', decayType: ['b<sup>-</sup>, [[neutron emission', 'n]] (0.055%)']},
    {nucleodeCount: '97m1', decayType: ['b<sup>-</sup> (>99.2%)']},
    {nucleodeCount: '97m1', decayType: ['IT (<0.7%)']},
    {nucleodeCount: '97m1', decayType: ['b<sup>-</sup>, n (0.11%)']},
    {nucleodeCount: '97m2', decayType: ['IT (94.8%)']},
    {nucleodeCount: '97m2', decayType: ['b<sup>-</sup> (5.2%)']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup> (99.67%)']},
    {nucleodeCount: '98', decayType: ['b<sup>-</sup>, n (0.33%)']},
    {nucleodeCount: '98m1', decayType: ['IT']},
    {nucleodeCount: '98m2', decayType: ['b<sup>-</sup> (96.56%)']},
    {nucleodeCount: '98m2', decayType: ['b<sup>-</sup>, n (3.44%)']},
    {nucleodeCount: '98m2', decayType: ['IT?']},
    {nucleodeCount: '98m3', decayType: ['IT']},
    {nucleodeCount: '98m4', decayType: ['IT']},
    {nucleodeCount: '98m5', decayType: ['IT']},
    {nucleodeCount: '98m6', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup> (98.23%)']},
    {nucleodeCount: '99', decayType: ['b<sup>-</sup>, n (1.77%)']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '100', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '100m', decayType: ['b<sup>-</sup> (98.92%)']},
    {nucleodeCount: '100m', decayType: ['b<sup>-</sup>, n (1.08%)']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup> (97.7%)']},
    {nucleodeCount: '101', decayType: ['b<sup>-</sup>, n (2.3%)']},
    {nucleodeCount: '101m', decayType: ['IT']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup> (>97.4%)']},
    {nucleodeCount: '102', decayType: ['b<sup>-</sup>, n (<2.6%)']},
    {nucleodeCount: '102m', decayType: ['b<sup>-</sup> (>97.4%)']},
    {nucleodeCount: '102m', decayType: ['b<sup>-</sup>, n (<2.6%)']},
    {nucleodeCount: '102m', decayType: ['IT?']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup> (92.0%)']},
    {nucleodeCount: '103', decayType: ['b<sup>-</sup>, n (8.0%)']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup> (66%)']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup>, n (34%)']},
    {nucleodeCount: '104', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>, n (<82%)']},
    {nucleodeCount: '105', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '106', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '107', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '108', decayType: ['b<sup>-</sup>, 2n?']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>, n?']},
    {nucleodeCount: '109', decayType: ['b<sup>-</sup>, 2n?']},
]
