const zirconium = [
    {nucleodeCount: '79', decayType: ['b+']},
    {nucleodeCount: '80', decayType: ['b+']},
    {nucleodeCount: '81', decayType: ['b+']},
    {nucleodeCount: '81', decayType: ['b+, p']},
    {nucleodeCount: '82', decayType: ['b+']},
    {nucleodeCount: '83', decayType: ['b+']},
    {nucleodeCount: '83', decayType: ['b+, p']},
    {nucleodeCount: '83m1', decayType: ['IT']},
    {nucleodeCount: '83m2', decayType: ['IT']},
    {nucleodeCount: '84', decayType: ['b+']},
    {nucleodeCount: '85', decayType: ['b+']},
    {nucleodeCount: '85m', decayType: ['IT']},
    {nucleodeCount: '85m', decayType: ['b+']},
    {nucleodeCount: '86', decayType: ['b+']},
    {nucleodeCount: '87', decayType: ['b+']},
    {nucleodeCount: '87m', decayType: ['IT']},
    {nucleodeCount: '88', decayType: ['EC']},
    {nucleodeCount: '88m', decayType: ['IT']},
    {nucleodeCount: '89', decayType: ['b+']},
    {nucleodeCount: '89m', decayType: ['IT']},
    {nucleodeCount: '89m', decayType: ['b+']},
    {nucleodeCount: '90m1', decayType: ['IT']},
    {nucleodeCount: '90m2', decayType: ['IT']},
    {nucleodeCount: '91m', decayType: ['IT']},
    {nucleodeCount: '93', decayType: ['b-<ref name="Zr93"/>']},
    {nucleodeCount: '93', decayType: ['b-<ref name="Zr93"/>']},
    {nucleodeCount: '95', decayType: ['b-']},
    {nucleodeCount: '96', decayType: ["'''2.34(17)x10<sup>19</sup>&nbsp;y'''"]},
    {nucleodeCount: '96', decayType: ['b-b-{{refn', 'group="n"', 'Theorized to also undergo b- decay to <sup>96</sup>Nb with a [[partial half-life]] greater than 2.4x10<sup>19</sup>&nbsp;y<ref>{{cite journal', 'last1=Finch', 'first1=S.W.', 'last2=Tornow', 'first2=W.', 'title=Search for the b decay of <sup>96</sup>Zr', 'date=2016', 'journal=Nuclear Instruments and Methods in Physics Research Section A: Accelerators, Spectrometers, Detectors and Associated Equipment', 'volume=806', 'pages=70�74', 'doi=10.1016/j.nima.2015.09.098', 'bibcode=2016NIMPA.806...70F', 'doi-access=free }}</ref>}}']},
    {nucleodeCount: '97', decayType: ['b-']},
    {nucleodeCount: '97m', decayType: ['IT']},
    {nucleodeCount: '98', decayType: ['b-']},
    {nucleodeCount: '98m', decayType: ['IT']},
    {nucleodeCount: '99', decayType: ['b-']},
    {nucleodeCount: '99m', decayType: ['IT']},
    {nucleodeCount: '100', decayType: ['b-']},
    {nucleodeCount: '101', decayType: ['b-']},
    {nucleodeCount: '102', decayType: ['b-']},
    {nucleodeCount: '103', decayType: ['b-']},
    {nucleodeCount: '103', decayType: ['b-, n']},
    {nucleodeCount: '104', decayType: ['b-']},
    {nucleodeCount: '104', decayType: ['b-, n']},
    {nucleodeCount: '105', decayType: ['b-']},
    {nucleodeCount: '105', decayType: ['b-, n']},
    {nucleodeCount: '106', decayType: ['b-']},
    {nucleodeCount: '106', decayType: ['b-, n']},
    {nucleodeCount: '107', decayType: ['b-']},
    {nucleodeCount: '107', decayType: ['b-, n']},
    {nucleodeCount: '108', decayType: ['b-']},
    {nucleodeCount: '108m', decayType: ['IT']},
    {nucleodeCount: '109', decayType: ['b-']},
    {nucleodeCount: '110', decayType: ['b-']},
    {nucleodeCount: '111', decayType: ['b-']},
    {nucleodeCount: '112', decayType: ['b-']},
]
